### ISSUE TITLE
Request: Mars5e Compatibility (or general mod compatibility)

### ISSUE THREAD

**Issue by Moerill** [otigon/automated-jb2a-animations#10]
Heya, 
I *love* this mod! And i really would love to make it work with my DnD5e roller [Mars 5e](https://github.com/Moerill/fvtt-mars-5e).
Skimming your code i notice you either use MidiQoL's hook or try to decipher the Chat Message (which probably breaks with mars modifying the chat messages heavily).

So.. i wanted to ask if we could work smth out to make this 2 modules work nice together?  

Some ideas from me: Either you provide a hook, which i or other modules can call to trigger the animations, or expose a method that can be called.  
Or I could do smth like the MidiQoL hook from my side, which you can hook on.  
Just some quick ideas from my side, maybe you got some better solution in mind!

**Comment by otigon** [comment]
Hey there!

I was looking through Mars 5e the other week trying to figure this same thing out. A few of the biggest requests my my module have been for the ability to play the animations at certain times, either on Attack Rolls, or Damage Rolls (Or on Hits using Midi). For Core 5e, I was able to distinguish between the Damage and Attack Rolls through the Chat Card.

Looking at Mars specifically, it's hard to distinguish between when the Attack Roll is made versus the Damage Roll (It's quite possible I'm just not looking in the right place). If this can be worked out on Mars' end, it's a pretty simple addition to get full support on here.

Both ways you mention above would work too, and I'm fully open to suggestions (very new to this whole thing). I'm close to releasing a pretty big update for the way the Animations are customized, but none of these changes should mess with the adding support for Mars. Feel free to reach out on Discord too and we can see about figuring this out.

**Comment by otigon** [comment]
@Moerill  Wanted to follow up again after having some more time to chew on this.

My first thought was a simple hook provided by Mars for Attack Rolls and Damage Rolls separately, though I'm uncertain how complex that would be. Or, if there may be a better way on my end to provide something for all the different rolling modules that would help out.

You hit it on the nose with how I'm doing it now. I run off the RollComplete and damageRollComplete hook in Midi, then for Core and MRE I'm able to snuff out the right spots in the Chat Message. The current problem I hit with Mars is a sure way to differentiate between Attack Rolls and Damage Rolls

**Comment by Moerill** [comment]
> My first thought was a simple hook provided by Mars for Attack Rolls and Damage Rolls separately, though I'm uncertain how complex that would be
I wouldn't advise that.. parsing HTML is to error prone for this (imo). This may additionally be a problem since the cards are not always rolled on creation, but sometimes later on clicks..
And multiple targets on one card, ... 

My preferred way would be for you to expose some function like..
``playAnimation(sourceToken, [targetToken1, targetToken2], item)``
This at least would make it easier for other modules to maybe jump on this and use it as well.

*If* you do not want that, i can add hooks like 
``Hooks.callAll('mars5e.attackRoll(source, target, item, {success})``
``Hooks.callAll('mars5e.damageRoll(source, target, item)``
in the next patch. (neither name nor parameters are set here, so.. if we go this way i'm open for suggestions!)

**Comment by otigon** [comment]
@Moerill I've just finished work on the release. I like the idea of providing a function to call, and I'll fiddle with it this weekend and see how best to implement that.

**Comment by Moerill** [comment]
Ok, perfect! 
Very excited!
feel free to hit me up on discord or so if you want some feedback / testing / ...

**Comment by otigon** [comment]
@Moerill I think I've just about got this ready to test. You're blanked out for me on Discord (can't send messages to you), so send me a message when you're free and I can show you what I've got

**Comment by MrVauxs** [comment]
Hi! Has this been actually resolved? 
The two are not compatible on Foundry 0.8.6, MARS 1.6.1 and 0.3.61 Automated Animations.

**Comment by Moerill** [comment]
See https://github.com/Moerill/fvtt-mars-5e/issues/101
