### ISSUE TITLE
Animation Fails to run on weapons with melee and range behavior (Foundry 0.7.10 and Older Midi-Qol Conflict?)

### ISSUE THREAD

**Issue by daft-develop** [otigon/automated-jb2a-animations#100]
Hello,

I think I've run into a corner case where some of the weapon animations fail to play due to a missing function in an older Midi-Qol version (Midi 0.3.60 is the latest available version in Foundry 0.7.10 AFAIK):

Setup working as expected:
Foundry 0.7.10
System - DnD 5e 1.2.4
Modules Installed and Active (2): AA 0.3.70, JB2A Free Content 0.2.0

With just those two modules, all working as expected (spells, range weapons, melee and thrown weapons). Console error about missing TokenMagic, but no surprise since I don't have it enabled. Enabling TokenMagic adds the effects as expected.

Setup that causes issues:
Same as above, but also enable Midi-Qol (version 0.3.60, latests I can get w/ Foundry 0.7.10)

When you enable the Midi-QoL module and use auto rolls, spells and range weapons still animate as before, but melee and thrown weapons (e.g. dagger or handaxe) don't animate and the console reports the following error:

> midi-handler.js:275 Uncaught (in promise) TypeError: MidiQOL.getDistance is not a function
>    at MidiHandler.getDistanceTo (midi-handler.js:275)
>   at cast (melee-range-attacks.js:152)
>  at meleeRangeSwitch (melee-range-attacks.js:456)

I'm guessing it's a non-issue in Foundry 0.8.6 and Midi-QoL later versions likely have the missing function. I'm sure once I migrate to 0.8.6 it'll be fixed, but wanted to give a heads up for anyone else hanging onto 0.7.10 for a bit.

**Comment by otigon** [comment]
Thanks for the heads up. I just pushed a fix for this on version 0.3.72
