### ISSUE TITLE
Minimal Roll Enchancements compatibility

### ISSUE THREAD

**Issue by benbarbour** [otigon/automated-jb2a-animations#101]
I'm not sure if a compatibility patch should be made here or in MRE, but if it's set up to auto roll attacks then AA doesn't detect those auto rolls.

AA also doesn't seem to detect damage rolls from MRE when "Play Attack Animations on Damage Rolls Only" is checked.

**Comment by otigon** [comment]
Thanks for the log, is this in Foundry 0.8.6?

**Comment by benbarbour** [comment]
Yes

**Comment by otigon** [comment]
It looks like MRE dropped a few flags that they previously added that allowed A-A to key the animations. I'll reach out to the Dev to see about getting that added back in

**Comment by otigon** [comment]
@benbarbour I've updated some things so MRE should function "mostly" normal now. As in, it will work with attack rolls. I've also updated some things based on an active MRE pull request, so when they get that integrated MRE will function as normal with Automated Animations
