### ISSUE TITLE
[Request] Support for Pathfinder 2

### ISSUE THREAD

**Issue by LonePaladin** [otigon/automated-jb2a-animations#102]
PF2's system framework already has options to automate spell area templates and conditions, so it should be comparatively easy to piggyback onto that and add sound and animation.

**Comment by otigon** [comment]
The way PF2 currently stands, there is nothing linking the data on item use (i.e. chat card outputs) to the actual items that they represent. Automated Animations stores all the animation data on the Item Flags, and without being able to reliably access that data there is no way to add support for where PF2 currently stands. The data output when an Item is used has zero reference to the Item or Item ID.

I've been told they are working to revamp some things this summer, so this may change later down the road
