### ISSUE TITLE
Teleport effect leaving token invisible on landing

### ISSUE THREAD

**Issue by siliconsaint** [otigon/automated-jb2a-animations#107]
Per our chat on discord.  Any use of teleport on chrome + other browsers is leaving the token invisible.  

Find the culprit confirmed this.  

<img width="540" alt="Screen Shot 2021-06-15 at 8 45 53 AM" src="https://user-images.githubusercontent.com/56798973/122274997-30e85d80-ceb1-11eb-9297-bacf8a6a7319.png">

Just wanted to put a bug reminder in.

**Comment by otigon** [comment]
I'm going to tweak how I toggle the token invisibility to hopefully help. The only way I've been able to replicate this is if I use the Firefox browser
