### ISSUE TITLE
autoanimations.js line 286

### ISSUE THREAD

**Issue by Jonwh25** [otigon/automated-jb2a-animations#108]
Looks like an old bug (https://github.com/otigon/automated-jb2a-animations/issues/46) has resurfaced.

![image](https://user-images.githubusercontent.com/60674327/122602923-724f4900-d028-11eb-8f05-16b5ccce2b49.png)

**Comment by otigon** [comment]
yeah I don't think I ever fixed it properly. I'll take a look this weekend and see what I can do

**Comment by otigon** [comment]
Pretty sure this is fixed for good now as of 0.3.81
