### ISSUE TITLE
[FEATURE REQUEST] Infinite loop for templates

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#114]
Hello,

Usually, we want spell templates to stop, like fireball.
Bur for some spells, like zone of truth, it would be nice if the animation kept looping until the template is deleted from the scene.

**Comment by otigon** [comment]
This will be doable once I get all the code written for persistent effects. What it will do is place a Video Tile on the canvas instead of simply playing a video

**Comment by otigon** [comment]
You can now place tiles on the canvas through the Template feature as of 0.5.0. This is only usable for Circular and Square templates
