### ISSUE TITLE
Feature Request: Pathfinder2 Support

### ISSUE THREAD

**Issue by Nuku** [otigon/automated-jb2a-animations#116]
Just to meekly inquire. PF2 support would be quite nice, thanks!

**Comment by otigon** [comment]
I'd love to support it as well, but not possible at the moment unfortunately. I need to wait until their Summer revamp on the item system to see if I can make it work afterwards

**Comment by otigon** [comment]
going to close this out, as AA should be working in PF2e now. They are adding some other stuff soon that will allow me to shore up PF2e support more
