### ISSUE TITLE
Feature request: Centralized Sound override

### ISSUE THREAD

**Issue by franckflo** [otigon/automated-jb2a-animations#117]
First, thanks for this great Module :). 

Rather than having to configure each item individually, it would be nice if we could set an override list of sounds associated with a word or a list of words, something we'd set in the module's settings. 

For example, we could associate a specific sound with the keyword "sword" so that AA would automatically use that sound when someone uses an item with "sword" in its name.

**Comment by otigon** [comment]
I'll be revamping the Audio system in A-A in the near future, so I'll take a look at this. Although it might be a bit out of my depth for implementing it

**Comment by franckflo** [comment]
I believe in you :). Maybe the authors from Midi QoL and/or Token Magic FX  could help you,

**Comment by otigon** [comment]
one of my milestone items is to provide a global level user defined Autorecognition list. When I get to that point I'll see if I can implement something like this

**Comment by otigon** [comment]
Tracking Sound upgrades in #165
