### ISSUE TITLE
[Feature Request] Intergrate with Beyond20

### ISSUE THREAD

**Issue by foxreinhold** [otigon/automated-jb2a-animations#118]
DnD Beyond has such wonderful character sheets, with with the Beyond20 Chrome Extension, you can roll straight from DnD Beyond to Foundry.  It would be great if the animations were called as well as they are with the native Foundry sheets.

**Comment by otigon** [comment]
There is not really anything I can do on my end to support Beyond20. My module simply reads the chat messages posted to chat, and grabs the Item information from it. Beyond20 would need to pass that information somehow, which afaik it doesn't do yet. There is another module called D&D Beyond Gamelog that has this functionality, though A-A support is behind a Patreon subscription I think
