### ISSUE TITLE
Witch bolt errors

### ISSUE THREAD

**Issue by RogueEntityX** [otigon/automated-jb2a-animations#120]
Not sure at what point this changed, but I am getting an error with Witch Bolt in the console, and the animation is not playing. This happens whether I use the Witch Bolt spell imported from DDB, create it myself, or override any other spell to use the Witch Bolt animation. I have tested this in a newly created world, using SRD creatures and the Starter Hero Sefris (warlock).

Foundry core 0.8.8
DnD5e 1.3.6

Automated Animations 0.3.88
JB2A - Patreon Complete Collection (Raishan)
DDB Shared Compendiums (my custom share compendiums for imported DDB content)

This is the console error: 
![image](https://user-images.githubusercontent.com/72455534/124155126-25c22f80-da64-11eb-9983-853e6356c020.png)

I've tested a handful of other animations which all seem to be working properly.

**Comment by otigon** [comment]
It was a fault on my end on the 0.3.88 release. It is treating Witch Bolt and Fire Bolt like they were the new bolt animation. I'll have a fix out for this today

**Comment by otigon** [comment]
Error should be fixed as of 0.3.89
