### ISSUE TITLE
[Feature Request] Add a way to generate a template if not implemented by the system

### ISSUE THREAD

**Issue by ILikeCoolThings** [otigon/automated-jb2a-animations#127]
This is a suggestion/request to add support for spells to generate templates if a system doesn't do it by default. One example would be Starfinder.

Starfinder right now does not generate a range template when a spell is cast. Having a way to generate a template with the spell would be a HUGE help!

Let me know if you would like an example!

**Comment by otigon** [comment]
I'll see if this is possible, otherwise I'll look at simply playing the video file with the "caster" as the source and have it directed at a target, and sized off the spell settings
