### ISSUE TITLE
[ Feature suggestion - SFRPG ] - Implementing the possibility of different animations for attack, normal and crit damage/hit

### ISSUE THREAD

**Issue by Nachtrose** [otigon/automated-jb2a-animations#128]
Hi, 
first off - great job with the Starfinder implementation. Makes it 1000% cooler :-)

Now to my suggestion. Could you check the possibility of implementing different animations for attack and damage? When not using "Quick rolls", we have popup windows with buttons for attack roll and the for either normal or crit damage roll. The rolls return values, that identify which button was pressed ( which roll rolled ) so it should be possible to differentiate between the three.  It won't be automated as in 5e using midi-qol, but it should be doable. I hope. 
After playing with AA a little, you could maybe use the explosions setting for this? Setting up two explosions and instead of playing them right after the attack animation, they could be played after a damage roll is made? One for normal damage, the other for crit damage.

Thanks for your work.

**Comment by otigon** [comment]
This won't be possible without a huge rewrite of the module sorry
