### ISSUE TITLE
[Request] Starfinder: Allow a delay on the animation firing and allow for the animation to repeat

### ISSUE THREAD

**Issue by Ironxxx** [otigon/automated-jb2a-animations#130]
As above really. This would be useful in other systems as well (I use this amazing mod in PF and SF).
The audio tab allows us to set a delay for sound which is great but it would be great if we could also delay the animation as sometimes you want the animation to happen after the sound, e.g., you may have a rifle that plays a loading sound first before firing.
In addition, it would be fantastic if we could set the number of times the animation repeats, e.g., when firing a repeating weapon like a minigun I like to repeat an animation a few times to get the proper "feel" for it. 
I can do this with macros/Item Macro but your module makes stuff so much easier.

**Comment by otigon** [comment]
Hey there! The repeating of animations is already in the works. Currently I'm going through and re-coding all the animation sequences and adding additional options. After that I'll be re-doing the entire Audio system to make it more flexible as well. I'll keep these in mind while I'm doing the rewrite

**Comment by otigon** [comment]
Loops and Delays are active as of 0.5.0. I didn't set a per item Start Delay however, as I already have the Global Delay in the module settings
