### ISSUE TITLE
Feature Request: Allow Formulas in Loop Counter.

### ISSUE THREAD

**Issue by Mozmonar** [otigon/automated-jb2a-animations#131]
This one might be a little tricky considering the module covers a bunch of different rulesets which have different actor data. But for things like magic missile it might be helpful to have the ability to setup formulas for calculating the number of times to loop an animation from the actor data so that it changed dynamically. My use case would be PF1 but it obviously applies to a number of other rulesets.

**Comment by otigon** [comment]
I'll take a look after the next release (currently re-writing alot of the module). Once things settle down I could see this implemented on a system specific case

**Comment by otigon** [comment]
Not going to be adding this feature
