### ISSUE TITLE
compatibility with magic items module

### ISSUE THREAD

**Issue by drdwing** [otigon/automated-jb2a-animations#136]
This is awesome mod and my players love it a lot.
But I found that there was a problem using this mod with magic items mod.
A player tried to cast misty step spell of magic item but it didn't display range of the spell.😢
He was sad because he liked the effect of misty step.
I wish you make him happy.

**Comment by otigon** [comment]
I'll check into it this week and see what I can do

**Comment by drdwing** [comment]
I think it works now
