### ISSUE TITLE
D&D 5e Sound Issue

### ISSUE THREAD

**Issue by King-Kronos** [otigon/automated-jb2a-animations#138]
I've tried this in my game, as well as a fresh world with no modules active. Whenever I attempt to add sound to a roll and have it play, the sound never plays and I get errors in my console log. I'm using the latest stable release of both Foundry and D&D5e, as well as your module.

The message that occurs is the following:
<img width="261" alt="Untitled" src="https://user-images.githubusercontent.com/77754673/125679387-80089a7f-d00b-4e54-96e5-7ae97698dc3b.png">

**Comment by otigon** [comment]
The error looks unrelated to Automated Animations. Which type of animation are you pairing the sound with, attacks, templates etc. I have it in the schedule to refactor the audio options soon, so I'll take a look

**Comment by King-Kronos** [comment]
Turns out I didn't disable all of my modules and still had one active when I was using Find The Culprit to sort out the issue. Turns out it's two separate issues. I had Midi-Qol active and it seems to be the module affecting it (not sure what settings causing it so I just disabled it). The second issue was that I was trying to use a custom template with it (using a webm animation from the animated-spell-effects module). I am unsure why, but even though the preview for the custom template is working, and I've gone by everything in the template tutorial in your Youtube videos, template animations don't seem to want to play for me. Because of this, the sounds won't play, as it seems sounds only play if an animation has been played. If I add animations from anything other than a template, sounds now play correctly.

**Comment by otigon** [comment]
If you can let me know which specific ASE animation you were trying to use I'll see if I can replicate and pin-point the error on my end

**Comment by King-Kronos** [comment]
It's happening to me with all of them.

**Comment by otigon** [comment]
Tracking Sound upgrades in #165
