### ISSUE TITLE
Wrong animation plays

### ISSUE THREAD

**Issue by King-Kronos** [otigon/automated-jb2a-animations#139]
When having the following setup, instead of the spear animation playing when attacking from ranged, the dagger animation plays instead.
<img width="466" alt="Wrong_Spear1" src="https://user-images.githubusercontent.com/77754673/126089238-ab01abab-aa07-4a8e-ba8f-5aca1713e712.png">
Here's the animation that is playing instead
<img width="371" alt="Spear 2" src="https://user-images.githubusercontent.com/77754673/126089515-a700736b-348f-4551-8cd4-b5fa5ca9c45f.png">

**Comment by otigon** [comment]
Someone mentioned this on the discord today too. This will be fixed on the next release

**Comment by otigon** [comment]
Should be fixed as of 0.5.0
