### ISSUE TITLE
Request: Custom animations

### ISSUE THREAD

**Issue by MS-PBS** [otigon/automated-jb2a-animations#14]
It seems that you have built a strong framework for playing animations on item rolls, with checks on distances, color, etc. While the JB2A animations collection is great, I think it would be a good idea to implement a way to add custom animations to items eventually, once you have cleared the items you have in your roadmap. Please, give it some thought.

**Comment by otigon** [comment]
Where the module is at right now, the entire system is built around the specific way JB2A is able to create their animations (color checks, file name structure, offsets, timing, distances, etc., etc.). This is most prevalent with the Melee attacks and Attack Spells. Other effects that would normally be used on Templates could possibly be added in, but something like that will be much further down the road.

**Comment by MS-PBS** [comment]
Yes, I understand. JB2A's module is very well structured and that makes it easier to work with. Thank you for considering it further down the road, it would be a shame to leave other great animation modules like Animated Spell Effects out. Anyway, thank you for your module, I bought a Patreon subscription to get all the animations! Cheers.

**Comment by otigon** [comment]
Custom Animations are live as of 0.5.0
