### ISSUE TITLE
[Request] healing animation with a range of self

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#140]
Hello,

Would be great if the healing animation plays on the token rather than the target if the range is set to "SELF"
This way, we won't have to "untarget" another token to have the animation playing on the token.

Thx!

**Comment by otigon** [comment]
Healing defaults to self animation if no target is selected, but I'll see about adding a checkbox switch for this use case

**Comment by otigon** [comment]
Issue should be resolved from recent updates, ability to choose how the animation plays in On Token menus
