### ISSUE TITLE
[Feature request] lock animation with template

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#144]
Hello,

Something I noticed using the module is:
- When a template is placed, if the user move that template before the end of the animation, the animation doesn't follow the template
- When a template deleted while an animation is still playing, the animation is not deleted right away

**Comment by otigon** [comment]
For the purposes of Automated Animations, I'm looking to replicate the "instant" type effects. So when the Template is placed, the animation plays a few times and goes away. This method plays a video on the canvas where the Template is placed, and is not tied directly to it.

If you are on DnD5e, the best bet to get that accomplished is to use Token Magic Effects, or Spell Template Manager / SIF Toolkit for other systems
