### ISSUE TITLE
Animations Will Not Play At All Anymore

### ISSUE THREAD

**Issue by King-Kronos** [otigon/automated-jb2a-animations#151]
I just updated to the latest release, as well as installing the new dependency. None of my animation will play anymore, and I am getting errors in the error log when I try to get them to play.

Here is an example of an error -

<img width="274" alt="Untitled" src="https://user-images.githubusercontent.com/77754673/127044962-f0a926e2-3392-46f2-96b6-ac4f527c9416.png">

**Comment by otigon** [comment]
Are these items that have been configured with custom/overrides? If the items were configured with an add-on explosion (in this instance Melee weapons), they need to be reconfigured. If this is something else you can export the item and send it to me on Discord and I can take a look.

**Comment by otigon** [comment]
I released 0.5.04 today, let me know if this helps with your issue.

**Comment by otigon** [comment]
@King-Kronos did this get resolved? It looks like in the error you might not have the Sequencer module installed and active. It is a dependency as of 0.5.0

**Comment by billytherex** [comment]
I had this problem for a bit. I installed midi-QoL and the problem seemingly resolved itself. That was before 0.5.04, though.

**Comment by otigon** [comment]
I'll check and see if something is happening for the module without Midi installed

**Comment by vanderleitelesjr** [comment]
Not playing at all for me too, currently running version 5.07
I still have to check if it might be due to any module incompatibility.

**Comment by otigon** [comment]
So I've checked with Midi and Core rolling in 5e and everything seems to be working fine. I saw someone have issues when they updated to the latest 5e release, but I upgraded and still had no issues. If you are having this problem, please run the Find the Culprit module, leave Automated Animations and Sequencer active and see if the issue persists. Also check for errors in the console (F12) if an animation doesn't play when you are expecting it to

**Comment by vanderleitelesjr** [comment]
Sequencer was not enabled, I had no idea that a new module was required.
