### ISSUE TITLE
Feature request PF2e: Setup "Ranged" animation seperately.

### ISSUE THREAD

**Issue by Symon-S** [otigon/automated-jb2a-animations#152]
I see that when using a weapon with reach, the default thrown dagger animation is played for said reach weapon.
Just wondering if reach could be setup with a display animation up to X grids away or something of the sort.

**Comment by otigon** [comment]
That's the plan. I'm going to update the melee weapons to add an "opt-in" box for the range switch and let users manually input the range to switch the animations. After these bug reports die down this week I'll be inputting that option for release.

**Comment by Symon-S** [comment]
That is great news, keep up the good work.

**Comment by otigon** [comment]
There is some better PF2e recognition in now for reading the actor data for when to perform the animation switch(as of 0.5.05). This might help out until I get this next release out

**Comment by otigon** [comment]
The new range switch from Melee is implemented as of 0.5.19
