### ISSUE TITLE
Feature Requests: WFRP

### ISSUE THREAD

**Issue by Txus5012** [otigon/automated-jb2a-animations#153]
Hi. Nice module you've got here!

I mainly GM WFRP and I've got some suggestions for that. Some will also work for other systems with opposed rolls too.

-Allow animations for defenders: In WFRP the defender can use a weapon to defend. It would be nice to see that animated too. Specially usefull for the next point.

-Add "Only play animations for opposed rolls": A version of "Only play animations for Damage Rolls" that makes the animation(s) appear when the opposed test result appears.

-Add "Play animation only when succesfull": As spells aren't always succesfully casted. It would be nice to have an option in A-A menu to select if the animation will show always or only when the roll is succesfull. This will be also usefull for Heal (the skill) tests too, for example.

-Add a pop-out message to decide the Scale: As the range of an Aura depends on how good the casting roll was, it would be nice to show a message after the roll asking for the final Scale of the animation.

Thanks for reading. Keep up the good work!

**Comment by otigon** [comment]
Hey thanks for all the input. Once the bug reports die down from this latest release I'll take a look at these

**Comment by otigon** [comment]
Not going to be adding this feature
