### ISSUE TITLE
[BUG] Items that have the "destroy on empty" trait don't place an animation on templates

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#156]
Hello,

FVTT 0.8.8
AA 0.5.04
DD 1.3.6
BetterRolls5e 1.5.6
item https://we.tl/t-tv1EQkLKJq

When an item with the "destroy on empty" trait checked is used, and a template animation is declared on the same item, the template is placed on the canvas without animation

EDIT: same thing for ranged weapons. Actually might be the same for every item that gets destroy because the user is using the last charge.

**Comment by otigon** [comment]
This one will take some digging, though I'm not certain there is much to be done. When the animation part of the module gets started, it grabs the item data based on the Item ID. Once the game deletes the item that unique ID no longer exists. I'll take a look and see if I can tweak anything to grab the item data before the game deletes it

**Comment by otigon** [comment]
going to close this one out, I've not been able to find any way to grab the flag data since the item is destroyed.
