### ISSUE TITLE
[BUG] filePath is not defined

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#157]
Hello,

FVTT 0.8.8
AA 0.5.05
DD 1.3.6
BetterRolls5e 1.5.6
https://we.tl/t-gMuIkORc89

Using an item with AA defined will throw an error (and not animation played):
![image](https://user-images.githubusercontent.com/1687854/127311147-4c71ace4-e38c-4b9c-9585-162fd0c78321.png)

**Comment by otigon** [comment]
I just fixed that on 0.5.06
