### ISSUE TITLE
[FEATURE] Hide teleport template 

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#158]
Hello,

Would it be possible to hide the teleport template from players? In cases where the GM uses a NPC feat/action.

Right now, everyone can see the template:
![image](https://user-images.githubusercontent.com/1687854/127396533-370fc21d-c610-4563-820d-f5499dae7deb.png)

Not even sure that is possible in Foundry :)

**Comment by otigon** [comment]
That would be a neat feature to have it only show for the user summoning it. Like you mention I'm not sure if that is possible, but I'll check. I could also look at other methods

**Comment by otigon** [comment]
Did some digging on this. Unfortunately for templates there is no way to limit the view to just the client who activated it (at least not yet in Foundry). I'll look at providing some options for this feature to either not place the template, or possibly to place a drawing or something similar on the canvas for range guidance.

**Comment by otigon** [comment]
I have added the option to hide the Template Placement for teleporting, though the range restriction is still in place. Takes a little guessing on the edges of range, but that's about the best implementation I can think of for now

**Comment by DarKDinDoN** [comment]
@otigon thx!
