### ISSUE TITLE
Suggestion: sound duration

### ISSUE THREAD

**Issue by Fridan99** [otigon/automated-jb2a-animations#159]
I have noticed a detail..... when putting the sound in a template, if the sound is very long and I delete the template, the sound continues to run until the end.

When using the Spirit Guardians, I have attached a sound of 01:32min, and when I remove the template before 01:32min, the sound continues. It would be nice if the sound system had 3 elements:

1. Start the sound when the template is placed or the animation start (in case the spell has template, for the rest start when the spell is executed)
2. Loop mode.... (this is good for the sounds of aura spells, or others that last a long time and you want it to be heard as long as it persists). With a similar option, it would not be necessary to attach very long audios.
3. End the sound when the template is removed.

I don't know if this is possible, but well.... is a suggestion.

**Comment by otigon** [comment]
Something like this may be possible with the new Sequencer dependency as Wasp provided some good options for sounds with it. I'll take a look when I get to the Audio revamp

**Comment by otigon** [comment]
Tracking sound issues in #165
