### ISSUE TITLE
'Could not find " " in database' error

### ISSUE THREAD

**Issue by gravagehulk** [otigon/automated-jb2a-animations#160]
I have been using Automated Animations for a while now in conjunction with JB2A. Recently, they were updated to use sequencer by default. Since then, I've been getting a 'Could not find " " in database' error on a regular basis. This happened when a player used a javelin, but it also happened when a skeleton from the monster manual fired an arrow. These are attacks that previously worked with no issue.

I'm on the latest 0.8.8 build of Foundry, 1.4.1 DnD5e, and the most recent versions of all three modules.

![image](https://user-images.githubusercontent.com/69117052/127652516-393f67e4-e735-404a-8f20-9d75718209e2.png)

**Comment by otigon** [comment]
Thanks for the report. Are you using the Free or Patreon JB2A package?

**Comment by gravagehulk** [comment]
> Thanks for the report. Are you using the Free or Patreon JB2A package?

I am, yes. Sorry. I should have mentioned that.

**Comment by otigon** [comment]
Sorry, which one?

**Comment by gravagehulk** [comment]
> Sorry, which one?

Haha. Sorry. I am using the **free** version. Communication is hard.

**Comment by otigon** [comment]
Haha, no problem. I'll have to fix the automatic recognition on a few of those to remove those errors for you. I'll look at fixing that this weekend

**Comment by gravagehulk** [comment]
> Haha, no problem. I'll have to fix the automatic recognition on a few of those to remove those errors for you. I'll look at fixing that this weekend

Thank you, sir!

**Comment by otigon** [comment]
These errors should be fixed as of 0.5.08
