### ISSUE TITLE
[BUG] Teleport not working in PF1e

### ISSUE THREAD

**Issue by RobTheDM** [otigon/automated-jb2a-animations#161]
Trying to get the teleport function to work in my PF1e game and it seems to not work. I swear I remember it working fine last time I tried, but that was back when it first was added. I'm getting this error in the console. 
![Teleport](https://user-images.githubusercontent.com/66711614/127756119-c7759ae5-54fe-4537-840b-9dae42e2a987.JPG)

**Comment by otigon** [comment]
I think I see where it broke. I'll add this fix in the next release either tonight or tomorrow morning

**Comment by otigon** [comment]
Teleportation should work again as of 0.5.10
