### ISSUE TITLE
Sound playing on non hit weapon attack

### ISSUE THREAD

**Issue by Carlosjrlu** [otigon/automated-jb2a-animations#164]
There is a setting to check whether or not an attack hits through Midi-QoL and it works perfectly for the animation, but if I add a sound, the sound plays even on non hit weapon attacks. The animation doesn't show but the sound does.

**Comment by otigon** [comment]
Sounds are not tied to animations currently. It is on my list to update the Audio options in AA but will be a little further down the line

**Comment by otigon** [comment]
Tracking Sounds issues/upgrades in #165
