### ISSUE TITLE
System Additions

### ISSUE THREAD

**Issue by otigon** [otigon/automated-jb2a-animations#166]
If a system below is listed as not compatible, that means I cannot get the required data from the Chat Message or System Hooks. You can put a Feature Request in to those systems to ask for adding the Item or Item ID into the createChatMessage hook, or for providing System specific hooks for when Attack/Damage rolls are made

Check the following systems for adding AA support:

1. ~~OSE (U-Man) - no data provided that can get to the Item when used~~
2. AGE System https://github.com/vkdolea/age-system
3. UESRPG d100 https://gitlab.com/DogBoneZone/uesrpg-3e/
4. Dungeon World
5. Simple World Build
6. The Dark Eye
7. ~~WWII: Operation Whitebox - can't get anything to work in the system~~
8. ~~Sandbox - no idea how to do anything in this system~~
9. ~~Lancer - no idea how to get this system to do anything~~
10. Old Dragon
11. Tagmar
12. Shadowrun 5e

**Comment by Quoros** [comment]
Any plans to add the LANCER system now that it finally hit 1.0?

**Comment by trodrigues1505** [comment]
Otigon, I did the tests in systems Tagmar and Old Dragon but in both it didn't work, even using customizations when clicking on the sheet, no animation is performed.

**Comment by otigon** [comment]
Right, I have to add specific support for different systems into Automated Animations. No system works out of the box because each one is different in how I have to grab the data.

**Comment by GenX187** [comment]
Just for information. I opend an enhancement request at the DSA 5 (TDE 5) Gamesystem for supporting this module. 
https://github.com/Plushtoast/dsa5-foundryVTT/issues/772
DSA 5 is one of the populared RPG-systems in Germany an official supported by the puplisher (Ulisses) so it would realy be great when this module will be supported in the future.

**Comment by Spader1976** [comment]
Can you add support for Earthdawn system?

**Comment by otigon** [comment]
I've updated the Readme on the main page to note that I'm no longer adding support for anymore systems. I will add a section on the Wiki page to detail how to add support via a pull request. Sorry for the inconvenience.
