### ISSUE TITLE
Rage item causes error in the D&D5E handler

### ISSUE THREAD

**Issue by Haxxer** [otigon/automated-jb2a-animations#167]
**Description:**
Using item causes an error, in conjunction with Midi-QOL.

**Error:**
```
dnd5-handler.js:230 Uncaught (in promise) TypeError: Cannot read property 'hasAttack' of undefined
    at Dnd5Handler.get hasAttack [as hasAttack] (dnd5-handler.js:230)
    at specialCaseAnimations (autoAnimations.js:466)
    at autoAnimations.js:228
    at Function._call (eval at <anonymous> (listeners.js:56), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at ClientDatabaseBackend.callback (foundry.js:8681)
    at foundry.js:8620
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateDocuments (foundry.js:8620)
    at ClientDatabaseBackend._createDocuments (foundry.js:8516)
```

**Files**
Included the exported item below:
[fvtt-Item-rage.zip](https://github.com/otigon/automated-jb2a-animations/files/6927337/fvtt-Item-rage.zip)

Midi-QOL settings here:
[fvtt-midi-qol-settings.zip](https://github.com/otigon/automated-jb2a-animations/files/6927352/fvtt-midi-qol-settings.zip)

**Comment by cogito808** [comment]
I am seeing similar errors for weapon attacks. It appears to be Midi-QOL setting because it is not happening in my test world with different settings.
`Uncaught (in promise) TypeError: this._item is undefined
    get hasAttack dnd5-handler.js:230
    specialCaseAnimations autoAnimations.js:466
    <anonymous> autoAnimations.js:228
    _call lib-wrapper.js line 1 > eval:4
    callAll foundry.js:153
    callback foundry.js:8681
    documents foundry.js:8620
    _handleCreateDocuments foundry.js:8620
    _createDocuments foundry.js:8516
    create backend.mjs:96
    createDocuments document.mjs:332
    create document.mjs:431
    createReverseDamageCard GMAction.js:155
    _executeLocal socketlib.js:192
    executeAsGM socketlib.js:90
    applyTokenDamageMany utils.js:306
    processDamageRoll utils.js:361
    _next workflow.js:586
    next workflow.js:338
    _next workflow.js:583
    next workflow.js:338
    _next workflow.js:555
    next workflow.js:338
    _next workflow.js:550
    next workflow.js:338
    doDamageRoll itemhandling.js:255
    call_wrapper libWrapper-wrapper.js:574
    rollDamage#0 libWrapper-wrapper.js:162
    _next workflow.js:492
    next workflow.js:338
    _next workflow.js:470
    next workflow.js:338
    doAttackRoll itemhandling.js:107
    call_wrapper libWrapper-wrapper.js:574
    rollAttack#0 libWrapper-wrapper.js:162
    _next workflow.js:437
    next workflow.js:338
    _next workflow.js:400
    next workflow.js:338
    _next workflow.js:397
    next workflow.js:338
    _next workflow.js:361
    next workflow.js:338
    processItemCardCreation chatMesssageHandling.js:517
    initHooks Hooks.js:110
    _call lib-wrapper.js line 1 > eval:4
    callAll foundry.js:153
    callback foundry.js:8681
    documents foundry.js:8620
    _handleCreateDocuments foundry.js:8620
    _createDocuments foundry.js:8516
`

Midi-QOL settings here:
[fvtt-midi-qol-settings.zip](https://github.com/otigon/automated-jb2a-animations/files/6933000/fvtt-midi-qol-settings.zip)

**Comment by otigon** [comment]
I have a fix in for the next release

**Comment by otigon** [comment]
This error should no longer show up as of 0.5..15
