### ISSUE TITLE
Edge case module conflicts with midi-qol, betterRolls5e, diceSoNice

### ISSUE THREAD

**Issue by Ro4m3r** [otigon/automated-jb2a-animations#170]
There are a few remaining edge cases for conflicts with popular modules. I'm not sure if it's worth fixing these as some of them are more minor, but these are still issues I ran into.

When using BetterRolls5e in combination with DiceSoNice, the animation is added to the template *after* the one that was created when casting the spell. I assume this was partly the reason for issue #168. This issue does not occur when using BetterRolls5e **without** DiceSoNice.

https://user-images.githubusercontent.com/21060784/128351316-15add0e3-718e-48e5-8662-ade473944b04.mp4

When using Midi-QOL with the workflow option "Auto Target on Template Draw" set to anything other than "None", the animation will be played twice. Once for the template created by the spell, and again on the next template, potentially causing multiple spell animations to overlap.

https://user-images.githubusercontent.com/21060784/128352287-e92d45f7-f06c-4237-8648-2471435104dc.mp4

**Comment by otigon** [comment]
Thanks for the detailed report, I'll do some testing and replicate to see about finding a fix. Should be simple as adding in a few checks here an there. Is this using the latest 0.5.15 or 0.5.16 version of Automated Animation? I Those releases restructured alot of the animation routing

**Comment by Ro4m3r** [comment]
All of this was using 0.5.16 of Automated Animations. 

If you publish a fix I'll test all of them in combination (midi-qol for auto-targeting, BR5e for rolls, dice so nice because it looks cool), as that is my preferred module combination, although my setup seems very specific.

Thanks for the quick responses on the issues and great work on the module! Been playing around with it and just really enjoy making animations for spells and attacks 👍

**Comment by otigon** [comment]
Based on my testing, the common culprit with this type of issue is Dice so Nice. Aside from double animations and such (which "should" be cleared up now, let me know if not), the problem occurs when the template is placed before the Dice so Nice roll has finished. This is in conjunction with Midi/Better rolls not displaying the chat card until the dice have finished rolling.

If the template is placed after the dice have rolled (i.e. the chat card appears), everything seems to work normally. There isn't much I can do for that aspect with the way templates are handled in A-A currently. A-A needs the chat card to be present to be able to know what animation to play. However, I do plan on attempting to rework the way template effects are played so maybe I'll be able to figure out a workaround
