### ISSUE TITLE
[BUG] Target & self effects won't work for spells with damages & BetterRolls

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#171]
Hello,

Here is an item: https://we.tl/t-gob3NVJSe0
This item has a "target effect". This will work correctly if the item doesn't have damage declared on it. But won't with the damage formula.

**Comment by otigon** [comment]
Can you attempt this without Better Rolls active?

**Comment by DarKDinDoN** [comment]
@otigon without BetterRolls, it works as soon as I hit the "damage" button in the chat message.

**Comment by DarKDinDoN** [comment]
@otigon It's working perfectly fine on melee weapons. The item has a damage formula and the animation is fired.

**Comment by otigon** [comment]
Assuming you are on 0.5.15 or above, this looks like a problem with my rework on the animation routers. I'll be pushing a fix tonight

**Comment by otigon** [comment]
Should be fixed as of 0.5.17

**Comment by DarKDinDoN** [comment]
@otigon Hey, updated to the latest version, same issue, same item.
Tried to recreate and the animation, same issue.
As long as the item has a damage formula declared on itself, it won't work with self or target effects. (BetterRolls)

**Comment by otigon** [comment]
I guess I fixed a different issue lol. I'll open this back up until I can take another look

**Comment by DarKDinDoN** [comment]
@otigon Hey, noticed this bug affects all animations except weapon animations.
On a side note: I don't know why, but I lost all my preconfigured self effects, except for the custom ones. Had to do them all over again :/

**Comment by otigon** [comment]
I can't promise any results for interactions with Better Rolls, but I'll take a look. I have not been able to add specific support for BR due to how they wrangle the chat message workflow

**Comment by DarKDinDoN** [comment]
@otigon understandable. If it can help, it was working fine before the newest release (before the new animation router)

**Comment by otigon** [comment]
that does help some, I'll compare the differences

**Comment by otigon** [comment]
@DarKDinDoN I'm going to close this issue as this is specifically a problem with Better Rolls. I can help troubleshoot more if you want to reach out to me on discord
