### ISSUE TITLE
Sound not playing with templates

### ISSUE THREAD

**Issue by RavenknightDM** [otigon/automated-jb2a-animations#175]
Hi, thanks for the mod!
I've noticed that I can't get audio anymore when I'm placing a template. Pretty syre it used to work just fine just a couple of releases ago.

**Comment by otigon** [comment]
thanks for logging the issue, I forgot about this one. I'll push a fix on the next release

**Comment by RavenknightDM** [comment]
Thanks Otigon. Your mod brings great joy to my table. :)

**Comment by otigon** [comment]
I've added the sound back to the Templates, and it should actually play when the template is put on the canvas now, better timing with the Animation. Version 0.5.22
