### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by gravagehulk** [otigon/automated-jb2a-animations#176]
Not an issue, per se, but I was working on my SW5e game and just noticed this. I can't find anything in the changelog for it. Can you tell me what it is?

<img width="633" alt="Screen Shot 2021-08-09 at 4 37 22 PM" src="https://user-images.githubusercontent.com/69117052/128777935-660c5538-1478-462e-ba6f-88f1e9194901.png">

**Comment by otigon** [comment]
I probably didn't document that well enough. That is intended to show that the TokenFX Tab plays before and after the primary animation set on the Animation Tab.

So you would have:
- Animation on Source Token
- Primary Animation (like laser shots)
- Animation on Target Token

I'll leave this open to remind me to update the Documentation

**Comment by gravagehulk** [comment]
Ah, thank you. I played around with it a bit and that makes sense. Probably could have figured it out myself, I was just surprised to see it. Cheers!

**Comment by otigon** [comment]
I actually want to figure out some CSS so the Source and Target boxes highlight green if they are activated

**Comment by otigon** [comment]
I was able to implement some dynamic CSS so the Source and Target Animation boxes will turn green when activated. I'm going to close this ticket for now, but I will be doing a complete rework of the Item Menus in the next month or two so I'll be making it more clear from a UI perspective
