### ISSUE TITLE
Possibility of players disabling Automated Animations?

### ISSUE THREAD

**Issue by Artetsu** [otigon/automated-jb2a-animations#179]
Unfortunately, some of my players have low-end machines (but not all of them), and I was wondering if it would be possible for some of them to have the option of not having the animation run from their end of the VTT. As when the animations are played, their foundry ends up crashing (their canvas turns black).

Just as we have global options and user options for many modules, maybe implementing something among those lines could make it work?

**Comment by otigon** [comment]
I can implement an option for individual clients not to have any animations "start" from their end, however, I now piggyback off of Sequencer and that module handles all of the animations. They would have to figure something out on their end as far as an option to not play animations on particular clients

**Comment by Artetsu** [comment]
Should I post something on Sequencer and cross-reference this?

**Comment by otigon** [comment]
That would be good to post there as well yes

**Comment by otigon** [comment]
I actually stumbled across a way to disable the animations from reaching an individual client. I'll do some testing this week and see if I can implement it

**Comment by otigon** [comment]
This feature is now live as of 0.5.28 as a client level setting so individual users can disable animationa
