### ISSUE TITLE
TriggerHappy Traps and Animiation Error

### ISSUE THREAD

**Issue by cogito808** [otigon/automated-jb2a-animations#180]
I am using TriggerHappy traps, specifically the design of Mr. Weaver (https://www.youtube.com/watch?v=Gd3MQPgIoKs) and I am getting some console errors seemingly pointing at AutoAnimations when they are activated. The attacks on the TrapEffects actor has animations disabled. Any help is appreciated.

    traffic-cop.js:39 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
        at trafficCop (traffic-cop.js:39)
        at setUpMidiNoA (autoAnimations.js:435)
        at autoAnimations.js:245
        at Function._call (eval at <anonymous> (listeners.js:56), <anonymous>:4:14)
        at Function.callAll (foundry.js:153)
        at TrapWorkflow._next (workflow.js:692)
        at TrapWorkflow._next (workflow.js:1959)
        at TrapWorkflow.next (workflow.js:340)
        at TrapWorkflow._next (workflow.js:659)
        at async TrapWorkflow.next (workflow.js:340)

**Comment by otigon** [comment]
I think I see where the error is occurring. I'll add in a fix today

**Comment by otigon** [comment]
Just for clarification, you said the items on the actor have their animations disabled? At the point where this error occurs, it has already passed that check and is assuming they are not disabled.

**Comment by cogito808** [comment]
Yes, but the attacks are on the TrapEffects actor. It might be looking at the Trap actor maybe and not the TrapEffects actor? It might be the macro itself as it doesn't seem to trip the token to visible either (or not related at all?).

**Comment by otigon** [comment]
"Should" be fixed as of 0.5.25, though this isn't something I could replicate without macros and such. Please let me know if this persists and we can troubleshoot further

**Comment by cogito808** [comment]
It is, thanks!
