### ISSUE TITLE
Template animations and concentration

### ISSUE THREAD

**Issue by jakekausler** [otigon/automated-jb2a-animations#183]
I create a spell, for example Fog Cloud, with a radius template (sphere). Then I create an Automated Animation with a circle template fog cloud effect, remove template after placement and place as tile. If I cast the spell then stop concentrating, I have to refresh for it to actually go away.

**Comment by jakekausler** [comment]
Actually both. The tile remains (though if there is nothing with concentration, then it should). Then, I can't click on the token on the token layer (wasn't testing this, just expected it to be gone), and it is gone when I refresh.

**Comment by otigon** [comment]
This should be fixed as of 0.5.25

**Comment by otigon** [comment]
Sorry, closed the wrong issue, this is still open

**Comment by otigon** [comment]
So the tile will remain until you manually delete it, there is nothing that links that to concentration. The Tile "should" persist across refreshes, though I haven't tested that specific circumstance and can check it out tonight

**Comment by otigon** [comment]
My only suggestion for this, in terms of not being able to delete a token, is to use the Find the Culprit module
