### ISSUE TITLE
Melee Animations no longer play

### ISSUE THREAD

**Issue by Lobosolo85** [otigon/automated-jb2a-animations#185]
I am not sure what changed in the last couple of revs, but my melee animation no longer play.  It looks like ranged and ranged spells are still working, but melee doesn't play even if I reset the animation and try different ones.  I tried disabling the "Melee to Ranged Switch".  Claws and bites no longer work either.  I am using Midi-Qol, Sequencer, etc.  I didn't make any recent module changes.  Any idea what this might be caused by?

Lobo

**Comment by otigon** [comment]
Are you getting any errors in the console?

**Comment by Lobosolo85** [comment]
Looks like I am....
![image](https://user-images.githubusercontent.com/87660869/129233324-1227af0c-adc8-4cc0-bb66-dce4cf059d5b.png)

**Comment by otigon** [comment]
What version of Foundry, Sequencer and Automated Animations are you on?

**Comment by Lobosolo85** [comment]
UPDATE - Looks like Claw and Bite DO Work....only the melee weapon animations are not working properly.  By unchecking "Disable Melee to Range Switch" the thrown weapon animations are now working.  Dagger does not play for melee but it does for thrown.  Ranged weapon and ranged spell animations still work fine.

**Comment by Lobosolo85** [comment]
Foundry - 0.8.8
AA - 0.5.27
Sequencer - 0.5.9

**Comment by otigon** [comment]
you will need to upgrade to Sequencer 0.6, this should resolve your issues

**Comment by Lobosolo85** [comment]
AHH.  Weird, I think my "update all modules" timed out without updating Sequencer....I thought I was up to the latest.  YUP!  It fixed it.   So sorry for the false alarm

Thank you so much, Otigon!

**Comment by otigon** [comment]
no problem! Glad it is fixed
