### ISSUE TITLE
Weapons Animations

### ISSUE THREAD

**Issue by Gvicross** [otigon/automated-jb2a-animations#186]
Weapon animations are not working, I target the target token, trigger for example "Rapier", the attack is rolled, but none of the animation. I already made sure the animation was recognized and everything.

**Comment by yahavatar** [comment]
Same here. Also, explosions are not working. We get errors:

![image](https://user-images.githubusercontent.com/780527/129299841-b37a04e4-7da1-4f65-bca5-6da9979e2876.png)

Even though a sound file has been chosen:

![image](https://user-images.githubusercontent.com/780527/129299862-9f53b19e-4a9c-43b8-aeb7-b4d6d0fc8ac3.png)

**Comment by otigon** [comment]
@Gvicross any errors showing up?

@yahavatar You need to update Sequencer

**Comment by yahavatar** [comment]
Sequencer says it is up-to-date:

![image](https://user-images.githubusercontent.com/780527/129300166-f01a676f-ec84-4795-9e04-8a26f4665bc8.png)

**Comment by Gvicross** [comment]
No one wrong appears, but in the f12, appears some things. I can show you, wait pls...

**Comment by Gvicross** [comment]
Well, I update Sequencer and the animations back to work... sorry e thanks for the attention.

**Comment by otigon** [comment]
@yahavatar I can't replicate this error. Try the following:
1. Disable the Explosion and Explosion Audio and see if error persists

Is this error only occurring on this item, or multiple items?

**Comment by yahavatar** [comment]
Error only happens when explosion is enabled for sure. Here's the console errors:

![image](https://user-images.githubusercontent.com/780527/129300641-ebe66148-8b1c-49cf-8106-8ef422b57c5f.png)

**Comment by yahavatar** [comment]
Explosion works. Explosion Audio is what throws the error.

**Comment by otigon** [comment]
Sequencer cannot find the Sound File. This could occur if you have spaces in the name, or for many other reasons. Try picking a different sound file

**Comment by yahavatar** [comment]
Won't work with this simple core sound:

![image](https://user-images.githubusercontent.com/780527/129300883-8bbd01ec-65b8-4a4b-8a63-b89153a59c6b.png)

**Comment by otigon** [comment]
Hmm, sounds work on my end. I'll do some testing and see if I can replicate the error

**Comment by yahavatar** [comment]
Here's a full screen capture of the settings I am using:

![image](https://user-images.githubusercontent.com/780527/129301063-0d4eab64-5c4d-412d-bb30-374a328202d7.png)

**Comment by yahavatar** [comment]
Tried closing everything down, server and client. Deleted and re-added tokens. Still same result. Is happening with all tokens on every scene too.

**Comment by yahavatar** [comment]
Tried uninstalling and re-installing sequencer. Didn't help...

**Comment by otigon** [comment]
@yahavatar I was able to replicate and track down the error. I'll have a fix in the next release, probably later today

**Comment by yahavatar** [comment]
Otigon, thanks a bunch!

There are a few issues with Sequencer that remain, but I believe that it is all on their end. I think they are mangling the JB2A name strings on a few range weapons/distances. I'm seeing several different errors depending on where source token is standing in relation to target. I'll wait for your update before I do anything.

**Comment by otigon** [comment]
Those errors with range have to do with the JB2A module. Both of the JB2A releases in July added lots of new animation files for existing animations. They added 5 and 15ft for many of them. Sequencer is just taking my database and finding the correct file for the range.

Are you running the free or patreon package for JB2A?

**Comment by yahavatar** [comment]
I'm using the Patreon version of JB2A right now. Is the free version better? I'm not married to the Patreon version at all. I really never use the whole gamut of their colors.

**Comment by otigon** [comment]
Automated Animations takes precedence for the Patreon module, so it will always read those files over the Free version. If you have not updated the Patreon module in a while that could be the issue

**Comment by yahavatar** [comment]
I generally update ALL modules at once every evening and track the level of changes that get installed to see if there is any version changes look dangerously large. This seems to be working better than doing updates every week or month as I was doing originally. The gradual increases keep the game more stable. It's the large jumps that bite us from time to time.

Both AA and JB2A are fully updated as of last night. I did this first thing in my testing. The errors I saw with Ranged weapons were just using a Bow and moving back gradually from the target. Eventually, I see things like:

![image](https://user-images.githubusercontent.com/780527/129411881-6cf1203b-1d01-4d57-ba33-1206524719d9.png)

![image](https://user-images.githubusercontent.com/780527/129411902-ed2af964-6c4e-4434-89e6-0cfb0679f779.png)

And errors:
![image](https://user-images.githubusercontent.com/780527/129412108-7e438c80-ed09-491b-b925-b49187c1ec55.png)


Oddly, the ranged weapons seem to have no issue with explosions and play the sounds just fine.

**Comment by otigon** [comment]
bear in mind the Patreon JB2A package is a manual installation, unless you are on the Forge?

**Comment by yahavatar** [comment]
Otigon, that's the ticket! I reverted to the Free version and now the issues have evaporated. I'm not going to mess with the Patreon version anymore if they do not have an auto-updater. ugh...

**Comment by yahavatar** [comment]
Well... sort of OK now. Ranged weapons are working perfectly. Hand-held melee weapons are still throwing the two errors... Using the latest JB2A Free.

**Comment by otigon** [comment]
That would be because I haven't released the fix for that yet

**Comment by yahavatar** [comment]
Gotcha. Figured that was the case. Thanks for taking the time to even pay attention to my posts. I'm using AA right now and am eternally grateful for what it adds to our games! I've just been trying to give you as much info as I can to help you track down the issues. Take your time.

**Comment by otigon** [comment]
sound issue should be fixed as of 0.5.29
