### ISSUE TITLE
Request: Option for Play Animation on Damage Roll for Hits, but not Misses

### ISSUE THREAD

**Issue by GambetTV** [otigon/automated-jb2a-animations#187]
Right now (unless I'm missing something) there is a setting to play Animations on both hits and misses, and a separate setting for only playing animations on damage rolls. Unfortunately, no one will roll damage rolls on misses, so using that setting means never seeing missed attacks. It'd be great to have a setting that would let you play an animation upon rolling damage for attacks that hit, but will automatically play the miss animation if it misses, without needing to roll the damage dice.

Hopefully that makes sense! Thanks!

**Comment by otigon** [comment]
If you leave the "Play Animations on Damage" unchecked, it will default to playing animations on Attack rolls, and then damage if there is no attack roll for the item.

Midi already has too many options for me to keep up with, so I won't be adding more for that sorry
