### ISSUE TITLE
 don't you have a contributor guide in this repository?

### ISSUE THREAD

**Issue by narukaioh** [otigon/automated-jb2a-animations#188]
I would like to integrate with the forbidden lands system, but I don't know how to contribute with this module. How it works?
What are the steps to setup this project in my foundry?

**Comment by otigon** [comment]
I had not thought about a contributor guide, I will have to add that. In the meantime, you can take a look at any of the System Handler files. It is basically a copy/paste. The difference sometimes comes with how to grab the Item ID, Source Token and targets. Every system seems to be a little different.

Then it is a matter of adding the proper hooks (chat message or system specific) and routing them to the right place.

I'll look at adding some documentation to show some examples

**Comment by narukaioh** [comment]
> I had not thought about a contributor guide, I will have to add that. In the meantime, you can take a look at any of the System Handler files. It is basically a copy/paste. The difference sometimes comes with how to grab the Item/ItemID, Source Token and targets. Every system seems to be a little different.
> 
> Then it is a matter of adding the proper hooks (chat message or system specific) and routing them to the right place.
> 
> I'll look at adding some documentation to show some examples

Yes, I'm doing exactly what you said and testing it here with my module that I downloaded from the foundry installer.

Thank you so much for the reply!

**Comment by otigon** [comment]
The biggest obstacle sometimes is parsing out when an Attack is made versus a Damage roll. Some systems auto automatically roll them together which makes it easy.

If there are system specific flags/hooks for those events it is smooth. Otherwise if you have to run of the createChatMessage hook, you need to set in checks so it doesn't play something every time a chat message shows up
