### ISSUE TITLE
[BUG] Automatic recognition of attacks doesn't work with Spanish language using English items

### ISSUE THREAD

**Issue by Musrha** [otigon/automated-jb2a-animations#19]
Since the Spanish localization update, automatic recognition doesn't work while Spanish is the default language and the items/spells are in English (like the SRD has). When you switch back to English language they work well.

Is there any way to select the language of the items should the module search for? Thanks in advance!

**Comment by otigon** [comment]
Hey @Musrha thanks for letting me know about this. I'll add back in the default English check as a back-up to the localization for the auto-recognition. The Animate Tab will still be localized, but if the base items are in English this should work as a good back-up.

I'll try to get this out by tonight, but might be tomorrow

**Comment by Musrha** [comment]
Thank you very much!! Don't need to hurry, just glad that it's being fixed! :)

**Comment by otigon** [comment]
@Musrha this issue should be fixed as of 0.2.51
