### ISSUE TITLE
[System request] Star Wars FFG

### ISSUE THREAD

**Issue by Ikabodo** [otigon/automated-jb2a-animations#190]
It would be super nice if AA could support FFG Star wars!

It's currently possible to open the AA menus on weapons, but they don't trigger.

I think laser sword and laser gun would cover almost all weapons in that system.

**Comment by otigon** [comment]
I'll take a look. I first need to rework the way I handle different systems to make them easier to manage

**Comment by otigon** [comment]
I believe someone on the JB2A discord was able to put in a Pull Request on the Star Wars FFG system to get the correct data passed into the chat messages. Once they are able to merge that SWFFG support can be imlemented

**Comment by otigon** [comment]
I've updated the Readme on the main page to note that I'm no longer adding support for anymore systems. I will add a section on the Wiki page to detail how to add support via a pull request. Sorry for the inconvenience.
