### ISSUE TITLE
Animation on damage application

### ISSUE THREAD

**Issue by Carlosjrlu** [otigon/automated-jb2a-animations#191]
Is it possible to set the animation to trigger only when I apply the damage from the damage card of MidiQoL?

This one
![image](https://user-images.githubusercontent.com/20954701/129464934-47bdf870-8a8e-468c-bf5f-4bc5946d5575.png)

**Comment by otigon** [comment]
Not currently. Not completely in the plans for the future but I'll add it to my list to take a look at
