### ISSUE TITLE
SW5e animations broken by recent update

### ISSUE THREAD

**Issue by gravagehulk** [otigon/automated-jb2a-animations#193]
The animations were working until recently. Now there is no laser blast when a blaster is fired (set manually). If I select "laser blast), I can't select a color. On creatures where it was already set (laser blast + red), the "laser blast" is blanked out. Either way, there is no animation.

<img width="627" alt="Screen Shot 2021-08-15 at 9 26 33 AM" src="https://user-images.githubusercontent.com/69117052/129481864-dcdba25a-d3c0-45fe-be00-4bcd91f97a42.png">

**Comment by otigon** [comment]
Thanks for reporting this. I'll get a fixed pushed for this either tonight or tomorrow

**Comment by gravagehulk** [comment]
you are the man! Thank you.

**Comment by otigon** [comment]
@gravagehulk can you tell me what version of Automated Animations you are on, and if you are using any localization?

**Comment by gravagehulk** [comment]
I'm on version 0.5.28. Sorry, I'm not sure what you mean by localization. It does show the "localization" tag on the modules screen.

**Comment by otigon** [comment]
I'm testing on my local SW5e and I can't seem to replicate the issue. Can you check for any errors in the console (F12) when this goes wrong?
![SW5e Lasershot](https://user-images.githubusercontent.com/73318661/129636608-31d8de97-7e68-4c8b-bc35-88c822c828a2.JPG)

**Comment by gravagehulk** [comment]
I'm not getting any console errors when I attempt to change the animation. I don't see any other errors either. I just tried disabling about half of my modules and none of that worked. Do you have the newest DnD5e system update?

**Comment by otigon** [comment]
I'll check, but that would t have anything to do with the A-A UI. Can you export the item and send it to me?

**Comment by gravagehulk** [comment]
I can't send .json files through here. Here's a zip. The blaster rifle is the one I customized. I'm working on a project for the SW5e developers to fix all of the weapon attacks to work correctly (templates, saves, etc). So none of my monsters are stock. But they were all working until recently. And I'm having this animation issue with everything now.

[fvtt-Actor-trooper.json.zip](https://github.com/otigon/automated-jb2a-animations/files/6995759/fvtt-Actor-trooper.json.zip)

**Comment by otigon** [comment]
gotcha, I'm running version 1.3.5.R1-A7 on SW5e

**Comment by gravagehulk** [comment]
yeah, that's the version I'm running. I've been systematically going through and disabling modules one-by-one, but so far none of them are causing this.

**Comment by otigon** [comment]
and for the animation side, you have Sequencer installed and active?

**Comment by gravagehulk** [comment]
I do, yes.

**Comment by otigon** [comment]
When I imported that actor, the Blaster Rifle settings looked like this. 
![SW5e Lasershot](https://user-images.githubusercontent.com/73318661/129638204-1ea58c1d-d27b-44d6-8a04-fdae301fa90d.JPG)

I was able to select the Laser Blast animation and the colors populated

**Comment by otigon** [comment]
If you have time, you can reach out on Discord and maybe I can join your world to try and troubleshoot this?

**Comment by gravagehulk** [comment]
Yeah, that's right. It was working fine up until recently and then it just disappeared. I assumed something broke in an update. I will reach out.

**Comment by otigon** [comment]
thanks, I'm Otigon#2010

**Comment by gravagehulk** [comment]
Not sure if I'm an idiot or what. I can't seem to find you on Discord. I have found and added people before. But nothing comes up when I search for your name.

**Comment by otigon** [comment]
I forgot to take my name of Do-Not-Disturb, that might cause that. You can also catch me on the JB2A discord at https://discord.gg/mED4HepT

**Comment by otigon** [comment]
Fixed as of 0.5.30
