### ISSUE TITLE
Documentation enhancement: supported items/spells

### ISSUE THREAD

**Issue by SR5060** [otigon/automated-jb2a-animations#196]
I apologize if this is present, I tried to look thoroughly before posting, but it would be great to have an inventory list in the readme of spells and attacks that are automatically supported. Would help tremendously with ongoing update maintenance. Right now I go through each item manually to see if it is set-up or not after a new jb2a release.

**Comment by otigon** [comment]
There is this that may be a little outdated: https://github.com/otigon/automated-jb2a-animations/blob/main/Animations/Available%20Animations.md

For the 0.6 series I will be implementing the Automatic Recognition as GM level settings that you will be able to customize from the Automated Animations settings.

**Comment by otigon** [comment]
Going to close this issue out. The 0.6.0 release (this weekend), will be reworking all of the automatic recognition with a Global user defined interface for which items will be automatically recognized
