### ISSUE TITLE
[BUG] Target effect not working anymore

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#199]
Hello,

FVTT 0.8.9
AA 0.5.42
5e 1.4.2

Get this error:
![image](https://user-images.githubusercontent.com/1687854/129985219-3baabf73-e2e8-4f66-b2c8-74115d1c0393.png)

With this item: https://we.tl/t-CXq6X0Wkrc

**Comment by otigon** [comment]
you'll have to send that to me on Discord, I don't have an account with that site

**Comment by DarKDinDoN** [comment]
@otigon You don't need one. Skip whatever sign-up you see.
I didn't use an account myself to upload the item.

**Comment by otigon** [comment]
Sorry, I'm not downloading something from a website that I've never used

**Comment by otigon** [comment]
Otigon#2010 on discord

**Comment by otigon** [comment]
Issue fixed as of 0.5.44
