### ISSUE TITLE
Configurations typed into an item's "Source" have no effect

### ISSUE THREAD

**Issue by danthemanb** [otigon/automated-jb2a-animations#2]
Typing "sword" into the source of a "mace"-named item will still use the "mace" animation instead of switching to sword.

Adding a color to the source disables the animation all-together.  (This may be because I'm not currently using the patron version)

I have Token Magic FX, Midi QOL, FXMaster, JB2A, and The Furnace all installed.

Sorry if I'm missing something obvious!

**Comment by danthemanb** [comment]
More details:  The targeted tokens still receive "bloody" or "colored" effects when hit, the animation is simply missing.

This occurs when switching to a ranged attack instead of melee as well for weapons such as the spear.

**Comment by otigon** [comment]
> More details: The targeted tokens still receive "bloody" or "colored" effects when hit, the animation is simply missing.
> 
> This occurs when switching to a ranged attack instead of melee as well for weapons such as the spear.

It's not currently possible to switch animations that are automatically recognized. I've created a test case with Cure Wounds and Healing Word, where you can switch the animations on those, but I haven't implemented it across the board yet. It is on the list!.

Also, if you are not using the Patreon version of the module, only input colors in the "Source" field if the free version has that available. For instance, the Generic Healing animation used for Healing Word has all colors available to Patreon and Free modules. In your case you can use the Source field to switch that color. However, if you put a color in the Source Field that isn't available in the Free version, it will try to read a File that is not there, and no animation will play.

I'm going to close this issue tomorrow, but please reach out on the JB2A discord if anything is unclear and I can show you in better detail.

**Comment by danthemanb** [comment]
Ah, I got the patron version and most cases are working.  I was either trying to access locked animations or not allowed switches (greataxe to sword).  Thanks for the information!

**Comment by otigon** [comment]
No problem. I'm working one Core support now, but switching animations will be worked on soon
