### ISSUE TITLE
Animation Not Playing

### ISSUE THREAD

**Issue by sampsonyee** [otigon/automated-jb2a-animations#200]
I'm new to Foundry VTT and I'm not sure if I'm setting everything up correctly.  I am drag-n-dropping weapons onto targets, and clicking on the roll buttons.  All the hits and damages are registering, but the animations aren't firing.  I went into the Web Developer Tools and see this error every time I attack:

```
build-filepath.js:28 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at buildFile (build-filepath.js:28)
    at meleeAnimation (meleeAnimation.js:55)
```

I'm currently using v0.5.46 with Midi QOL 0.8.45 in my environment.  Any help would be appreciated!

**Comment by otigon** [comment]
I'm not certain what you mean by dragging/dropping weapons on to the target? Is this every weapon throwing that error or just a few select ones?

**Comment by sampsonyee** [comment]
I'm using Midi QOL's Drag and Drop Targeting, dragging from Player 1's Inventory Longsword to Monster 1's avatar for targeting and attack/damage rolls.

Looks like only the Longsword.  Actually, I just tested the default Longsword from the dnd5e Starter Heroes' Krusk (Half-Orc Paladin) character, it shows the error.  However, when I replaced the Longsword with one from the dnd5e Compendium's Items, it did not show the error.  So is this some sort of missing data that caused the error?

**Comment by otigon** [comment]
I didn't know that drag/drop was a thing. Just tested on my server and everything seems to be working fine. Mind you, this will only work for so many things.

As for the longsword, it might have just had an error on it if you maybe had attempted a custom configuration on it?

**Comment by sampsonyee** [comment]
I honestly can't remember if I played around with it or not trying to learn/fix things.

I appreciate the quick response!  Also, great work with the module!
