### ISSUE TITLE
[System request] Sandbox 

### ISSUE THREAD

**Issue by Kalltern** [otigon/automated-jb2a-animations#204]
Hello!

This module is neat!

It would be really nice if it could work with cItems upon activation in sandbox ^.^ 
Provided that this is possible ofcourse :)

**Comment by otigon** [comment]
I'll take a look. I first need to rework the way I handle different systems to make them easier to manage

**Comment by otigon** [comment]
sorry, no idea how to use this system. You'll need to find someone who knows the system to issue a Pull Request to add support
