### ISSUE TITLE
[BUG] Place as tile not working

### ISSUE THREAD

**Issue by kuchrk24** [otigon/automated-jb2a-animations#205]
FoundryVTT 0.8.9
Automated Animations 0.5.52
socketlib 1.0.9
DnD 5e 1.4.2

I have a custom animation I am trying to set up to place a tile. Here is a screen shot of the configuration.
![image](https://user-images.githubusercontent.com/74018852/131176598-a923620d-b6df-4d4e-9110-cdcc254cb5c8.png)

When I place the measured template, no tile is being placed. No console errors.

**Comment by kuchrk24** [comment]
Neither of these configurations work either. Seems templates are just broken.  No console errors related to this module that I see.

![image](https://user-images.githubusercontent.com/74018852/131198064-2556ff36-f67b-4106-abce-c1dc77f386bc.png)
![image](https://user-images.githubusercontent.com/74018852/131198079-36c6ff32-acf7-4786-9ba8-b6997a677bf8.png)

**Comment by otigon** [comment]
@kuchrk24 In my test world this works as intended.

1. Have you tested with only A-A, Sequencer and Socketlib active?
2. Are you using Better Rolls? That usually breaks things
3. Do you have something checked on the TokenFX Tab and not filled out?
4. Are you on a scene with a grid?
5. Do any other animations act abnormally?

**Comment by kuchrk24** [comment]
Shoot... it does work with just the three modules. I guess I'll turn modules back on a few at a time and see if I can figure out which one is the trouble maker. Tried turning off just Better Rolls before that and it didn't have an effect.

**Comment by otigon** [comment]
The Find the Culprit module is great for these troubleshooting issues. Let's you cycle through active modules and reenables all of them when finished

**Comment by kuchrk24** [comment]
That's good to know. I ended up finding it manually. It's Midi QOL. The only reason I have that one installed is because its a dependency for the Midi SRD..... using it for the compendium of spells with active effects.

**Comment by otigon** [comment]
Can you export your midi settings and send to me on Discord? I use Midi all the time and don't see that issue.

**Comment by kuchrk24** [comment]
I actually just basically nuked the settings to see if i could find one that was causing a problem. So far no good. Give me a moment and I'll export

**Comment by kuchrk24** [comment]
Sent

**Comment by otigon** [comment]
Both issues should be resolved on the latest release
