### ISSUE TITLE
Feature Request: Different sounds for different distance 

### ISSUE THREAD

**Issue by Kaharos94** [otigon/automated-jb2a-animations#208]
Basically it's not much. It'd be nice if you could  different sounds for the different distances. A handaxe or a dagger can be thrown or it can be close range, so it'd be nice to have them playing different sounds.

**Comment by otigon** [comment]
I'll get this looked at when I start the revamp of the audio in A-A

**Comment by franckflo** [comment]
Looking forward to it :). An extension of this would be to allow wildcards in the name  (just like FVTT does for token images)  so that an ambitious GM could have more than one sound for a specific weapon.

**Comment by otigon** [comment]
Active in version 1.0, closing issue
