### ISSUE TITLE
[Bug] JS exception for Bless automation

### ISSUE THREAD

**Issue by tools81** [otigon/automated-jb2a-animations#210]
![image](https://user-images.githubusercontent.com/42152017/131949131-9d51f7a4-f724-4ec6-b709-16bb25449a70.png)

Reproduce: Simply select Bless as a Custom Sequence animation and attempt to cast it.

**Comment by tools81** [comment]
Looking into this further, I think this is due to the spell's setup in the midi-srd module.

**Comment by otigon** [comment]
This one slipped my mind, I'll get a fixed pushed out today. In the meantime you can go to the "TokenFX" tab and disable the Target Animation

**Comment by otigon** [comment]
Fixed as of 0.6.14
