### ISSUE TITLE
[System request] Old School Essentials

### ISSUE THREAD

**Issue by WallaceMcGregor** [otigon/automated-jb2a-animations#211]
Hi. It would be great if this wonderful module would be compatible with OSE 🥰

**Comment by otigon** [comment]
I'll take a look. I first need to rework the way I handle different systems to make them easier to manage

**Comment by WallaceMcGregor** [comment]
Thanks 👌🏻

**Comment by otigon** [comment]
I took a look at OSE, and unfortunately it does not provide the information required for Automated Animations to work. At a minimum, when you use an Item it needs to get access to the Item-ID or the Item via the createChatMessage hook. OSE doesn't seem to pass anything into the Chat Message that reference the item being used.
