### ISSUE TITLE
[Bug] Custom animation not working in templates 

### ISSUE THREAD

**Issue by RavenknightDM** [otigon/automated-jb2a-animations#214]
Hiya, with 0.6.1 I've lost the ability to show custom animations in templates. They appear just fine in target and self animations though.

Edit: Scratch that. It seems like that I've lost all template animations not just the custom ones.

Another edit: It seems that the templates that have a set animation (Such as Fog Cloud) works as intended. (Sorry for being confused. :D )

**Comment by napolitanod** [comment]
I'm experiencing issues with custom templates also. Here is the error in the console.log along with my settings.
![image](https://user-images.githubusercontent.com/22696153/132962636-16843779-7c93-47c3-ae62-df769cec328a.png)
![image](https://user-images.githubusercontent.com/22696153/132962653-1fbeb245-eddc-47c5-9aa9-257b2c2bf474.png)
![image](https://user-images.githubusercontent.com/22696153/132962664-dca8e694-3060-453e-8364-97c3e17ccbd3.png)

**Comment by otigon** [comment]
Thanks for letting me know on these. I'm looking at this now

**Comment by otigon** [comment]
I just pushed version 0.6.02 to fix this. Let me know if this resolves your issues

**Comment by RavenknightDM** [comment]
That did the trick! Thank you so very much for all your hard work. This mod is amazing!
