### ISSUE TITLE
[Little BUG] Little incompatibility with other modules "Cannot read properties of undefined (reading 'replace')"

### ISSUE THREAD

**Issue by p4535992** [otigon/automated-jb2a-animations#218]
### Environment Details

* Foundry VTT Version: 0.8.9
* Operating System: Linux
* How Are You Using Foundry: Native Application (Electron)
* Which Game System: dnd5e v.1.4.2
* Modules Enabled?: yes
* Module Version 0.6.02

### Issue Description

A exception is come out when [CUB](https://github.com/death-save/combat-utility-belt) is enable.

![1](https://i.imgur.com/PFdtDyO.png)

![2](https://i.imgur.com/qzog8ne.png)

A simple solution maybe is just put a check for undefined on the 'oldname' variable.

**Comment by otigon** [comment]
Is this with everything, or just certain specific settings?

**Comment by otigon** [comment]
I enabled CUB on my dev world and don't have any of these issues. If you can do a few things it would help me to pin down why the error is occuring:
1. Export the item and send it to me on Discord. You can find  me in the JB2A discord or at Otigon#2010. If this is from the automatic recognition I'll need those exported settings as well
2. Let me know if this is only occurring with a specific set of items, or across the board.

**Comment by p4535992** [comment]
After some tests, it seems that everything is attributable to midiqol.

The error occurs during a fight at the time of the attack roll, this regardless of the token, item and the combat.
When Disabling the midi module the error disappears.
Unfortunately, I was not able to understand more in detail

![img](https://i.imgur.com/8meA0U3.png)

I attach my midi-qol json if it can help
[fvtt-midi-qol-settings.json](https://github.com/otigon/automated-jb2a-animations/files/7157426/fvtt-midi-qol-settings.json.txt)

**Comment by otigon** [comment]
I have added a few checks in to exit out prior to the regex if the name field sent is undefined. Can you let me know if this is still occuring?

**Comment by p4535992** [comment]
I verified that with the version in question without the Babele module the problem persisted. After updating the module the problem disappeared. I'm sorry I didn't dig into what caused it.
I close the ticket because it is solved for me.
