### ISSUE TITLE
[System Request] Add Support to Dungeon World

### ISSUE THREAD

**Issue by brunocalado** [otigon/automated-jb2a-animations#22]
You did an amazing job. Thank you.

Can you add support to DW? I can try to help.

**Comment by otigon** [comment]
I'll take a look, I'm in the process of adding some other systems as well

**Comment by brunocalado** [comment]
I was think if is possible to just send you a markdown file. 

So you can focus on just the system undertand the markdown.

**Comment by otigon** [comment]
Yeah that would be great

**Comment by otigon** [comment]
Tracking system additions in #166
