### ISSUE TITLE
Aura's are extremely hard to scale properly, can you set it to measure by FT instead?

### ISSUE THREAD

**Issue by Avitale34** [otigon/automated-jb2a-animations#224]
Aura's are extremely hard to scale properly, can you set it to measure by FT instead?

**Comment by otigon** [comment]
I will be updating Auras after the Sequencer version 1.0 release. Until then I'm limited by how CTA defines the scale

**Comment by otigon** [comment]
This will be changed in the next update so you can set the size of the Aura in grid distance.

**Comment by otigon** [comment]
Auras now scale by setting the radius distance
