### ISSUE TITLE
Tormenta 20

### ISSUE THREAD

**Issue by cleciojunior2** [otigon/automated-jb2a-animations#227]
Do you have any tutorials on how to configure on Tormenta 20? I did everything in the foundry version 0.8.9 but I couldn't.

**Comment by otigon** [comment]
Not sure what you mean by configuring Torments 20? Are you not able to get animations to play?

**Comment by cleciojunior2** [comment]
Exactly, I followed all the instructions on how to set up the module, but it didn't work out. I'm using the latest versions of Foundry, Sequencer, FXMaster and JB2A. Can you help me?

**Comment by cleciojunior2** [comment]
I tested on DnD5e and it worked perfectly but it didn't work on Tormenta 20, plz save me.

**Comment by otigon** [comment]
I can take a look today, but it also looks like you need to update Automated Animations. Please do that first and see if everything works

**Comment by cleciojunior2** [comment]
I updated Automated Animations and tried again but didn't succeed:

![Screenshot_1](https://user-images.githubusercontent.com/90729577/133467501-427ccb1d-1ff1-4352-9723-71525aff9bb4.png)
![Screenshot_2](https://user-images.githubusercontent.com/90729577/133467506-151abb18-5c41-431f-8e3d-27cdb0a19263.png)
![Screenshot_3](https://user-images.githubusercontent.com/90729577/133467507-150f00b5-f72c-4cca-bc34-9be96a606b3f.png)

**Comment by otigon** [comment]
No wories, are any errors showing in the console (F12) when you expect an animation?

I'll take a look at this later today

**Comment by cleciojunior2** [comment]
On the console appears this:

![Screenshot_4](https://user-images.githubusercontent.com/90729577/133486642-819af3cc-5334-4a64-a958-0374ccbe4b07.png)

**Comment by otigon** [comment]
I found the error, it was a typo on my end. I'll push the fix in a few hours.
If you want to fix it locally in the meantime you can change line 435 in autoAnimations.js from
if (game.user.id === msg.user.id) {
to
if (game.user.id !== msg.user.id) {

**Comment by otigon** [comment]
Issue should be resolved as of A-A version 0.6.14

**Comment by cleciojunior2** [comment]
it worked out! thank you so much, your work is fantastic, I'm from Brazil and here we are going through a financial crisis but as soon as things get better I will make a donation, thank you once again!

**Comment by otigon** [comment]
Hey it's no problem, glad I was able to resolve the problem!
