### ISSUE TITLE
D&D5e Range and On Token animations not working.

### ISSUE THREAD

**Issue by Cull3411** [otigon/automated-jb2a-animations#228]
D&D5e Range and On Token animations not playing.

Foundry VTT 0.8.9
D&D5e  1.4.3
Same modules as your 9/10  https://youtu.be/RcoNepDRj4M
Automated Animations 0.6.13

I worked on it several hours last night and added several entries to Automatic Recognition Setting. I had not used it before.  They all worked great!
Hooray!

Today I was going to do more and retested some of the Range and On Token ones from last night and they don't work now.
Awww...

Most obvious is that the link at the top of the item sheet " A-A "  does not open a window.  This is true for items I have changed and ones I just now pulled from the Spell SRD compendium.

New Automatic Recognition Settings for Range and On Token don't work either.

The Melee animations are working.

**Comment by otigon** [comment]
So they worked last night but not today? Can you check your console (F12) for errors when you expect an animation, and also when you try to open the A-A button on the item sheet? Please send shots of both

**Comment by Cull3411** [comment]
Hi,

It's great you responded so quickly.

Yes, it worked last night. I didn't add any modules since then. I just started up the sever and tested my last thing just as a matter of process.  Surprised.

Casting Cure Wounds Start to finish

When I click A-A button for Cure Wounds

Modules:

![bgicgmckiojpjjkn](https://user-images.githubusercontent.com/77463883/133508501-42255b45-78d1-47ae-827a-5c77c5cad963.png)
![dhilnadmbmpnliag](https://user-images.githubusercontent.com/77463883/133508507-e08b3422-b914-48c3-a623-425b4bf09915.png)
![inebbfbdecnpklpg](https://user-images.githubusercontent.com/77463883/133508509-38c15a36-c09b-43fe-824f-de0f765a6dd5.png)
![gnnnafofdognggic](https://user-images.githubusercontent.com/77463883/133508512-1340e638-67c7-4fc3-abf6-b0f4bcf09853.png)

**Comment by otigon** [comment]
Can you export your automatic recognition settings and send them?

**Comment by otigon** [comment]
I'm taking a look at this now, but can't replicate any of the errors. If you can export your Automatic Recognition menu settings, and export the Cure Wounds item, that would help me narrow down the issue

**Comment by Cull3411** [comment]
Sorry I was replying to the emails GITHUB sends   See below:

On 9/15/2021 5:31 PM, DM wrote:
> On 9/15/2021 5:28 PM, DM wrote:
>> On 9/15/2021 5:23 PM, otigon wrote:
>>>
>>> Can you export your automatic recognition settings and send them?
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub, or unsubscribe.
>>> Triage notifications on the go with GitHub Mobile for iOS or Android.
>> One from last night (2) and one from just now (3).
>>
>> I was thinking I would try removing the module and reloading it.
>>
>>> I reloaded the export from last night and it seems to be working again.  Still testing, but so far it's working.
>
I don't know how it happened but I think I found the unwanted null.

This doesn't work  (3) 

 },
    "16": {
      "hidden": true,
      "name": "",
      "animation": "a1",
      "variant": "",
      "color": "",
      "repeat": 1,
      "delay": 500,
      "scale": 1,
      "below": false,
      "custom": false,
      "switchType": "on"
    }
  },

This does work (corrected in the .json file and reloaded)

   },
    "16": {
      "hidden": true,
      "name": "test",
      "animation": "a1",
      "variant": "",
      "color": "",
      "repeat": 1,
      "delay": 500,
      "scale": 1,
      "below": false,
      "custom": false,
      "switchType": "on"
    }
  },

Had to make the .json ,txt to upload them here.

[fvtt-autoanimations-autorecognition (3) test.txt
[fvtt-autoanimations-autorecognition (3) test.txt](https://github.com/otigon/automated-jb2a-animations/files/7173806/fvtt-autoanimations-autorecognition.3.test.txt)
[fvtt-autoanimations-autorecognition (3).txt]
[fvtt-autoanimations-autorecognition (3).txt](https://github.com/otigon/automated-jb2a-animations/files/7173807/fvtt-autoanimations-autorecognition.3.txt)
[fvtt-autoanimations-autorecognition (2).txt
[fvtt-autoanimations-autorecognition (2).txt](https://github.com/otigon/automated-jb2a-animations/files/7173808/fvtt-autoanimations-autorecognition.2.txt)

**Comment by otigon** [comment]
ahhh  I see where that's breaking down now. Thank you for sending me that. So if any "Item Name" field is left empty, that considers it an automatic match while doing the name comparisons since I'm using an includes() method and not equals comparisons.

Glad to know that particular error is resolved for now. I'll add some checks in account for blank fields

**Comment by otigon** [comment]
Ok I've added in a few lines to correct those errors to bypass automatic recognition items that have a blank Name field. Please let me know if any other errors occur.

I'll close this issue for now
