### ISSUE TITLE
Cannot Delete Tiles Created by Templates

### ISSUE THREAD

**Issue by Cull3411** [otigon/automated-jb2a-animations#229]
Cannot Delete Tiles Created by Templates

Foundry VTT 0.8.9
D&D5e 1.4.3
Same modules as your 9/10 https://youtu.be/RcoNepDRj4M
Automated Animations 0.6.13

Process:
Create Automatic recognition Setting as shown in screenshot
Cast spell
Select created tile
Press Delete Key

Error is displayed and tile does not delete.

Browser refresh removes the tile.

![tile delete](https://user-images.githubusercontent.com/77463883/133537343-331fd8f3-f492-40e1-92b0-07a9514329ac.jpg)

**Comment by otigon** [comment]
This is an error that occurs in Foundry sometimes, but there is really no way to know why. Have you tried Find the Culprit to see if there is a module interfering?
