### ISSUE TITLE
Animation with Better Rolls for 5e Inconsistant

### ISSUE THREAD

**Issue by MrBrentRogers** [otigon/automated-jb2a-animations#23]
On my home Foundry installation automated-jb2a-animations works perfectly with all modules I use (Better Rolls for 5e included).
On FoundryServer where I host automated-jb2a-animations doesn't work with Better Rolls for 5e enabled. 

I've tested extensively if it was a combination of modules that allow/ not allow Better Rolls for 5e & automated-jb2a-animations to no success in finding any issues.

So far I've only gotten Better Rolls and AA-JB2A in only one world on my home system :(

**Comment by otigon** [comment]
This is odd. Have you checked to ensure the Better Rolls on your Foundry Server is fully updated? Their latest release added specific support for A-A to play animations on Attack Rolls.

It might be worthwhile to try an uninstall-reinstall of Better Rolls on your server.

**Comment by MrBrentRogers** [comment]
Issue seems to be with certain scenes. Unknown reason for scene issues.
