### ISSUE TITLE
[BUG] Can not open the animation tab of an item if this Item is recognize as a default animation

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#231]
Hello,

Assuming an item with a name recognize by the default animations array. Clicking on the "A-A" button will throw this error, and not open the tab:
![image](https://user-images.githubusercontent.com/1687854/133820249-b9ca09b9-2339-4d72-8ccb-3c43ee531b41.png)

**Comment by otigon** [comment]
Are you on the latest version 0.6.17? I thought I fixed that last night

**Comment by DarKDinDoN** [comment]
@otigon sorry forgot to give you this information

FVTT 0.8.9
5e 1.4.3
AA 0.6.07

**Comment by otigon** [comment]
I, I'll get that fixed today after work

**Comment by otigon** [comment]
@DarKDinDoN can you send me an item that has this issue? I can't replicate on my local machine
