### ISSUE TITLE
Missing configuration in the default animation configuration window

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#232]
Hello,

The checkbox "Scale by Token Size" is missing in the default animation configuration window.

FVTT 0.8.9
5e 1.4.3
AA 0.6.18

**Comment by otigon** [comment]
That is intended. I have switched it to scale to token size by default, and will be switching the Item menus to the same in a future update.

**Comment by otigon** [comment]
I built the Automatic menus in the way I plan on switching the Item menus to. I just need to work on a merge script so I don't blow everything up

**Comment by DarKDinDoN** [comment]
@otigon Ok i think I understand what's happening here. You are right it's "scale by token size" by default.

Tested the same animation on two different grid size.

Square size to 50 pixels:
![image](https://user-images.githubusercontent.com/1687854/133866220-b58a7151-8aa4-497c-a805-380c9e1f39a4.png)


Square size to 100 pixels:
![image](https://user-images.githubusercontent.com/1687854/133866243-039770e1-cc5b-4903-8399-f9edcc25f37d.png)


As you can see with 50 pixels squares, the animation if smaller than with 100 pixels square.

**Comment by otigon** [comment]
Not understanding what you're saying. Is that the same scale on two different grid sizes?

**Comment by DarKDinDoN** [comment]
@otigon 

Assuming:
- default animation array defaults to "Scale by Token Size"
- Scale of a static (onToken) animation: 3


I'm expecting the animation to be 3 times bigger than the token:
![Group 1](https://user-images.githubusercontent.com/1687854/133888658-e2aa9653-cf50-473a-8437-44a36c530fb6.jpg)

It works perfectly on a 100px grid size:
![image](https://user-images.githubusercontent.com/1687854/133888725-83c67f7c-f8ec-499a-b05f-a688b4f32943.png)

But on the 50px grid size, the same animation with the same scale is smaller:
![image](https://user-images.githubusercontent.com/1687854/133888773-a7df293a-89ec-48de-bf78-91d9d91b3da6.png)



After some digging, I think I found what's going on here.

By default, Sequencer is assuming a 100px grid size: https://github.com/fantasycalendar/FoundryVTT-Sequencer/blob/4a7d71f6579ede30af6ae5cfd423085b5b583bd4/scripts/module/sections/effect.js#L31
That is why it is working correctly on a 100 px grid size.

But when the grid size is 50 px, Sequencer still compute the animation size based on a 100 px grid size (hence a smaller animation).
If I'm not mistaken, Sequencer offers a method called `gridSize()` to pass it the scene grid size. Did some tests (but not extensive), and it seems to fix the issue.

I didn't make a PR because this fix needs to be applied on all animatons except a few ones (like melee animation that is working fine at the moment).

**Comment by otigon** [comment]
That was baked into a lot more of the module than I realized. I do have a fix in for the next release, I'll let you know when it's active

**Comment by otigon** [comment]
Scaling issues should mostly be resolved as of 0.6.20. It was a nasty merge so I'll give it another look-over

**Comment by DarKDinDoN** [comment]
@otigon Hey, did a few tests, seems to be working like charm!

**Comment by otigon** [comment]
yeah I'm learning some new tricks with Sequencer along the way, going to be switching out the Custom Token Animation requirements to use only Sequencer. This will affect Auras and Bless initially, but I'm looking at adding support for persistent effects in more areas. I'll send you a video

**Comment by DarKDinDoN** [comment]
@otigon Ouuuuuhh, yeah looking forward to this. That seems to be a great feature. 😄
