### ISSUE TITLE
Closing Automatic Recognition Settings without submitting changes causes module to fail

### ISSUE THREAD

**Issue by DylanAngell** [otigon/automated-jb2a-animations#239]
Adding an item to any category in the Automatic Recognition Settings and then closing the window without submitting changes will cause the module to not operate. Animations will not play and the Item Animation Settings window will not open on any item. Can be resolved by re-opening the Automatic Recognition Settings and either submitting or deleting the un-submitted changes.

Attached image shows console error when trying to render the Item Animation Settings window during this issue.

![Capture](https://user-images.githubusercontent.com/56407578/134254349-ffae28ef-5649-44c0-b6f6-f6c7246e9395.JPG)

**Comment by otigon** [comment]
Thanks for the report. I was able to replicate the issue. I'll look into this and see how to fix it.

**Comment by otigon** [comment]
Issue should be resolved as of 0.6.51
