### ISSUE TITLE
Problem when a temporary item is rolled

### ISSUE THREAD

**Issue by tposney** [otigon/automated-jb2a-animations#243]
In midi-qol I occasionally create a temporary item (i.e. not a world item and not an actor owned item) and roll it. The causes an issue in getdata-by-system, line 57. Where ```token.actor.items.get``` can return null.

Can I ask that the item get guarded by
```if (!item) return;``` immediately after the get?

**Comment by otigon** [comment]
Will do, I'll get that patched today. I want to say I had that in before, but it may have dropped off when I restructured all of that.

**Comment by otigon** [comment]
Fix is active with version 0.6.27

**Comment by tposney** [comment]
Many thanks
