### ISSUE TITLE
enhancement: sneak attack on first attack vs feature

### ISSUE THREAD

**Issue by SR5060** [otigon/automated-jb2a-animations#244]
given that sneak attack is a passive feature, it would be great if the animation triggered on the first applicable attack vs clicking on the feature itself.

**Comment by otigon** [comment]
That would require a higher level of integration with the game system that I don't currently have plans for. In particular for this, there is no way to tell the system which attack you are rolling. All it sees is a roll showing up in Chat.

**Comment by SR5060** [comment]
fair enough, if you do decide to explore this in the future, midi qol srd module has a sneak attack that uses flags to detect/activate the feature. that flag may be a (relative) simple way to trigger the animation.
