### ISSUE TITLE
Randomized item sounds

### ISSUE THREAD

**Issue by Vesselchuck** [otigon/automated-jb2a-animations#245]
I'll provide an example, we can use “Randomize token image” option by typing the name of file like this: “token_folder/token_*”. Then it will randomly pick one of the files from the directory which named “token_1" or “token_2". Can this thing be implemented for Automated Animations sounds to have randomized sounds for swings/shots/etc?

**Comment by otigon** [comment]
It will be when I rework all of the audio. That won't be for another two or three weeks maybe
