### ISSUE TITLE
Problems with Savage Worlds

### ISSUE THREAD

**Issue by Diogoarakis** [otigon/automated-jb2a-animations#249]
I got a list of problems I found running Animated Animations with Savage Worlds

System - Savage Worlds 0.20.4
Extra Modules - 
Better Rolls 2 for Savage Worlds
Token HUD

1. "Template Animations" won't work with Cone template. 
2. When I set a custom "Template Animation" on a item, it works properly - I place the template and the animation runs when I roll the test. But with the "Automatic Recognition" its presents a strange behavior: the animation runs when I place the Template, not when I roll the test, and do not work every time I activate it.
3. With the "Automatic Recognition" some items behave different depends on where I activate it: from the Token HUD, or from the shortcut or directly from a sheet

**Comment by otigon** [comment]
Sorry but I won't be updating SWADE support any further. The system and how it operates are too far outside of my knowledge base. If you know anyone that has Javascript / System Knowledge who can help out please feel free to send them my way

**Comment by SalieriC** [comment]
I wanted to tackle the templates (with BR2) for a while now. The thing is, I currently lack two things: A Hook from BR2 with the required information and I don't know how and where templates are handled by A-A.

**Comment by otigon** [comment]
I'll send you a breakdown of how Templates are handled on the latest A-A later this morning
