### ISSUE TITLE
Star Wars 5e animations are no longer working

### ISSUE THREAD

**Issue by gravagehulk** [otigon/automated-jb2a-animations#250]
Hi, it's me again. 

I'm not sure what changed, but the animations are no longer working for Star Wars 5e. As you can see in the screenshot, I have everything set, but there is no animation. Also, I have a sound set and that sound does not play when the weapon is fired. This was all working the last time you fixed things, but the next time I loaded my game, they were broken again. I disabled and re-enabled both Automated animations and JB2A, as well as sequencer. I also tried clearing the animation completely and resetting it. 

It just never works.
<img width="610" alt="Screen Shot 2021-09-29 at 7 58 47 AM" src="https://user-images.githubusercontent.com/69117052/135273561-dae35b79-3bdc-4d6b-a58b-6cb6d4e2d86e.png">

**Comment by otigon** [comment]
I'll give SW5e a check today

**Comment by gravagehulk** [comment]
> I'll give SW5e a check today

Thank you, sir. If you need to connect to my game for testing, let me know. I think I still have you on discord. I will make myself available.

**Comment by otigon** [comment]
Fixed as of 0.6.31. Sorry for the inconvenience

**Comment by gravagehulk** [comment]
Thanks again!
