### ISSUE TITLE
Compatibility with other systems

### ISSUE THREAD

**Issue by trodrigues1505** [otigon/automated-jb2a-animations#251]
Could you create compatibility of this module for systems: Tagmar, Old Dragon and Sand Box?

**Comment by otigon** [comment]
Sandbox no, I'll have to check Tagmar and Old Dragon. I try to keep a master list located here for systems I've checked #166

**Comment by otigon** [comment]
systems added to #166 to check

**Comment by trodrigues1505** [comment]
Thanks!!!!

Em qua., 29 de set. de 2021 às 17:25, otigon ***@***.***>
escreveu:
