### ISSUE TITLE
[5e] "Hunter's Mark" missing in default animation configuration window

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#252]
Hello,

FVTT 0.8.9
5e 1.4.3
AA 0.6.31

Hunter's Mark seems to me missing in the "presets" tab in the default animation configuration window.

**Comment by otigon** [comment]
It will be in on the 0.6.50 release in the next week or two. I'm finishing up a lot of reworks on all the menus

**Comment by otigon** [comment]
HM is in the Auto-rec Menus as of 0.6.51
