### ISSUE TITLE
Macro to Manually Trigger Item Animation

### ISSUE THREAD

**Issue by brunocalado** [otigon/automated-jb2a-animations#253]
Hi.

I'm trying to write a macro that will read an actor. Let the user pick an item and then play the animation.

I'm trying to use this:
`AutoAnimations.playAnimation(tokenD, game.user.targets, itemFromDir)  `

But, I'm getting an error:
![image](https://user-images.githubusercontent.com/4999783/135654323-8c35d37a-48cf-4171-b115-eca6fe1e9f94.png)

This is the item AA
![image](https://user-images.githubusercontent.com/4999783/135654394-2017d43a-7b40-4428-b12a-bf7b9fc06203.png)

This is the basic code:
```  js
let itemName = html.find("#selecteditem")[0].value;  
  
  let itemFromDir = game.items.contents.filter(e => e.type === 'cItem' && e.name === itemName && e.data.flags.autoanimations.override)[0];  
  
  console.log('------------------');
  console.log(itemName);
  console.log('------------------');

  AutoAnimations.playAnimation(tokenD, game.user.targets, itemFromDir)  
```

Can you give some help? 

Thank you.

**Comment by otigon** [comment]
Try sending the game.user.targets as Array.from(game.user.targets)

**Comment by brunocalado** [comment]
worked. tks

**Comment by otigon** [comment]
I'll add some checks in to convert it to an array on my end as well
