### ISSUE TITLE
SWADE But After update

### ISSUE THREAD

**Issue by brunocalado** [otigon/automated-jb2a-animations#254]
After the last update I started to get errors.

![image](https://user-images.githubusercontent.com/4999783/135670343-d7ad30b9-9e1f-4826-950a-9fe785e175fb.png)

**Comment by otigon** [comment]
do you have the latest JB2A release? That looks like one of the files from their release yesterday

**Comment by brunocalado** [comment]
Maybe the update failed. I'll try again after delete the module

**Comment by brunocalado** [comment]
I had an update issue. 

Worked. Tks
