### ISSUE TITLE
[SWADE] Error

### ISSUE THREAD

**Issue by brunocalado** [otigon/automated-jb2a-animations#255]
I can't find a pattern to better report this. 

Sometimes I just get this error:

![image](https://user-images.githubusercontent.com/4999783/135675304-f53c35db-fc5c-4f9f-aee2-046857503ee0.png)

**Comment by otigon** [comment]
Is this just random or is it limited to certain items?

**Comment by brunocalado** [comment]
Both items had the same AA. But, one of them don't work.

![image](https://user-images.githubusercontent.com/4999783/135678244-64349a93-5de5-4590-acdd-a2563f5f0f75.png)

**Comment by otigon** [comment]
If you can export both of those items and send them to me on discord at Otigon#2010 I can take a look this weekend.

In case you don't know how, drag each item to the Item bar on the right, right-click and choose export

**Comment by brunocalado** [comment]
I find out how to trigger the error.

If you create the animation in a actor an move the actor to the scene it will work.

If you create the animation in a unliked token it'll generate the error.

**Comment by otigon** [comment]
hmm, that sounds like it it related to the system (SWADE) rather than anything else. I've not had that error in 5e and PF2e

**Comment by otigon** [comment]
I'll leave this open until I can check it this weekend to replicate the error. I'm interested to see why this is occuring

**Comment by SalieriC** [comment]
Have you tried this with system rolls @brunocalado? Because I *think* this is a quirk with BR2. BR2 always seems to try to get the items from the actor, instead of the token.

**Comment by brunocalado** [comment]
It's BR2. Just want this to work with BR2.

**Comment by SalieriC** [comment]
Then I think this can be closed @otigon.
It's a BR2 problem as far as I can tell. The reason being that BR2 uses the actors item to roll, not the tokens item. This means that on linked tokens it's all good but on unlinked tokens the actor needs to carry the data, not the token. Ask Javier about it if you want it fixed @brunocalado but it's a quirk in BR from the beginning of BR1 so I am not sure if this can and will be fixed.

**Comment by brunocalado** [comment]
> 

Already did. BR2 told me to came here. jb2a told me to go to br2.

**Comment by SalieriC** [comment]
I just realise, my recent PR might've actually fixed that problem as well. Please go try @brunocalado, it seems to work for me.
