### ISSUE TITLE
Source token animations do not play

### ISSUE THREAD

**Issue by bibicvc** [otigon/automated-jb2a-animations#257]
Source token animations do not play. There is no associated error I can spot in the console. These were functioning correctly last I checked 20 days ago. 

I figured out how to fix it - if you enable "custom animations" while the preceding two entry boxes are blank, the animation won't play.

If you enable "custom animations" after choosing an option for the entry boxes, it will function correctly. It doesn't matter what options you pick in the entry boxes that disappear as long as they are not blank.

This doesn't work:
![image](https://user-images.githubusercontent.com/68487801/135762976-2210db5f-848f-4fb3-8f6c-7ab02f85a94f.png)
![image](https://user-images.githubusercontent.com/68487801/135762982-953bc6e8-c02e-4d41-be56-b0c38d2be698.png)

This does work:
![image](https://user-images.githubusercontent.com/68487801/135762991-6133e037-ba3e-4d7e-8002-7b914f0c8ecc.png)
![image](https://user-images.githubusercontent.com/68487801/135763142-1986d6fc-ef03-4130-93cf-6f43264ce677.png)

**Comment by otigon** [comment]
I'll have this fixed on the next released

**Comment by otigon** [comment]
Issue should be resolved as of version 0.6.51
