### ISSUE TITLE
System Request: Twodsix

### ISSUE THREAD

**Issue by Darkluc9850** [otigon/automated-jb2a-animations#259]
Hey, recently I started using [Twodsix](https://foundryvtt.com/packages/twodsix) game system for sci-fi and would really love to have animations play on the weapon attacks.
Thanks.

**Comment by otigon** [comment]
I've updated the Readme on the main page to note that I'm no longer adding support for anymore systems. I will add a section on the Wiki page to detail how to add support via a pull request. Sorry for the inconvenience.
