### ISSUE TITLE
Request: override flag to play when action is first clicked?

### ISSUE THREAD

**Issue by modzy2** [otigon/automated-jb2a-animations#26]
For actions that involve no attack rolls, would it be possible to have a flag to play an animation anyway when the action is first clicked?  Something like Atropal's life drain, where there is no roll.  I can set a dummy roll, which works fine.

**Comment by otigon** [comment]
Is this for abilities that have neither an Attack Roll or Damage Roll?

**Comment by modzy2** [comment]
It has a damage roll, but I like the animation on the attack roll for everything that has one

**Comment by otigon** [comment]
Items without attack rolls or damage rolls should play more consistently now, so this type of setting shouldn't be needed anymore
