### ISSUE TITLE
Add Sound to Auto Recognition

### ISSUE THREAD

**Issue by brunocalado** [otigon/automated-jb2a-animations#260]
Can you add sound to  Auto Recognition?
![image](https://user-images.githubusercontent.com/4999783/136716696-7aaee261-78f7-4dbd-adf0-96421f7c33eb.png)

tks

**Comment by Smithythe** [comment]
This sounds like a very welcome feature. Will there be support for playlists also in your Audio system update? The ability to use array of random audio files would be a cherry on already nice cake.

**Comment by otigon** [comment]
Active in version 1.0, closing issue
