### ISSUE TITLE
More options for Token and Target Animations

### ISSUE THREAD

**Issue by DrYima** [otigon/automated-jb2a-animations#261]
Thank you for the great module first and foremost!
I think adding more options (for example, having the Target animation not play when the attack misses, but still have the modified missing main animation play, which is mainly why i am here eheh) to the +Token FX tab could add a lot to the module, also, i know custom animations can be inserted but is there maybe a possibility to add the effects from token magic in any way?

Thank you again for your work and i wish you a good day

**Comment by otigon** [comment]
Thanks for the compliment, much better than your bitchy attitude on Discord! Your snarky comments aside, I'll take a look at adding some of these features since they are valid

**Comment by otigon** [comment]
I have a fix in for this on the upcoming 0.6.50 release. Behavior will be that the Target FX animation will play if the target is hit, and not play if missed.

**Comment by otigon** [comment]
Issues should now be resolved as of version 0.6.51
