### ISSUE TITLE
Can't delete aura from token.

### ISSUE THREAD

**Issue by RavenknightDM** [otigon/automated-jb2a-animations#264]
Hiya, fist a great big thanks for this amazing module. :)
I have an issue with auras though (Spirit Guardians) when activated they stay even after the effect is gone from the token and I can't find any way to delete them from the tile layer. Am I missing something ( I probably do) or is this a bug?

**Comment by otigon** [comment]
Use the Sequencer Effect Manager, a button on the 1st left hand menu
