### ISSUE TITLE
Fall back to weapon group/base weapon if no matches were found

### ISSUE THREAD

**Issue by CarlosFdez** [otigon/automated-jb2a-animations#266]
So both PF2e and 5e (more recently) have the concept of a base weapon/weapon group. It'd be nice if we could have animations attempt to match on the base weapon/weapon group if it fails to match on the item name.

For example, Guns and Gears came out recently, and these are all the weapons in the firearm group: https://2e.aonprd.com/WeaponGroups.aspx?ID=16 that I'd love to have a catch-all animation for.

I could create a PR for this if you're extremely busy.

**Comment by otigon** [comment]
yeah I might try the fallback method first since it does match on an includes() method, that would be the easiest implementation so I'll see how that plays out first

**Comment by otigon** [comment]
Not going to be adding this feature

**Comment by CarlosFdez** [comment]
That's a shame. I'd have been willing to do it myself, but it seems you've decided against the idea of falling back to base weapons (frostbrand to longsword) or would rather target base weapons instead somehow. Or neither.

**Comment by otigon** [comment]
You're more than welcome to issue a pull request to add that functionality, I'm just not personally adding in anymore system specific features

**Comment by CarlosFdez** [comment]
Sure! This weekend I'll look into adding it for both 5e and 2e. They both have base weapon as a concept, and was the reason I even pitched it in the first place.

**Comment by otigon** [comment]
Awesome, I look forward to it and very much appreciate it!
