### ISSUE TITLE
Start Teleport SFX when destination is chosen.

### ISSUE THREAD

**Issue by SalieriC** [otigon/automated-jb2a-animations#272]
Teleport opens a template in which a token can relocate. The SFX is played as soon as the roll is executed (delayed by the usual means). I'd suggest to start the sfx only once the location to teleport to is chosen in order to make sure the sfx is synchronised with the animation.

**Comment by otigon** [comment]
I'll get this feature added on 0.7.00

**Comment by otigon** [comment]
Active in version 1.0, closing issue
