### ISSUE TITLE
BUG: Auras are off-center

### ISSUE THREAD

**Issue by GambetTV** [otigon/automated-jb2a-animations#276]
Auras are slightly off it seems, dropping a little down and to the right, by about 10% if I had to guess.

![image](https://user-images.githubusercontent.com/72000497/139527180-40655bd8-8e33-46ea-a5c2-536d34753f65.png)

**Comment by otigon** [comment]
Please use Find the Culprit module to test with just Sequencer and Automated Animations active. This looks like a module is interfering somehow, as I cannot replicate the issue (they are centered perfectly for me)

**Comment by GambetTV** [comment]
Just did so, and the bug persists. The problem seems to occur when a token's "Scale" is set to something other than 1. The higher the number gets the more off-center it becomes. Note: To duplicate this you'll have to remove the previous effect, change the scale, and then reapply the effect.

![image](https://user-images.githubusercontent.com/72000497/139556472-850fb79d-ee42-483e-89e7-5af9772d4d54.png)
![image](https://user-images.githubusercontent.com/72000497/139556491-4f11e656-807e-4ed5-84f9-877eb2d5bc13.png)
![image](https://user-images.githubusercontent.com/72000497/139556513-97b05fc0-2bd5-428d-909a-6c27a392829c.png)
![image](https://user-images.githubusercontent.com/72000497/139556524-269a8067-c485-4fce-b74a-c6682ad8bc84.png)

**Comment by otigon** [comment]
I've reported this on the Sequencer issues list, as this is not a problem with Automated Animations, but has something to do with Pixi
