### ISSUE TITLE
Support for Cyberpunk Red Core system

### ISSUE THREAD

**Issue by Dadrak** [otigon/automated-jb2a-animations#278]
**Description:**

Potential Automated Animations module support the Cyberpunk Red Core system on FoundryVTT

**Proposed Feature:**

Cyberpunk Red Core is a game system used to play the game on FoundryVTT. The support of A-A would allow players to use the animations provided by JB2A and add their own sounds to attack, damage and other type of rolls

Here is the systems Gitlab : https://gitlab.com/JasonAlanTerry/fvtt-cyberpunk-red-core

Here is the systems FoundryVTT page : https://foundryvtt.com/packages/cyberpunk-red-core

I understand that you all have other priorities and that this is only a visual enhancement, still I hope you take it under consideration and as always thank you for your hard work.

**Comment by otigon** [comment]
I've updated the Readme on the main page to note that I'm no longer adding support for anymore systems. I will add a section on the Wiki page to detail how to add support via a pull request. Sorry for the inconvenience.
