### ISSUE TITLE
Adding Automatic Recognition causes animations to break

### ISSUE THREAD

**Issue by jerichojx** [otigon/automated-jb2a-animations#279]
Every time I add a Preset, Template or Aura Automatic Recognition, it breaks all animations including those attached to items or features

Even though I do not fill up any information, it just breaks any and all animations.

If I create an animation attached to an item or feature, it does not break anything

Foundry version: 0.8.9
System: Star Wars 5E
System version: R1-A8
![AA bug](https://user-images.githubusercontent.com/67579273/141221766-edfce079-5710-46ba-9a34-5763d2fa2b93.png)

**Comment by otigon** [comment]
Have you tried deleting the blank field?
What errors are showing in the console when it fails?
What A-A version?

**Comment by otigon** [comment]
closing due to no response
