### ISSUE TITLE
Mace animation causes red spot to remain forever after animation completes

### ISSUE THREAD

**Issue by DFreds** [otigon/automated-jb2a-animations#28]
![image](https://user-images.githubusercontent.com/11878569/114120270-252d5900-98ba-11eb-8988-b852d878b60f.png)

See image

**Comment by Ziggomatica** [comment]
You should be able to use the TokenMagic macro "Delete Filters on Selected" to get rid of that.  (I think it's intended?)

**Comment by DFreds** [comment]
Ah okay. I thought it was a bug... you're right that it can be removed that way. No problem then

**Comment by Ziggomatica** [comment]
After updating to 0.2.73, the blood splatter doesn't seem to happen anymore.

**Comment by otigon** [comment]
I've been phasing out the Blood Splatter effects on many of the Animations. It's much too buggy

**Comment by DFreds** [comment]
Awesome, thanks!
