### ISSUE TITLE
Getting an error whenever I hit a token with concentration

### ISSUE THREAD

**Issue by Deadboydeath** [otigon/automated-jb2a-animations#280]
Hi Otigon,

I'm unsure if this is an autoanimation issue, but this is what pops up in my  errors:
<img width="567" alt="123123" src="https://user-images.githubusercontent.com/89600048/141648979-06a3c77e-859f-4012-9fc8-11abf2f52817.PNG">
<img width="556" alt="235465684" src="https://user-images.githubusercontent.com/89600048/141648981-8e7a3e8f-7b94-47d8-bf7b-9a34a1b1a6e0.PNG">

Can you please take a look?

Thank you,
Deadboydeath

**Comment by otigon** [comment]
I need a little more information on this like the Game System for one. I suspect if this only happens when concentration is active another module is causing issues. Can you try Find the Culprit with only Sequencer/A-A active and see if it persists?

**Comment by Deadboydeath** [comment]
Currently no error pops up when  I hit a token with concentration. Issue might've been removed during the recent updates, I'm not sure. But, thanks for the replying
