### ISSUE TITLE
TypeError when no itemId exists in dnd5e roll flags

### ISSUE THREAD

**Issue by IamWarHead** [otigon/automated-jb2a-animations#282]
![image](https://user-images.githubusercontent.com/78622932/141678860-76505dd5-a94d-432e-a3d0-b00753f44ea7.png)

Report:

The problem is that flag-handler returns undefined if item data does not exist so handler.item will raise a type error.

DoD: 

It should not raise a type error.

**Pull request:**
https://github.com/otigon/automated-jb2a-animations/pull/281

**Comment by otigon** [comment]
will be corrected on 0.6.57 as noted in the PR close
