### ISSUE TITLE
[BUG] Hunter's mark with persistent marker will throw an error without target

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#285]
Hello,

FVTT 0.8.9
5e 1.5.3
AA 0.6.56

Using the Hunter's mark preset without target will display this sequencer error message:
![image](https://user-images.githubusercontent.com/1687854/141988516-79af3932-9576-481a-ba3c-ffe2813cc1c2.png)

**Comment by otigon** [comment]
will be fixed on 0.6.57
