### ISSUE TITLE
Certain PF2e spells cannot be animated

### ISSUE THREAD

**Issue by bennyty** [otigon/automated-jb2a-animations#286]
FVTT: 0.8.9
PF2e: 2.19.0.9009
A-A: 0.6.56

For some spells such as Divine Lance and Moonbeam, when you cast the spell you must make a "Spell Attack" by clicking an extra Attack button on the chat card. This triggers a second chat card to come up. This second `ChatMessagePF2e` object doesn't have a `.item` attached, it's `null`.

![2021-11-21 11_43_55-Steam](https://user-images.githubusercontent.com/592150/142778727-acd92225-7376-453a-9a5d-9e32d69bb431.png)

**Comment by bennyty** [comment]
Quite a lot of chat messages (most of which don't have to do with items or spell attacks at all) seem to cause this warning to appear. Things like adding a condition to a creature causes a message which then errors out.

These extra errors are a lesser concern than the main topic of this issue since they're just console errors and no animation is supposed to play anyway. Just thought it might help for debugging.

**Comment by otigon** [comment]
There a quite a few errors in PF2e from what I gather due to the last system update. I'll check into them. The errors for non item stuff will be fixed on the next release

**Comment by otigon** [comment]
On further investigation, the animation issue with some spells is due to the latest PF2e system release. They seem to have dropped off references to the Item during Attack rolls for spells. If you switch A-A to animate on damage, this can be fixed. Otherwise someone will need to log an issue with the PF2e devs

**Comment by silvative** [comment]
The next PF2E version will fix this bug! Sorry for the trouble.
