### ISSUE TITLE
Be able to set animations items/buffs/player/npc

### ISSUE THREAD

**Issue by BlackWand1** [otigon/automated-jb2a-animations#288]
Hey!

Would be neat to be able to set automated animations for npc and players as well, or at least on items and buffs - to add effectful auras to monsters.
I did some testing and maybe it would be possible, but I did not get it to work. And maybe this module primarily only works together with an "attack".

**Comment by otigon** [comment]
The module works with any item use, it gets different slightly depending on the system. So I'd need more info

**Comment by BlackWand1** [comment]
Hi,
The 3.5e SRD system.

I tried applying some animation to a npc that should be active at all times, like an evil aura.
But could not get it to work.


Robert Winbladh
________________________________

**Comment by otigon** [comment]
did you set it as a Persistent effect?

**Comment by BlackWand1** [comment]
I added an aura to the sheet, and set the following A-A settings. Not showing anything.

![Capture](https://user-images.githubusercontent.com/85252943/143781892-ddb34cc5-f7c7-4290-af51-232b2c1be030.PNG)

**Comment by otigon** [comment]
Try setting it as an Aura instead of a Persistent On Token animation

**Comment by BlackWand1** [comment]
No luck. Also tried some variations.

Does the "Animation Type" really affect anything else rather than a type of grouping of animations?
I also tried the "Source Token Animation" without luck.

**Comment by otigon** [comment]
I've not been able to replicate this issue on my end. It might have something to do with the item being used? Have you tried setting this up on other items?

**Comment by otigon** [comment]
closing due to no response
