### ISSUE TITLE
Suggestion: Global on/off for blood splatter

### ISSUE THREAD

**Issue by napolitanod** [otigon/automated-jb2a-animations#29]
You module is slick and I just started using it. One of the DND games I play is with my 9 year old son. Though he will love the frost beam animation and the like, the blood splatter is not something I want to introduce to him in our game (e.g. scimitar hit animation). I would love to be able to toggle it off as a config.

On the other hand, another group I play with is gonna love the blood and as far as my tastes go, the more splatter the better. Its just for the little ones :)

Thanks!

Dan

**Comment by otigon** [comment]
I'm in the process of removing the "Blood Splatter" effect from the Module. It is quite troublesome for some systems and buggy most of the time when trying to remove it. This refers to the Token Magic FX "bloodsplat" that puts some blood on the token picture briefly.

The animations themselves have some blood effects that I can't remove, as those are part of the Animation file from JB2A.

On a side note, I highly recommend the Blood 'n Guts module for the blood effects on hits.

**Comment by napolitanod** [comment]
Ah, that makes sense that it is in the actual automation itself. Thank you for taking the time to respond. Heading over to the blood n Guts module now!

- Dan
