### ISSUE TITLE
Generic damage animations in Automatic Recognition Settings window

### ISSUE THREAD

**Issue by M0nk3yy** [otigon/automated-jb2a-animations#291]
The "Automatic Recognition Settings" window in the module settings doesn't include options for _generic damage animations_ (which I prefer). This would be nice to have to avoid having to set them on all new weapons :)

![image](https://user-images.githubusercontent.com/66137312/143895427-2ec70d08-df64-4054-a7eb-82d906dffd21.png)

**Comment by otigon** [comment]
Issue is correct as of version 1.0.0
