### ISSUE TITLE
Customizing an animation - Shield not working **BUG**

### ISSUE THREAD

**Issue by UnoriginalDM** [otigon/automated-jb2a-animations#292]
Hello, love the mod. Came across a small bug that is probably an easy fix.
If you choose to do a custom animation and select "On Token" and use the "Condition" "Shield" it throws an error. I noticed when setting it up the animation and selecting "Shield", it does not load the dropdown for the "Variant" or "Color" section like the other conditions (even if the condition only has a single variant and color it still loads the drop down to "01" and "White" respectively).

Setup:
![image](https://user-images.githubusercontent.com/77896718/144620352-c3c69fd4-4ff9-4092-9178-1a8979dd1bfd.png)

Error:
![image](https://user-images.githubusercontent.com/77896718/144620425-470f2ed2-017b-4bde-bb11-20085c391999.png)

**Comment by otigon** [comment]
Hey thanks for the report. I'll take a look at this tonight and see what I can do to fix it.

**Comment by otigon** [comment]
should be resolved
