### ISSUE TITLE
SFX selection for automatic recognition setting

### ISSUE THREAD

**Issue by SalieriC** [otigon/automated-jb2a-animations#293]
In my opinion this is a rather crucial thing, as the automatic recognition is completely ignoring sound effects right now. Automatic recognition has the potential to be a huge time saver but without SFX selection it's pretty much useless for me.

**Comment by otigon** [comment]
I'm in the process of re-doing all the sound options in A-A, but with the Holidays it will take time

**Comment by otigon** [comment]
Active in version 1.0, closing issue
