### ISSUE TITLE
Bug with play animation on damage roll Better Rolls 5e

### ISSUE THREAD

**Issue by remiverdel** [otigon/automated-jb2a-animations#295]
Hi,

The Play Animation only on damage roll option doesn't seem to be working with Better Rolls as of right now. It works perfectly fine when deactivating Better Rolls and when Better Roll is active and this option checked, no animations play whatsoever.

Cheers,

Rémi

**Comment by otigon** [comment]
This is a known issue specific to Better Rolls, nothing to be done on my end to fix this unfortunately. If using Better Rolls I would leave that option unchecked.
