### ISSUE TITLE
Persistant effect missing in the default animation array

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#296]
Hello,

FVTT 0.8.9
5e 1.5.5
AA 0.6.67

It appears that the option "Persistant" is missing in the default array configuration for "On token" animations.

On the left, the default configuration and, on the right, the override on an item:
![image](https://user-images.githubusercontent.com/1687854/145877077-bc115cf3-4b0c-4965-bc9e-bb23343be3e1.png)

Also, can a persistant effect use another animation rather than defaulting on the primary animation?

**Comment by otigon** [comment]
Thanks for notifying me on that. I'll get it patched today

**Comment by otigon** [comment]
What do you mean by using another effect?

**Comment by DarKDinDoN** [comment]
Yes ! The persistant animation could be entirely different from the primary animation, don't you think?

**Comment by otigon** [comment]
I think that would require too much reconfiguring and would confuse a lot of people. Each menu is designed with an associated Sequence to play a single animation, with the Source/Target FX menu the only outlier that plays an animation before/after the Primary animation.

I will be adding in the ability to call macros along with the Audio rework. That would allow for some expansion on the existing structure.

Also, the persistent option should be back on that menu as of 0.6.68
