### ISSUE TITLE
Trigger to play animations

### ISSUE THREAD

**Issue by AetherianRPG** [otigon/automated-jb2a-animations#297]
I selected "play animations on roll attack" option for my game. And it is playing on attack rolls as intented. But it is also playing on damage rolls and on damage apply. So I'm getting a triple animation play (one from attacks rolls, another one for damage rolls and the last one from apllying damage).

System: Shadow of the Demon Lord.

**Comment by otigon** [comment]
I'll take a look and see if I can find the problem, someone else had submitted the compatibility update for SOtDL

**Comment by otigon** [comment]
I was able to get it sorted out. I'll have it fixed in tomorrows update

**Comment by otigon** [comment]
should be fixed as of version 1.1.7
