### ISSUE TITLE
System Request: Dungeon Crawl Classics

### ISSUE THREAD

**Issue by justinthejaguar** [otigon/automated-jb2a-animations#298]
Would you be willing to add DCC to the list of systems supported?

**Comment by otigon** [comment]
I took a brief look at this system. For A-A to be able to function, it needs access to the Targets, Source Token, and Item. All flags are stored on the items.

DCC passes the Target list, and Token ID which is good. However there is no reference to the Item in the ``createChatMessage`` hook (Chat Card data). To add support, they would need to pass either the Item or Item ID inside the Chat Message hook data. Without that, there is no reasonable way for A-A to get the data it needs.

You can try issuing a request on their system github/gitlab page, as ask that the Item or ItemID be passed in the chat card data hook.

Outside of that, it appears that the system rolls the attack/damage instantly in one chat card, so there would be no need to differentiate when an certain type of roll is made.

**Comment by justinthejaguar** [comment]
I know this feature is on their to-do list, and I have linked this conversation to an issue bringing the interest to their attention. Thank you for taking a look.
