### ISSUE TITLE
Unlink repeat of VFX from SFX

### ISSUE THREAD

**Issue by SalieriC** [otigon/automated-jb2a-animations#302]
Previously SFX was not repeated with VFX. Now the SFX uses the same repeat value set for the animation which causes some issues for me. Please unlink the two and/or create an additional option to repeat audio.

**Comment by otigon** [comment]
The sounds are now fully linked to the animation to reduce complexity on my end. I'll look at adding a checkbox to decouple the repeats from the defining animation

**Comment by otigon** [comment]
Probably going to have to make this a global module setting to decouple sounds. Otherwise I'd have to rewrite all of my sequences... and that's not going to happen again

**Comment by otigon** [comment]
Feature is active as of 1.1.4 as a Global module setting to Decouple sounds
