### ISSUE TITLE
Combat tracker flickering, this error seems associated (thrown simultaneously) 

### ISSUE THREAD

**Issue by Burrowfield** [otigon/automated-jb2a-animations#303]
![image](https://user-images.githubusercontent.com/1859214/147881640-46bece23-d283-4356-ab26-6642e1d9fb2d.png)

Getting this at combat turn start. Any clue?

System: PF2e (current)
Version: Foundry >9.0

**Comment by otigon** [comment]
I'm not able to replicate this. Do you have a module enabled that does something during combat?

**Comment by otigon** [comment]
You are most likely using some sort of module that adds something in Chat during combat. This is confusing A-A somehow, and I'd need to know the module to replicate and find a fix

**Comment by otigon** [comment]
@Burrowfield any update on the modules you have active? See about

**Comment by otigon** [comment]
Closing issue due to no feedback
