### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Cimeryl** [otigon/automated-jb2a-animations#304]
Hello, 

Can you add the possibility to order Alphabeticaly in the Automatic Recognition

Thank you

**Comment by otigon** [comment]
Thanks for logging this. I'll give it a look and see about having it auto-sort itself whenever you Submit and Close the menu.

**Comment by otigon** [comment]
Feature is active as of 1.1.4. You'll find the Sort Menu button next to the Search Bar at the top of the Autorec menu
