### ISSUE TITLE
Automated Animations not working with spells stored in Magic Items items

### ISSUE THREAD

**Issue by MrZwij** [otigon/automated-jb2a-animations#306]
Template spells stored in Magic Items items don't animate.

When I cast Cone of Cold as a spell from the item Staff of Frost (using the Magic Items mod), it seems to be ignored by A-A. But when I cast the same spell from the character's spellbook, it works great.

**Comment by otigon** [comment]
Fixed as of version 1.1.4 so long as you are using Midi-QOL. I'm still looking for a Core solution

**Comment by Kreals** [comment]
I am currently also having this issue. Not sure if this problem has re-emerged.
