### ISSUE TITLE
Template animations error post 9.241 update

### ISSUE THREAD

**Issue by Melephisance** [otigon/automated-jb2a-animations#309]
My automatic animations for template spells are now not working. 
Oddly, if I pick fireball, and cast, all AA settings are ignored, template is placed, no animation.
I cast it again - now it works properly.
I then cast Lightning bolt - now the Fireball animation occures!
I cast Lightning bolt again, now it works propery.
Now I cast Fireball, this time the Lightning bolt animation occurs!

Error in console:-
entity.js:1972 The Actor5e#useSpell method has been deprecated in favor of Item5e#roll

Hope this helps with a quick fix! :)

**Comment by otigon** [comment]
Known issue due to some changes I made on my end. Should be fixed later today. In the meantime you can backtrack to A-A version 1.1.3

**Comment by otigon** [comment]
Should now be fixed as of version 1.1.6
