### ISSUE TITLE
Request : Compatibility for 3.5SDR

### ISSUE THREAD

**Issue by valhallatoys** [otigon/automated-jb2a-animations#31]
please make it compatible for 3.5SDR

**Comment by otigon** [comment]
I'm not familiar with that system, what is SDR?

**Comment by valhallatoys** [comment]
its the name of the D&D 3.5 module sistem on froundry

**Comment by otigon** [comment]
@valhallatoys D&D 3.5 support is active now, though I haven't officially listed it. I'm having issues with the Animation Tab closing after every update.

**Comment by irbian** [comment]
> @valhallatoys D&D 3.5 support is active now, though I haven't officially listed it. I'm having issues with the Animation Tab closing after every update.

you made my day

**Comment by otigon** [comment]
full compatibility with 3.5 went live as of release 0.4.00 . No more A-A tab. It is now spawned through the A-A button on the top of the Item Sheet
