### ISSUE TITLE
Some animations just aren't working - SWADE

### ISSUE THREAD

**Issue by gravagehulk** [otigon/automated-jb2a-animations#310]
Hey, Otigon. I'm having a weird issue. I'd send a screenshot, but I don't think anything short of a screen record would help.

I have been setting some animations for some of the powers in SWADE. Some work fine. Blast - Fireball -attached to template. Works great. Darkness - Sequencer effect works great.

But then some just don't work. For instance, if I set a Cone (on template) for the "Burst" power, no matter what color or animation I set it to, no animation plays. I see the preview of it, but it never actually plays when I cast the spell. The same goes for some of the Shield (on token) effects. The energy shield (blue) works. But the fire shield, earth, etc do not. 

I have one of the recent versions of the JB2A Patreon sets. I also tried switching to the free version, but I'm seeing the same thing. There are no console errors at all. The animation just never plays.

I'm still on Foundry 0.8.9 (waiting for one module to get updated)
SWADE 0.21.4

**Comment by otigon** [comment]
Thanks for the report. I'll do some testing to try to replicate this weekend.

**Comment by gravagehulk** [comment]
FYI: I tested this in Version 9, build 242, SWADE 0.22.4 and i'm getting the same results.

For instance: Cone Template set to Cone of cold. I see the preview, but the animation doesn't actually kick off when the "Burst" spell is cast. No errors in console.

**Comment by otigon** [comment]
Sorry, I'm not going to be updating SWADE any further. I know nothing about the system and don't know anything about how the items are set-up. If you know someone with Javascript/SWADE System knowledge who would like to help out please send them my way

**Comment by gravagehulk** [comment]
That’s unfortunate. Please don’t make it incompatible in the module list, though. It kind of works and even in its current state, it’s better than nothing.

**Comment by otigon** [comment]
No worries there, I'm not removing it
