### ISSUE TITLE
Feature Request: Symbaroum system

### ISSUE THREAD

**Issue by yjeroen** [otigon/automated-jb2a-animations#312]
Would love support for this system!

If I need to / can help in any way with my limited javascript knowledge, let me know.

**Comment by otigon** [comment]
@yjeroen I took a brief look, and it seems like the system does provide the information A-A needs to run. However, I know nothing about Symbaroum. Can you provide some basic information on this? Such as:

1. I see there are weapons, does the system have separate attack/damage rolls?
2. Are there spells, Area of Effects, templates, etc?
3. 
Any other brief info you can provide about how the system is played would help me make sure I add in the proper stuff

**Comment by otigon** [comment]
On further investigation, it doesn't appear that the system reliably passes the Item ID being used. If you want you can submit a request on the System GitHub page to add the Item, Item UUID, or Item ID to the 'createChatMessage' hook data. That would allow me to add support for the system

**Comment by yjeroen** [comment]
Done, thanks!

https://github.com/pwatson100/symbaroum/issues/453

**Comment by yjeroen** [comment]
@otigon, data-item-id is passed by to the chat, as you can see here:
https://github.com/pwatson100/symbaroum/blob/master/template/chat/combat.html#L17

Or do you mean you expect it in one of these functions?
https://github.com/pwatson100/symbaroum/blob/master/script/common/hooks.js

**Comment by otigon** [comment]
In the first link (from my brief testing), it doesn't always pass the the "data-item-id" in the chat. I'm not sure if this has to do with Hit vs Miss on the action. Not a deal breaker by itself, but that would mean in this instance animations would only play on a success. I'm also uncertain how other items treat this.

With the Item ID not listed in a DIV, I'll have to figure out how to extract it from the <p> section. Core DnD 5e passes the Item ID this way in chat but in a DIV section, and my system can automatically pull it from that.

The other instance is that Token ID doesn't pass if the token isn't selected why using the Item. Again not a deal breaker, but things get a little weird if you have to find the originating token based off an Item ID.

I'll reopen this for now to see if I can extract the Item ID as-is

**Comment by otigon** [comment]
Yeah I can't figure out how to pull the Item ID from the P tags inside HTML. A little outside of my skill set

**Comment by bithir** [comment]
Hi @otigon - one of the devs for Symbaroum. The complexity is a bit different and more subtle with Symbaroum.  Essentially, the player always rolls, i.e. when a player attacks, he rolls attack (as most RPGs), when the player is attacked, they roll defense - the aggressor (npc/monster) do not roll the dice.

At this moment, the item id for attack is the weapon the player uses, but when a player is defending, the item id is their armor.  This can be changed however, for situations we know.

I suspect we would need a more fine-grained interface to have a successful integration.  Something like
- data-source-id
- data-target-id
- data-weapon-id (or potentially keep data-item-id with some changes)

The reason for source-id/target-id, is that the actor id for a roll message is the same for when the player attacks and when they defend.  So, I believe it be quite unique for how to gather data from the chat message.  I'm happy to add in the required fields in to the system.

I'm also open for other suggestions on what suits you best, if you want to have have Support for Symbaroum.

**Comment by otigon** [comment]
Hi @bithir ! 

Thanks for reaching out. I'll take this info to do some testing later this week and see if I can get a handle on it.

For the data, what you mention above ( data-source-id, data-target-id, data-item-id ) should definitely work for A-A. I can take that at the front-end and arrange it as needed to get things running correctly. I think the simplest way (tho I'm not a system dev, I'm just spit-balling) might be to add that information as flags in the chat message?
