### ISSUE TITLE
Teleport bug

### ISSUE THREAD

**Issue by RonaldoBrum** [otigon/automated-jb2a-animations#313]
I'm running foundry V9 with automated animations version 1.1.6 , however the actors are not teleporting or animating teleport spells. I've also been having problems with ranged spells like magic missile

**Comment by otigon** [comment]
What system are you running?

If 5e, make sure you are not using the DAE SRD Misty Step item. I deactivate A-A if that one is being used due to conflicts.

I need more information on what problems you are having with range spells

**Comment by RonaldoBrum** [comment]
- yes, I'm using 5e

- I'm using the misty steps SRD

- when the distance spells, I noticed at first the magic missile is what I noticed

**Comment by otigon** [comment]
Please check for errors in the Console (F12) when this happens. Not much to go on based off the description. If you can grab a screen video and post it in the JB2A discord that would help https://discord.gg/hWWzVm3d

**Comment by otigon** [comment]
closing due to no response
