### ISSUE TITLE
Request: SFX without animation

### ISSUE THREAD

**Issue by SalieriC** [otigon/automated-jb2a-animations#314]
Sound Effects are now tied to the animation directly. This is a problem if items were set up without an animation but with a sound in earlier versions because these now don't play the sfx which was set up. Sometimes there just isn't a fitting animation available.
I'd like to request a feature to play just the sound and no animation and a migration method for items already set up like this.

**Comment by otigon** [comment]
All you need to do is check the Disable Animation box and the Audio button will appear. If a sound was set previously it is stored in the item still
