### ISSUE TITLE
users see animations DM dosent see animations

### ISSUE THREAD

**Issue by Druak** [otigon/automated-jb2a-animations#316]
I couldn't find a discord to ask this question.

the automated animations are working for my players they all can see the animations happen. but as the DM i don't see any of the animations.

**Comment by Druak** [comment]
it was ublock orgin blocking the animiations

**Comment by otigon** [comment]
No worries, thanks for reporting. Here is the JB2A discord where I have a few channels for Automated Animations https://discord.gg/hWWzVm3d

**Comment by otigon** [comment]
resolved, ublock origin culprit
