### ISSUE TITLE
sounds are not playing

### ISSUE THREAD

**Issue by modzy2** [otigon/automated-jb2a-animations#318]
updated foundry to 9.242 and Auto Anim to 1.1.6 and now the sounds are not playing for attacks

**Comment by otigon** [comment]
Check for errors in the console (F12)

**Comment by modzy2** [comment]
No errors.  If i change it from melee to ranged, it plays ok.  Change it back again and it does not play

**Comment by otigon** [comment]
I'm unable to replicate any issues with Sounds, can you verify that the item is populated correctly? Also, are these customized on the item or running from Automatic Recognition window?

**Comment by otigon** [comment]
closing due to no response
