### ISSUE TITLE
Fobidden Lands animations do not play if "Link Actor Data" is checked on token

### ISSUE THREAD

**Issue by bblonski** [otigon/automated-jb2a-animations#319]
The global automated animations will not trigger if "Link Actor Data" is checked on a token. If "Link Actor Data" is unchecked, animations play as expected.

**Comment by otigon** [comment]
I have a few items to look at for Forbidden Lands. I'll try to get to them this week

**Comment by otigon** [comment]
Found the issue. I'll have the fix in with tomorrows release

**Comment by otigon** [comment]
should be fixed as of version 1.1.7
