### ISSUE TITLE
[BUG] Teleport template not working

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#321]
Hello,

FVTT 9.242
AA 1.1.7

When using a teleport animation:
![image](https://user-images.githubusercontent.com/1687854/149254271-df534761-309a-492c-881c-eef15c5d0c61.png)

**Comment by otigon** [comment]
Nevermind, I didn't realize the file I saved those in were not getting packaged with the release. Should be fixed on 1.1.8
