### ISSUE TITLE
Automated Animations/Sequencer PF2E Issue

### ISSUE THREAD

**Issue by Lawlesslisa** [otigon/automated-jb2a-animations#324]
When I go to save my module settings, I get this message from FVTT.

<img width="547" alt="Sequencer" src="https://user-images.githubusercontent.com/94867746/149553528-7e2f6c30-24c1-478a-a061-d7a674f44ad4.png">

I am using the latest Sequencer module, version 2.0.1 and this is in the PF2E system. I believe it is preventing my Automated Animations Module from working.

I originally posted this in the Sequencer Module Issues GitHub and that creator said it was an issue with this Automated Animations Module.  I am using the most current version of Automated Animations, 1.1.8 in PF2E.

**Comment by otigon** [comment]
This is just a deprecation warning and doesn't prevent anything from running in Automated Animations. Are your animations not working? If so, please check the console (F12) for any error messages when you expect an animation

**Comment by Lawlesslisa** [comment]
Here is what I got with F12 in Foundry after doing a melee attack with a glaive, so it should have played but it didn't.

<img width="773" alt="F12 Play Animation Results for Melee Attack" src="https://user-images.githubusercontent.com/94867746/149559178-bf335f86-bf81-4c57-9810-2c949c00e80b.png">

**Comment by otigon** [comment]
Are you hosting Local or on the Forge?

**Comment by Lawlesslisa** [comment]
I am on FoundryServer, not local

**Comment by otigon** [comment]
Thanks for the info, are you on Foundry V9 or V8?

**Comment by otigon** [comment]
I'm working with the Sequencer Dev to get this resolved. Seems to be an issue on the remote servers end
