### ISSUE TITLE
Ray templates don't have "attach to template" option 

### ISSUE THREAD

**Issue by adacosta92** [otigon/automated-jb2a-animations#325]
![image](https://user-images.githubusercontent.com/67127175/149568225-9770507a-0219-4239-9180-e51ccca87637.png)
As above, Ray templates like Gust of Wind should have the option to attach to template

**Comment by otigon** [comment]
This is expected behavior, and the option has only ever been available on Square/Circle types. With Sequencer 2.0 released I'll be taking another look to see if I can make this happen

**Comment by otigon** [comment]
Feature will be added in the 2.0 release this week

**Comment by otigon** [comment]
This feature should be live as of 2.0.0
