### ISSUE TITLE
[BUG] Error on startup

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#326]
Hello,

FVTT 9.242
AA 1.2.0
5e 1.5.7

Here is the console error on startup:
![image](https://user-images.githubusercontent.com/1687854/149602668-861b9e2d-45eb-43d7-8e74-315a8dc4cba5.png)

**Comment by otigon** [comment]
You update quick lol, fix is already out in 1.2.1
