### ISSUE TITLE
Coriolis RPG / Other Year Zero Engine Systems compatibility

### ISSUE THREAD

**Issue by SKYCH1EF** [otigon/automated-jb2a-animations#327]
Is there a way to make this module compatible with any of the Year Zero Engine games like Coriolis, Forbidden Lands, and Mutant Year Zero? Currently I can access the menus and add animations but animations will not play when making an attack roll for any item. I can currently make macros for the animations but would love the animations to play automatically with weapon attack rolls. Thanks in advance! And keep up the great work!

**Comment by otigon** [comment]
It should already be compatible with Forbidden Lands, but I'd have to look at adding support for the others

**Comment by SKYCH1EF** [comment]
That would be awesome! Thank you!

**Comment by otigon** [comment]
I've updated the Readme on the main page to note that I'm no longer adding support for anymore systems. I will add a section on the Wiki page to detail how to add support via a pull request. Sorry for the inconvenience.
