### ISSUE TITLE
OSE Integration System Updated 

### ISSUE THREAD

**Issue by justinthejaguar** [otigon/automated-jb2a-animations#328]
Would you be able to integrate OSE into Automated Animations? I made a request to meet the item ID requirements and the system was updated to meet the requirements in the latest version.

https://github.com/vttred/ose

![D174AD0F-EAC1-4161-873F-BA3D69F958C2](https://user-images.githubusercontent.com/38022481/149765037-b1ce7099-1dfc-4493-b902-a899d14f0fe5.jpeg)

**Comment by otigon** [comment]
Remind me again, is OSE Old School Essentials?

**Comment by otigon** [comment]
I checked briefly, and while they are pushing the Data-item-id in the chat html, it is null. Therefore there is nothing I can do. I've updated the Readme on the main page to note that I'm no longer adding support for anymore systems. I will add a section on the Wiki page to detail how to add support via a pull request. Sorry for the inconvenience.

**Comment by otigon** [comment]
I was looking in the wrong place on this one. I'll get support added in this week

**Comment by anthonyronda** [comment]
Thanks for getting support working!

OSE intends to list supported modules in the near future, and I'm collecting that list now. I noticed that it's not listed on your README yet, but if you don't get around to it no worries. Thanks again!
