### ISSUE TITLE
CSS on animations page doesn't play nice with DarkUI for SFRPG

### ISSUE THREAD

**Issue by TheTailson** [otigon/automated-jb2a-animations#332]
When viewing the animations window on an item while using the SFRPG Dark UI module (https://foundryvtt.com/packages/sfrpg-modern-ui) the window will inherit the text colour, but not the background colour, of the theme. This results in white text against Foundry's parchment-colour background, making it difficult to read.

![darkuiproblems](https://user-images.githubusercontent.com/30989747/150333060-892c379b-5d17-4be7-bec9-59d3aed8f1b3.png)

**Comment by otigon** [comment]
It will be a while before I can get to this. It stems from my entire CSS file and how I had to force override some items as a result of some Systems CSS making the menu unusable
