### ISSUE TITLE
Error thrown on load, isPrivate not defined

### ISSUE THREAD

**Issue by the-real-orson** [otigon/automated-jb2a-animations#333]
Describe the bug
On screen load I get an error, I think the problem is with Autoanimations module

Console Error info:
foundry.js:316 ReferenceError: isPrivate is not defined
[Detected 2 packages: autoanimations, sequencer]
at autoAnimations.js:88:75
at Function._call (foundry.js:294:14)
at Function.call (foundry.js:279:33)
at module.js:35:15

AutoAnimations js that is producing the error:
// Registers Database with Sequencer
Hooks.on("sequencerReady", () => {
let obj01 = moduleIncludes("jb2a_patreon") === true ? JB2APATREONDB : JB2AFREEDB;

Sequencer.Database.registerEntries("autoanimations", obj01, isPrivate = true);
if (game.settings.get("autoanimations", "killAllAnim") === "off") {
    console.log("ANIMATIONS ARE OFF")
    socket.off('module.sequencer')//
    killAllAnimations = true;
}
});

Foundry V9.238
Hosted on Worldmill
System: dnd5e

OS: 
Windows 10
Browser Chrome

**Comment by otigon** [comment]
please update to the latest Automated Animations, you are a version or two behind

**Comment by the-real-orson** [comment]
Sorry, thought I was current but was on 1.1.9, my bad
