### ISSUE TITLE
Odd behaviors with the Thunderwave animation

### ISSUE THREAD

**Issue by SagaTympana** [otigon/automated-jb2a-animations#336]
I'm getting some very weird behavior when trying to attach the Thunderwave template animation to the Shatter spell. Basically, the animation is playing really really small (as seen at the bottom right of the attached image). The scale is set to 1 for both X and Y, and the size is fine when I cast Thunderwave or Thunderclap with the same animation.

Separately from that, it seems that no matter whether I have the animation set to middle, left, or center, it's always playing the bottom-middle loop (this is true of all three of the spells I mentioned).

Additionally, setting the color to "random" seems to cause the animation to fail to play at all.

![image](https://user-images.githubusercontent.com/96776279/150910222-43d555a5-a2d9-4ab0-82c0-c7ec4775463e.png)

**Comment by otigon** [comment]
This will be fixed on the next release. I was routing things incorrectly, so the "5e" Thunderwave (which changes animations based on Template relative location to the Token) will be moved to the Preset menu.

**Comment by otigon** [comment]
This should be fixed on the current release
