### ISSUE TITLE
FR:  Allow configuration of Miss animation on Misses and Hit animation on Damage for DnD5e

### ISSUE THREAD

**Issue by robnmeyer** [otigon/automated-jb2a-animations#338]
Summary:  Allow to configure animation on misses, but when hit, play animation on damage.   Also allow critical hit and miss animation to play even if configured to play animation on damage.   For example, one such configuration could be as follows - misses are played on the missed attack roll (including the critical miss animation), and critical hit animation is played on a hit but the actual fun animation is played when the damage is rolled.

Further info.
Midi can be used in a light fashion way for combat automation and still provide a lot of value (DFred's CE automation, integration with AA animations, etc).  Many folks do not fast forward rolls.  In these cases, rolls for Attacking and Damage are two distinct steps.  Right now, the only configuration options available in AA are:

1. Playing all animation on the Attack Roll.  This is great for misses, but somewhat anticlimactic for Hits since the splatter and skull overlay can happen 10 - 30 seconds later when the player rolls the damage and the Hit animation has long finished.
2. Playing all animations on the Damage Roll.  In this case, animations for a Miss won't play since the player never rolls the damage dice.  But, having the hit animation tied in with Splatter and the Skull icon and all that stuff is fun and pretty dramatic.

**Comment by magiccuboid** [comment]
I second this request! Sometimes the spell animation can be missed when the spell hits since the player's attention is drawn to the roll damage popup. It'd be nice for AA to wait until damage is rolled on hits, but still show the miss animation on misses.

**Comment by otigon** [comment]
Sorry, the amount of work required to implement something this in depth is not something I will be undertaking
