### ISSUE TITLE
Star Wars FFG Automated Animation didn't work

### ISSUE THREAD

**Issue by Thorshko** [otigon/automated-jb2a-animations#340]
Hi :) . About our talk, it could be nice to see why automated animation didn't work. I guess it's because the particular system of Star Wars FFG. 
Indeed, it uses some dice with particular symbols on it : A green die (8 faces) called "ability die" with symbols : advantage, success, nothing. A Yellow die (12 faces) symbols : advantage, success, nothing or Triumph. Triumph generate the Triumph effect, like a critical succeed and a success automatically. The yellow die is called "proficiency die" and these two kind of dice are used with a number equal to your caracteristic and skill lvl to simulate your dice pool, the yellow die is an upgrade of the green die.

    They are opposed to a number of purple dice (8 faces), called "difficulty die", to simulate difficulty (1 for easy, 2 for average, etc... until 5 or 6), with symbols : threat (or disadvantage and cancelling an advantage symbol), failure (opposed and cancelling to a success symbol), or nothing. It could have one red die or several red dice (12 faces) called "challenge die" or several purple dice in function of the test. A red die is due to a skilled opponent usually and it is an upgrade of the purple die. The symbols on the red die are :  threat, failure, nothing or disaster (disaster is like an critical failure with an automatic failure added and the disaster naturally opposed and cancelling a Triumph).

   A white die (12 faces) is used too apart or with these dices to simulate the Force. The White die, called the "Force die" generates on 5 faces, 1 or 2 light points of Force and on 7 faces 1 or 2 dark points of Force. With these points, a force sensible could use a Power of the Force for pure use (Move an object for example) or to boost an actual skill (like athletics). Sorry if i bored you a little, i finished my explaination ^^. 

   So, i think the principal problem here is the system of Star Wars FFG. In the chat, it displays the fact, the test is succeed or not. To succeed your test, you need to have more succes symbols than failure symbols knowing the fact each success cancelling each failure and vice-versa. The advantage and threat symbols works the same way, and it is the same for triumph and disaster symbols. The advantage and threat symbols allow the GM to enhance the narration or boost some effects : movement bonus, boost an ally, etc... . 
Is it possible to modify the ... hum... macro ? To apply it with the particular symbols of Star Wars FFG ? I guess it didn't work because of that. An other module, FFG Star War Enhancements use JB2A and some sounds to automatically apply a type of animation and sound to a category of weapon (like light weapons, heavy weapons, lightsaber, etc...). BUT, you can't customize them. It works, its pretty fine but it's pretty sad to see a rocket laucher doing "pew pew pew" ah ah :).

**Comment by otigon** [comment]
support for Star Wars FFG should be active now
