### ISSUE TITLE
Midi-QOLI (Midi-Quality of Life Improvments) feature for Warhammer FRPG 4th edition

### ISSUE THREAD

**Issue by Thorshko** [otigon/automated-jb2a-animations#341]
Hi again, so about our talk, it could be nice to have a missing animation integrate to Warhammer just like for DnD 5e. A huge thanks to you, for your hard work. Continue like that you gained me in supporter for your Patreon ^^.

**Comment by otigon** [comment]
not going to be implementing this feature
