### ISSUE TITLE
Better Rolls for 5e causing Magic Missile to not play.

### ISSUE THREAD

**Issue by mooseable** [otigon/automated-jb2a-animations#343]
I'm running Better Rolls for 5e 1.7.1 and Automated Animations 1.3.0

Because better rolls auto-rolls damage when there's no attack roll, it doesn't trigger Automated Animations to play the effect for spells like Magic Missile. Changing magic missile to a ranged attack (requiring a roll) or disabling Better Rolls so you have to press a button to roll damage plays the animation properly.

**Comment by otigon** [comment]
Better Rolls is not currently being working on for Foundry V9 and afaik is only in a maintenance period. BR has always had issues with compatibility with A-A. Unfortunately I won't be updating anything to support BR until I hear that it is being fully maintained for current Foundry
