### ISSUE TITLE
Issue: Starfinder spells throwing error

### ISSUE THREAD

**Issue by ILikeCoolThings** [otigon/automated-jb2a-animations#346]
Posted this in the troubleshooting discord, but making it official for tracking.

System: Starfinder

Issue: Spell casts throw errors when configured for Auto animations. This happens when configured for an animation or macro. Ranged and melee animations work fine.

Error:
![image](https://user-images.githubusercontent.com/54457140/152693736-4cef2712-9b91-4521-924f-b8543a29b558.png)

Macro:
for(let target of targets){       
    new Sequence()
    .effect()
        .file("jb2a.shatter.purple")
        .atLocation(target)
    .play()
};

Let me know if you need any more info!

**Comment by otigon** [comment]
Pretty sure I have this one sorted. This was a workflow I hadn't touched for quite some time and it was.... messy to say the least. I'll be releasing an update to day with this fix in it

**Comment by ILikeCoolThings** [comment]
Cool. If you want, I'll look for an update tonight and can let you know if I run into any more issues

**Comment by otigon** [comment]
"Should" be fixed as of version 2.0.2. Let me know if you notice any further strange behavior
