### ISSUE TITLE
PF2E - Magic Missile doesn't play animation if animations from damage rolls only is off.

### ISSUE THREAD

**Issue by Joshmvii7** [otigon/automated-jb2a-animations#347]
Magic Missile will play animations on damage roll if animations from damage rolls only is on. But if that setting is off, presumably because it has no attack roll/save/area template it won't play an animation on anything, chat card insertion or damage.

**Comment by otigon** [comment]
Are you on the latest version of A-A v2.0.1?

**Comment by Joshmvii7** [comment]
Yes, this is 2.0.1. I know it's in the issue title, but this is Pathfinder 2E, in case that matters. I know I saw another magic missile related issue reported for 5E.

**Comment by Joshmvii7** [comment]
Oh, thanks. Sorry, I didn't realize without that checked it should still play on damage. My friend was trying to attach a macro that casts the magic missile spell (and handles how many missiles, etc.) to the animation, and so he was having to roll damage to get the macro to run and we were looking for a different way since the macro itself rolls damage.

This issue can be closed, apologies.

**Comment by otigon** [comment]
If this macro is being used in A-A, you can run it with the animation disabled and put in the effect Sequence in the macro itself. If you're not familiar check out the Sequencer GitHub for some info, or you can ping me on the JB2A discord channel and we can get ya started

**Comment by otigon** [comment]
going to close this. I created #349 to look at adding that new option into how to play the macros
