### ISSUE TITLE
Feature request: expand import options.

### ISSUE THREAD

**Issue by Iankid** [otigon/automated-jb2a-animations#350]
I would like to be able for me and other users of this module to be able to share our animations with each other.
However the current import option replaces all existing ones.
So we are looking for an import option that is additive to the list, rather then replacing,

**Comment by otigon** [comment]
not going to be adding this functionality

**Comment by otigon** [comment]
For the upcoming 3.0 update I was able to implement a Menu Merge feature that will be additive in nature. Reopening this issue

**Comment by otigon** [comment]
Feature is active for Merging menus as of version 3.0.0
