### ISSUE TITLE
[BUG - 5e] Animation not played upon item destroyed

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#351]
Hello,

When using the last of a consumable item and if that item has charges and "Destroy on empty" activated, the item gets destroyed on use.

![image](https://user-images.githubusercontent.com/1687854/153413643-4549a1d7-071b-4703-b2ad-bdb364a1bfc9.png)

Upon use, no animation is played in this case.
I think this is because the item no longer exists on the sheet.
And apparently, the 5e system embed the item data in the chat card when the item gets destroyed, so that should be retrievable.

**Comment by otigon** [comment]
This is a known issue. By the time A-A gets the data it needs to get the item it no longer exists. I've not found a proper work-around to fix this

**Comment by DarKDinDoN** [comment]
Core 5e :)
Only when the item is destroyed and in the dnd5e flags.

**Comment by otigon** [comment]
Ah good deal, thanks for the info as I didn't know it did that. I'll see if I can use that to fix the destroyed item issue

**Comment by otigon** [comment]
Heck now I want to put a request in to 5e to store the item there all the time, make my life easier haha

**Comment by DarKDinDoN** [comment]
Not sure if they are willing to do that. It sounds like putting weight on the chat message data when it's not useful.

**Comment by DarKDinDoN** [comment]
@otigon you are testing with the latest 5e system?
The item data is stored in the chat card data. `itemData` if I'm not mistaken.
