### ISSUE TITLE
Minor issue with midi-qol

### ISSUE THREAD

**Issue by nulmas** [otigon/automated-jb2a-animations#357]
I may be missing something, but I've been messing with the settings of both modules and can't figure out a solution. I've only tested this with Shield, but I suspect it may also be an issue with other spells.

In a scenario where the DM wants to apply the effects themselves (or if a player forgot to target themselves before casting), Shield's animation will play both when the spell is cast and when the effect is activated.

This by itself isn't much of a problem, but if the animation is changed to persistent it becomes one. I've managed to figure out two workarounds, using sequencer to delete one of the animations or using Convenient Effects to set the effect (after creating a custom shield without that modules animation), but I was wondering if I was missing something or if this could be somehow fixed. I'm also posting this at midi-qol's [gitlab](https://gitlab.com/tposney/midi-qol/-/issues/702).

Thanks in advance!

**Comment by otigon** [comment]
How is the item set up for animation, menu, type, etc? Need more info to pinpoint what is happening

**Comment by otigon** [comment]
If this is using the Shield spell preset in the Autorec menu, then the duplicate animations when set to Persistent is on my end. I'll provide a fix in the next update

**Comment by nulmas** [comment]
Thank you!

**Comment by otigon** [comment]
This one fell through the cracks, but is now fixed as of version 2.5.7. In addition, one of the next major releases will include support in 5e for Active Effects, so this type of animation (when set to persistent) will be automatically deleted if defined on an active effect
