### ISSUE TITLE
Range calculation not working properly for the SWADE system

### ISSUE THREAD

**Issue by Pubmaster32** [otigon/automated-jb2a-animations#358]
When I have the dagger animation set up with the automatic range switch it only plays the "dagger thrown" animation when its 6 squares away (if its 5 or less its just the stab animation that plays next to the attacking token so it doesn't connect), and when I set it to manual range detection and set the "Grid squares for Range Switch" to 2 or 1 or even 0.1 it just plays the stab animation but it slides across the tabletop to the target and looks silly.

The sliding melee attack animation from any range when range is set manually is a recent issue but the animation not switching until more than 5 squares away has been happening since I got foundry and added that module in at the same time back in Jan (seeing a video on this module is actually what made me switch from Roll20)

I think what might be happening at least with the automatic setting is it might be set for 5 ft. because of D&D and Pathfinder and because of that here it’s seeing that as 5 full inches. I don't have any clue why it is doing the sliding of the stab animation.

[Edit: Also yes I jumped through all the hoops of only having this module, sequencer, socketlib, and the JB2A module turned on and nothing changes]

**Comment by Pubmaster32** [comment]
> How does SWADE handle distance on the grid?

I am not 100% sure how to answer this but I think the best way is to say, each grid square is 1 inch with no special rules for diagonals like there are in say Pathfinder.

> Also, have you tried setting the Melee-Range switch to "Custom" and the range switch to Manual? This method allows you to set the specific grid squares that will do the Range animation switch.

Yes I have tried switching to custom and had the range switch to manual, like I said above that is what causes the stab animation to slide across the tabletop when more than 5 squares away, rather than the throwing animation. And that happens no matter what I set the number to 1, 2, 0.1, and 10 to name a few

**Comment by otigon** [comment]
I'll have to see if someone else can fix this specifically for SWADE. I can never get the system to function properly on my end so that eliminates any possibility of me troubleshooting it

**Comment by otigon** [comment]
I "think" I was able to properly fix this for the SWADE system. The update is live now and should work as intended for the Melee-Range switch type attacks
