### ISSUE TITLE
Feature request: Configure Automatic Recognition

### ISSUE THREAD

**Issue by BlackWand1** [otigon/automated-jb2a-animations#359]
Today there is only 1 list and a "global" export/import. Imagine that you could import multiple config files and all applied.
And you could drag and drop them into a specific order - considering that some spells/effects could be duplicates.

You could import "fire spells" from one user that has made a great work, and import "cold spells" from some other. And also along that have your own configurations.

This would improve the way users can share different configs with each other. Since probably no body would have a full complete config.

One more thing - maybe should be separate request. But in many cases maybe multiple different "names" would apply to the same effect. So if one could have a list of "names" that would match, instead of just one.

Cheers

**Comment by BlackWand1** [comment]
Like you would create folders, or groups. You can import/export folders separately. And I could divine my own spells into different folders for each spell level / spell type etc.

**Comment by otigon** [comment]
That's well outside my capabilities sorry

**Comment by BlackWand1** [comment]
If you would add it as a second layer on top of everything. Once you press save - it would save current effects top->down etc to the one config you have today.

Robert Winbladh
________________________________

**Comment by otigon** [comment]
If you have an idea of how to do it you can issue a pull request, otherwise I won't be doing it sorry

**Comment by otigon** [comment]
Do give a little more of a comprehensive answer, some of the things you mention I don't believe are even possible in Foundry. And some that I know might be possible would require such an extensive rework of the Auto-rec Menu Im not willing to do it.

For the multiple fields for the same name, if you need something that extensive for an animation I would recommend using the Macro field for that level of customization. A-A is an entry point, and will not cover super complex animation Sequences
