### ISSUE TITLE
Inline A-A style bleeds to other tabs

### ISSUE THREAD

**Issue by Deuterazamus** [otigon/automated-jb2a-animations#36]
With AA active, open the details of an item, eg a spell:
![image](https://user-images.githubusercontent.com/68236513/115795549-66e8f400-a3d0-11eb-8a8b-10a0a3a1d6ce.png)
all select fields are shown with rounded corners.

Another instance of this style being applied outside its scope is in DAE Duration tab:
![image](https://user-images.githubusercontent.com/68236513/115795865-05755500-a3d1-11eb-936b-addb79610015.png)

Inspecting the DOM it turns out that this style is applied here:
![image](https://user-images.githubusercontent.com/68236513/115795696-b29b9d80-a3d0-11eb-8bf3-a19dbc9dd021.png)

The source of the style is:
https://github.com/otigon/automated-jb2a-animations/blob/22a7b77c4ae1abec0b0e6c4ce5045abb232ce1f2/src/templates/animatetab.html#L5

Deactivating AA returns the item and DAE pages to their normal aspect

**Comment by otigon** [comment]
Thanks, I suspect I need to contain my CSS to only my module. I'll roll back those changes for now
