### ISSUE TITLE
AA does not work with Unarmed Attack

### ISSUE THREAD

**Issue by Ghilteras** [otigon/automated-jb2a-animations#360]
All the other animations work fine, but for some reason Unarmed Attack does not work, is this a known issue?

**Comment by otigon** [comment]
Assuming this is with PF2e, the Unarmed Strike is populated on the sheet and not tied to any item. A-A depends on an item to be able to run everything, so the only work-around is for you to create an actual unarmed strike item and attach it to the sheet
