### ISSUE TITLE
Addition of an origin attribute on persistent tiles

### ISSUE THREAD

**Issue by pgervais70** [otigon/automated-jb2a-animations#361]
To be able to cleanup when a spell or effect expires it would be easier if a persistent tile created by an animation has an origin attribute. 
this would allow to filter tiles by the spell/feature uuid and delete when the effect expires. 
There is something similar that already exists on sequencer persistent effects.

**Comment by otigon** [comment]
Will have this added in to the next release. The flag will be:

Tile - data - flags - autoanimations - item UUID

**Comment by pgervais70** [comment]
That will be perfect!
Thanks

**Comment by otigon** [comment]
revising the above so it is more readable:

```js
Tile: {
 data: {
  flags: {
   autoanimations: {
    origin: item.UUID
    },
   },
  },
},
```

**Comment by otigon** [comment]
flag addition is live as of version 2.1.3
