### ISSUE TITLE
Animations not playing when players attack

### ISSUE THREAD

**Issue by Zeezel** [otigon/automated-jb2a-animations#363]
I don't know if this is a real issue or if I'm an idiot, but whenever players make an attack (whether its melee, ranged, or a spell), it will not play an animation. It will play an animation if I, the GM, do it, and the players can see that animation to. The attached video shows what I'm talking about. The right side is the foundry app, signed in to the GM account. The left side is chrome, signed into a test account that is configured the same as the player accounts. Issuing the attack on the GM account plays the animation for both, while issuing the attack on the player account does nothing. This used to work just fine, and I don't recall changing any settings. I believe this started after a recent update. That didn't stop me from combing through the settings of Automated Animations, Midi Qol, and FXMaster to see if I was missing something, but I found nothing. Sorry if this is a dumb post, I'm used to finding solutions on my own, but I don't know what else to do. I made a GitHub account just to submit this. 

https://user-images.githubusercontent.com/100888699/156684089-7e32888b-9830-4cca-8eb0-ce7cd6c14f36.mp4

**Comment by otigon** [comment]
Check your Sequencer settings for Player Permissions level, chances are that you need to lower that for the Players to initiate animations

**Comment by Zeezel** [comment]
Yep, that was it. Guess I am an idiot after all. Thank you very much!
