### ISSUE TITLE
FEATURE REQUEST: Alternate Sounds for Misses

### ISSUE THREAD

**Issue by pesky-wobbit** [otigon/automated-jb2a-animations#365]
Would be a great option!

**Comment by otigon** [comment]
adding comment from Steel_Wind on discord

Suggestion: Given that MidiQOL can properly detect and display a "miss" and a "hit" and AA adjusts accordingly, it would be IDEAL if AA had some way to change the sound FX being played to play a wildcard from "hit" and "miss" SND FX directories. Just add another path box on the AA Recog to draw from one or the other. 

If "Miss" SND FX dir is empty, revert to hit directory so as not to mess up anybody's existing implementations.

**Comment by otigon** [comment]
sorry not going to happen
