### ISSUE TITLE
Animations very sluggish on the Forge (more so than previously)

### ISSUE THREAD

**Issue by KammaKhazi** [otigon/automated-jb2a-animations#367]
Hi, I am running the latest Automated Animations module on Foundry v9 (build 255) hosting on the Forge.
It may well be a forge issue but I noticed lately animations set up via Automated Animations that were previously running ok are now ridiculously slow (like it appears in a minute if your lucky). It seemed to mostly affect custom animations. 
I have attached screenshots of my AA settings in case I'm doing something dumb (these settings worked fine previously).
Kind regards, 
KammaKhazi
![AAPrimaryAnimation](https://user-images.githubusercontent.com/81476445/157435603-d29bc7bc-f145-4270-9a4e-4801d4802df8.jpg)
![AAExtraEffects](https://user-images.githubusercontent.com/81476445/157435627-fac68f73-02ab-4d71-976d-4a5bac87be1d.jpg)

**Comment by otigon** [comment]
This will be an issue solely with the Forge unfortunately, as there isn't any that has changed in A-A to increase that time. When using the JB2A module from the Bazaar, the animations have to be downloaded from there server when they are used. The slow timing "should" only happen on the first use, as by that time it should be cached for the next time, but there isn't anything I can do on my end for that.

All A-A does is build a Sequence from the menu selections and send that to Sequencer to play the animation
