### ISSUE TITLE
[5e] Rectangles templates not working

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#369]
Hello,

When defining any square animation in the default animation array, we get this error after placing the template: 
![image](https://user-images.githubusercontent.com/1687854/157938086-62299e1f-6b6b-44ca-a396-dda2624b8c15.png)

![image](https://user-images.githubusercontent.com/1687854/157939523-69ce660a-e002-4251-bf53-895aa01bea70.png)

**Comment by otigon** [comment]
These work on my test world, have you tried running Find the Culprit to see if another module is interfering?

**Comment by DarKDinDoN** [comment]
@otigon good call! DF template enhancement is the culprit 😸

**Comment by otigon** [comment]
ah gotcha, I'll check on my end to see if there is anything I can do to account for that

**Comment by otigon** [comment]
It looks like it is the "Fix Square Template Rotation" setting that is causing that issue

**Comment by flamewave000** [comment]
I have a fix coming that placates Sequencer's expectation of there being X, Y, Width, and Height properties on the shape. Basically just adding them onto the Polygon object so it doesn't complain.

**Comment by otigon** [comment]
Thanks @flamewave000 for doing that. I'll close this issue now, but will work to add a rotation effect in A-A for when this type of template is being used to align with the rotation it is at
