### ISSUE TITLE
Request: add a global animation override list (similar to Token Magic FX)

### ISSUE THREAD

**Issue by franckflo** [otigon/automated-jb2a-animations#37]
First, thank you for this wonderful module: I added it as a surprise to my players, and they were amazed :). 

Next: it would be nice to be able to override the animations from a central location in the module settings (just like Token Magic FX does for AoE templates), while still having the ability to override each item's animation individually. That would save a lot on configuration time for the GM, but keep flexibility. The individual item's override would override the global configuration override of course.

**Comment by otigon** [comment]
I like the idea of it, though I'll have to peek at TMFX and see how exactly they implement that. I'll definitely add it to the list to look at

**Comment by franckflo** [comment]
Hi Otigon. Is that something you think you will be implementing?

**Comment by otigon** [comment]
Hey, not realistically. I'd have to change too much code and I don't have near enough time
