### ISSUE TITLE
Spirit Guardians

### ISSUE THREAD

**Issue by jbowensii** [otigon/automated-jb2a-animations#370]
Spirit guardians really stutter's during the loop, any idea what I can do to make this better?

**Comment by otigon** [comment]
The animations are essentially videos being played on the canvas. If it is stuttering, you might try a different browser, or make sure you have hardware acceleration enabled in the browser you are currently using

**Comment by otigon** [comment]
closing this issue as it isn't anything to do with A-A specifically
