### ISSUE TITLE
Thunderwave - "could not determine where to play the effect" error message

### ISSUE THREAD

**Issue by rpganalyst** [otigon/automated-jb2a-animations#371]
Hello, I read your last two changelogs, then I logged for test the changes.
I drag an Actor having Thunderwave in his spellbook, then I cast the spell from the Actor's sheet.

Here's the log:
Foundry VTT | Rendering AbilityUseDialog
token-attacher.js:1028 Token Attacher | Tools added.
backend.mjs:306 Foundry VTT | Created ChatMessage with id [vJTREL03tDXWQgxo]
midi-qol.js:33 midi-qol |  DmageRollComplete elapsed 192ms
token-attacher.js:1028 Token Attacher | Tools added.
backend.mjs:306 Foundry VTT | Created MeasuredTemplate with id [fTxlZo9W9ZazNrTN] in parent Scene [1rIMh2gelLnDoLii]
lib.js:403 Uncaught (in promise) Error: Sequencer | Module: Automated Animations | Effect | play - Could not determine where to play the effect!
[Detected 1 package: sequencer]
    at Module.custom_error (lib.js:403:12)
    at Proxy._customError (sequencer.js:182:20)
    at Proxy._expressWarnings (effect.js:846:33)
    at Proxy.run (effect.js:855:14)
    at section.js:169:30
custom_error @ lib.js:403
_customError @ sequencer.js:182
_expressWarnings @ effect.js:846
run @ effect.js:855
(anonymous) @ section.js:169
setTimeout (async)
(anonymous) @ section.js:162
_execute @ section.js:161
await in _execute (async)
play @ sequencer.js:40
await in play (async)
templateAnimation @ templateAnimation.js:206
await in templateAnimation (async)
(anonymous) @ traffic-cop.js:182
_call @ foundry.js:294
callAll @ foundry.js:253
callback @ foundry.js:10095
(anonymous) @ foundry.js:10065
_handleCreateEmbeddedDocuments @ foundry.js:10065
_createEmbeddedDocuments @ foundry.js:9957
await in _createEmbeddedDocuments (async)
create @ backend.mjs:95
await in create (async)
createDocuments @ document.mjs:338
createEmbeddedDocuments @ document.mjs:522
🎁call_wrapped @ libWrapper-wrapper.js:511
createEmbeddedDocuments @ terrain-main.js:55
🎁call_wrapper @ libWrapper-wrapper.js:620
🎁Scene.prototype.createEmbeddedDocuments#0 @ libWrapper-wrapper.js:189
a.lc @ df-templates.ts:59
a.emit @ index.js:202
r.dispatchEvent @ interaction.min.js:8
r.processPointerDown @ interaction.min.js:8
t.recursiveFindHit @ interaction.min.js:8
t.findHit @ interaction.min.js:8
r.processInteractive @ interaction.min.js:8
r.onPointerDown @ interaction.min.js:8
backend.mjs:306 Foundry VTT | Deleted MeasuredTemplate with id [fTxlZo9W9ZazNrTN] in parent Scene [1rIMh2gelLnDoLii]
2lib.js:403 Uncaught (in promise) Error: Sequencer | Module: Automated Animations | Effect | play - Could not determine where to play the effect!
[Detected 1 package: sequencer]
    at Module.custom_error (lib.js:403:12)
    at Proxy._customError (sequencer.js:182:20)
    at Proxy._expressWarnings (effect.js:846:33)
    at Proxy.run (effect.js:855:14)
    at section.js:169:30

Thank you.

**Comment by otigon** [comment]
This is a known issue when using the DF Template Enhancement module and it's "Fix Square Template Rotation" setting is active. No know fix at this time other than disabling that setting

**Comment by rpganalyst** [comment]
Thank you.
