### ISSUE TITLE
[BUG] effect size is grid dependent

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#373]
Hello,

FVTT 9.255
5e 1.5.7
AA 2.1.9

In the last few released, something happened to the effect size. Or maybe I misunderstood how this works.
The size of an "on token" animation depends on the grid size in the scene configuration.

Example with the same spell, the same targets:

100px grid:
![image](https://user-images.githubusercontent.com/1687854/159126159-c7de2511-1036-4ea9-9114-e0197f2c1071.png)

200px grid:
![image](https://user-images.githubusercontent.com/1687854/159126178-2b95cb8a-c545-40ed-9374-fa44cb283652.png)

**Comment by otigon** [comment]
I'll take a look. I need to convert all the animations to be based on GridSize at some point rather than manually doing the coding in A-A

**Comment by otigon** [comment]
as of version 2.5.4 I've changed the Melee and On Token effects to scale based on Grid Size of the scene. This should keep scaling the same between scenes of different grid sizes.

I'll leave this issue open until I can go through and update the "Add on explosions" and Extra Effects types to use Grid Size to scale

**Comment by DarKDinDoN** [comment]
You rock! I confirm that these are working correctly now 👍

**Comment by otigon** [comment]
Sweet, glad it's working. The other ones will require a bit more testing before I get them implemented. Probably another day or two

**Comment by DarKDinDoN** [comment]
Cool! Thx for the good work :)

**Comment by otigon** [comment]
All effects should now be updated to use the current scaling technique as of version 2.5.7
