### ISSUE TITLE
Unable to open AA screen for some spells since recent release

### ISSUE THREAD

**Issue by KammaKhazi** [otigon/automated-jb2a-animations#375]
Hi, since one of the more recent releases I have been unable to bring up the Automated Animations screen for several spells and the animations I had set do not fire. DnD5e, latest foundry release, fully up to date module.
I've attached the json for the character I've been testing if that helps at all....unseen servant, guidance, shape water and toll the dead all wont let me into their configs and non of them show animations. The other 7 spells all work fine, both access to the settings and playing the animations...so it's really peculiar.

[fvtt-Actor-klandar-hellspawn.txt](https://github.com/otigon/automated-jb2a-animations/files/8312652/fvtt-Actor-klandar-hellspawn.txt)

**Comment by otigon** [comment]
@KammaKhazi Thanks for the report, the actor did help. I was able to replicate the issue and find the error. I'll have this fixed in the morning

**Comment by KammaKhazi** [comment]
superb thanks very much for all your hard work, great module.

**Comment by otigon** [comment]
This should be resolved now as of version 2.5.4. Please let me know if you hit any other snags

**Comment by otigon** [comment]
closing as resolved
