### ISSUE TITLE
Persistent type dropdown not working

### ISSUE THREAD

**Issue by matt-duffy** [otigon/automated-jb2a-animations#376]
This was working previously, I think it is something from the last release.  When I try and create a new entry in templates with a persistent effect the dropdown for the type does not render, it still renders for old template entries, and if I deselect "Persistent" on Entangle and then click it again the dropdown appears.  But on Moonbeam here it does not, no matter what template type I select.

![image](https://user-images.githubusercontent.com/6329577/159702256-1a37a229-20c1-4d31-8a49-f2a8f12cb200.png)

I used find the culprit and still had the problem with just these modules enabled:

![image](https://user-images.githubusercontent.com/6329577/159702340-4f5ae6b5-1328-43bb-8e6c-798b028ac508.png)

**Comment by otigon** [comment]
Thanks for the report, it's probably a bug in either my HTML or listeners. I'll take a look today

**Comment by otigon** [comment]
Found the issue. I'll close this out when I push the release in a bit

**Comment by otigon** [comment]
issue should be resolved in version 2.5.6

**Comment by matt-duffy** [comment]
All working, thanks for such a great module!
