### ISSUE TITLE
[BUG] Module Conflict with Conditional Visiblity

### ISSUE THREAD

**Issue by Brimcon** [otigon/automated-jb2a-animations#377]
Repost from here: https://github.com/p4535992/conditional-visibility/issues/21
**Module Version:**
Automated Animations v2.5.6
Conditional Visibility: 0.5.6

**Describe the bug**
With Automated Animations enabled Conditional Visibility prints an error and becomes non-functional.
```js
module.js:44 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'API')
[Detected 1 package: conditional-visibility]
    at setupHooks (module.js:44:34)
    at conditional-visibility.js:41:5
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5528:11)
    at Game._initializeGameView (foundry.js:6510:16)
    at Game._initializeView (foundry.js:6486:21)
    at Game.initialize (foundry.js:5433:16)
```

**To Reproduce**
Enable both Conditional Visibility and Automated Animations alongside their dependancies
Refresh page. Observe Console Error.

**Expected behavior**
No Console Error and functional Conditional Visibility.

**Browser:**
Chrome

**Foundry Version:** 
Version 9.255

**Game System:** 
DnD5e 1.5.7

**Additional context**
[CVTest-1648142888547.log](https://github.com/p4535992/conditional-visibility/files/8344030/CVTest-1648142888547.log)

**Comment by otigon** [comment]
From what I can gather this error is occurring when Conditional Visibility is is registering or doing something with the hooks in their system. I can't see any way that Automated Animations can be interfering with that, but their code is a little over my head. You'll probably have better luck with posting this on their repo
