### ISSUE TITLE
Animation Origin isn't correct with multiple tokens of the same type

### ISSUE THREAD

**Issue by remiverdel** [otigon/automated-jb2a-animations#378]
Hi,

When I have an encounter with let's say 5 bandits, it seems that as a GM when I select the bandit, target the player and fire an arrow, the arrow is not coming from the bandit I select but from a totally different one.

Hope there is a way to fix this issue!

Thx

**Comment by otigon** [comment]
What system is this

**Comment by remiverdel** [comment]
I’m on DnD5e

**Comment by otigon** [comment]
thanks, I'll give it a check

**Comment by otigon** [comment]
Need some more info as I cannot replicate:
DnD 5e version
Foundry version

Are you using any rolling modules like MRE, Midi, or just core 5e?

**Comment by remiverdel** [comment]
Latest DnD and Foundry versions

I’m using Better Rolls 5e and Smart Target maybe one of them is the culprit?

**Comment by otigon** [comment]
Can you try disabling Better Rolls and test?

**Comment by remiverdel** [comment]
Yes. It seems Better Rolls is the culprit.. Would you know where it's coming from?

**Comment by otigon** [comment]
Better Rolls was always troublesome with A-A support. Right now it is considered to be in maintenance mode with no-one really updating it. It is expected that it will become unusable on future Foundry updates. The recommendation would be to find an alternative substitute like MRE, Mars, or even Midi.

**Comment by remiverdel** [comment]
Thanks for the info, didn't know Better Rolls wasn't updated anymore.. I was trying to use Mars Moerill's but it seems a bit laggy especially the "auto roll attack" doesn't work, does it for you? Or would you personally recommend another alternative?

**Comment by otigon** [comment]
Personally I use Midi-QOL. It's mostly for those who want automation, but you can cut it down to a bare-bones use to where it just handles automatic rolling. It has a bunch of default settings you can choose from depending on your level of desired automation.

Nothing will get you the nice visual appeal of Better Rolls tho

**Comment by remiverdel** [comment]
Thanks for the tips, I'll look into Midi QOL and see what I can get from it! Thx

**Comment by otigon** [comment]
No problem, good luck!

**Comment by remiverdel** [comment]
Hi, sorry to come back so soon,

It seems that with midi QOL as a GM animations work but when a player launches an attack, I hear the animation but nothing plays out

**Comment by otigon** [comment]
Double check your Sequencer permissions in that module's setting

**Comment by remiverdel** [comment]
Thx man, I don’t know how I could completely overlook this!
