### ISSUE TITLE
Feature request: allow A-A to call item macros when Item Macros module is activated

### ISSUE THREAD

**Issue by paulohdsc** [otigon/automated-jb2a-animations#379]
As we discussed on Discord, there is an option to disable the Item Macro's automatic execution and use it only for storage purposes, letting other modules make the macro call. Storing macros like this is useful for organizing and sharing purposes.

So I am opening this issue for you to evaluate the possibility and convenience of allowing your module to call macros from the Item Macros module.

If you decide to implement it, it would be nice to add an argument identifying that it is a call coming from A-A, in the same way that Midi QoL does, so that the user can differentiate which part of the code to act on. Something like: `if ( args[0] === "autoanimations" ) {/* do A-A stuff */}`.

**Comment by otigon** [comment]
Thanks for the info on that, I'll definitely take a look

**Comment by otigon** [comment]
Currently testing with this. I have it working, but I'll have to think about whether to require an input in the current A-A Macro Name field for something like ``Item Macro`` so I can split off that part of the workflow to run it

**Comment by otigon** [comment]
Yeah I think I'll match the way Midi is doing it. It looks like you have to input ``ItemMacro`` (Case Sensitive) into the on-use field of items for it to execute it

**Comment by otigon** [comment]
completed with A-A version 4.0.0. Use the word ItemMacro in the macro name field to call Item macros
