### ISSUE TITLE
Request: use JB2A from AWS S3 bucket

### ISSUE THREAD

**Issue by emwhalen** [otigon/automated-jb2a-animations#380]
The storage limitations on my hosting solution make the in-Foundry JB2A Patreon module infeasible (it consumes a large amount of space). I typically upload large assets and libraries to my S3 bucket and pull from there. AA doesn't appear to currently support JB2A being hosted anywhere but within Foundry's path, and I wish I could point AA to the module files in my S3 instead.

**Comment by otigon** [comment]
A-A maintains it's own separate database so the file paths are always set to ``modules.jb2a.....``. I'm not sure what an S3 bucket does tho, does it change the file locations?

**Comment by otigon** [comment]
I can look at adding a setting to override the initial path with a custom one. Have you also tested a Sequencer macro to make sure they play fine thru there?

**Comment by emwhalen** [comment]
Thank you for considering! Yes, I do successfully run Sequencer macros pulling remote files. There are some minor inconveniences, but it is fully functional. I've also reached out to that project on the same subject.

**Comment by otigon** [comment]
Ok cool. Give me a bit to figure out how best to add that setting a switch

**Comment by otigon** [comment]
Just to clarify the file structure before I implement this: 
Here is a snapshot of how the file paths look right now:
![image](https://user-images.githubusercontent.com/73318661/160451055-3a77b66f-d2ab-49d7-b3d7-7e7eb0b87a80.png)

If drawing from an S3 bucket, the only section that would change is ``modules/`` correct? So the new file path in your case would be something like:

``s3bucketLocation/jb2a_patreon/Library/Generic/......`` ?

**Comment by emwhalen** [comment]
Yes, exactly.

**Comment by otigon** [comment]
I should be able to have this released today or tomorrow. The setting will look something like:
![image](https://user-images.githubusercontent.com/73318661/160458122-5849ebba-a6e6-4d38-8a68-0d554eb223c6.png)

So you'll only have to add the S3 bucket path and the A-A database will update accordingly

**Comment by emwhalen** [comment]
You're a god. That's exactly what I need, and it will make a substantial difference in my game.

**Comment by otigon** [comment]
I just pushed this feature on version 2.5.9. Please let me know if anything weird happens with it, as I have no way to test this lol

**Comment by emwhalen** [comment]
It seems to work so far! Fantastic! I'll keep an eye on it for any quirks.

I did notice that having a path specified doesn't suppress the UI warning about the missing modules. It's trivial, but it would be nice if it stopped.

Additionally, the Settings form doesn't mention that the folder must be titled exactly "JB2A_DnD5e". Doing so could save some headache for future users that aren't inclined to check the console.

Many thanks again.

**Comment by otigon** [comment]
Come to think of it now, I'll probably have to change/add something to this. A-A maintains 2 databases, 1 for the Patreon pack and 1 for the Free pack. I only load 1 into the Sequencer Database registry.

I'll have to see how best to determine which one you are using from the S3 bucket

**Comment by otigon** [comment]
What I'll do today is require the S3 input in the module settings to be either:
1. S3Location/JB2A_DnD5e
or
2. S3Location/jb2a_patreon

This will allow me to run a few checks to register the correct database, and will prevent that error from popping up on start-up.

I'll let you know later today when I'm able to release the update

**Comment by otigon** [comment]
Hey @emwhalen I just pushed version 2.6.0 to correct that S3 location setting. New requirement for input will be either
S3Location/jb2a_patreon
or
S3Location/JB2A_DnD5e

The last part is just to let A-A know which internal database to register with Sequencer, and your JB2A package in your S3 bucket should remain as the same file structure, with the overall folder being either JB2A_DnD5e if you are using the Free version, or jb2a_patreon if you are using the Patreon Package.

Sorry for the confusion

**Comment by emwhalen** [comment]
Works great. Feel free to close this one. I can submit any bugs I find as a separate issue.

**Comment by otigon** [comment]
will do, thanks for the feedback
