### ISSUE TITLE
Issue with Active Effect and Auras

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#383]
Hello,

FVTT 9.255
5e 1.5.7
AA 3.0.1

First off, the new Active Effect system is awesome. Thx for that.

While using an active effect animation combined with an aura and Kandashi Active Auras, the module seems to replicate the aura animation on targeted tokens (as well as the source).

Here is an example:
![image](https://user-images.githubusercontent.com/1687854/161994646-1164304d-4c0b-41ab-98f3-9202f37a0bef.png)

The spell in the screenshot is "Spirit Guardians".
The character on the left is the source of the aura.
The character on the right is inside the aura. It is affected by the aura, but also replicates the aura animation, which it shouldn't do in this case.

**Comment by otigon** [comment]
How do you have that Animation set up? A normal animation for the Item, either customized on the item or in the Auto-rec Aura menu would be the way to go, and then a separate animation for the Active Effect, either on item or in the Auto-rec Active Effect menu

**Comment by otigon** [comment]
Or is the Active Effect also getting applied to the Source Token?

**Comment by DarKDinDoN** [comment]
The animation is defined in the Auto-rec "Active Effect" tab.

Yes, I could use two different animations.
But the new active effect system has a super interesting feature: it kills the animation on effect deletion.
And since I'm not using Midi Qol or such, I can't just use the "classic way" or else I have to manually kill the animation with the Sequencer pannel.

**Comment by DarKDinDoN** [comment]
For now, I do the following: I create two effects on the item, one with the Kandashi Active-Aura and the other just for the animation. This way, the animation is not propagated to the others tokens.

**Comment by otigon** [comment]
Hmmm, let me take a look later and see what I can do to alleviate this

**Comment by otigon** [comment]
Can you DM me your Spirit Guardians Active Aura item? Mine doesn't seem to work correctly and I'm trying to test a fix

**Comment by DarKDinDoN** [comment]
Yes, that is what I do for now.
On effect for the aura, another effect for the animation.

**Comment by otigon** [comment]
I'm going to close this one as an incompatibility between A-A and AA
