### ISSUE TITLE
FEATURE REQUEST : Looping sounds for long ambiance spells

### ISSUE THREAD

**Issue by remiverdel** [otigon/automated-jb2a-animations#384]
Hi!

I was wondering if you guys had an idea for allowing to loop sound. For exemple, I use the call of Lightning spell with a 1 minute thunder sound effect and I would love for it to last as long as the spell lasts. Do you guys see in the future a loop checkbox in the sound settings so it can last as long as the template (if linked to template) is on?

Thx for the awesome work!

**Comment by otigon** [comment]
All sounds are played through Sequencer, which afaik uses the Foundry sound system. I'll check to see if it's possible currently to loop sounds
