### ISSUE TITLE
A few Active Effects enhancements

### ISSUE THREAD

**Issue by DarKDinDoN** [otigon/automated-jb2a-animations#385]
Hello,

Once again, great job with the active effect release. I couldn't be more happy with this!

Two things that I think could improve this feature:
- For a linked token (to actor), apply the same persistent sequencer effect to all tokens on all scenes (and remove for all token on effect deletion)
- For linked token with an already defined active effect, start the sequencer effect when a token representing this actor is placed on the canvas (from sidebar, copy/paste, etc.)

**Comment by otigon** [comment]
I could tie in to the Token added onto a scene for the 2nd one to check for Active Effects on the token, and start the Animation. But I think that would have to be a setting on the Active Effect A-A menu (possibly from the Autorec Menu), since I could see an argument also for not wanting that. I'll take a look either way.

For the first one, what's the use case for applying/removing the animation that linked token on all scenes?

**Comment by DarKDinDoN** [comment]
@otigon For the first one, simply having multiple scenes with the same tokens. Especially for PCs.

Example: the party chase an NPC, someone falls on the ground, he is stunned (sequencer effect). The gamemaster ask the rest of the party what they will do. After that, a combat is engaged, the GM activate a new scene for the combat. The stunned PC should have that stunned animation.

**Comment by DarKDinDoN** [comment]
@otigon for the second one, yes a setting would be ok. But I would rather have a general setting for this that activates the feature for all active effects, than per animation (or both)

**Comment by otigon** [comment]
so it's probably not possible to create an animation on linked Tokens across multiple inactive scenes (at least not that I've found). 

However, it is certainly possibly to read the token when placed on a scene and start up animations from Active Effects that are active on the token. I'll look at adding that feature in with a Global setting to do this for Linked, Unlinked, Both or None

**Comment by DarKDinDoN** [comment]
Great! Thank you for investigating the subject :)

About creating an animation across multiple scenes.
I was thinking, maybe we can just hook on scene rendering.
Each time we do that, we iterate through linked tokens on canvas that have effects, creating sequencer effects and deleting old sequencer effects (for previously deleted effects on another scene).

I think that should do it, and since it is scoped to linked tokens with effects, it should not affect performances.

**Comment by DarKDinDoN** [comment]
Hooking into `renderSceneControls` and making sure `game.canvas.scene` exists should do it.

**Comment by otigon** [comment]
> 

That's a good suggestion. I'll take a look at implementing that on Scene Loading. Gotta be careful with that one cause boyo... that could blow up fast lol

**Comment by otigon** [comment]
I was able to get it to create the relevant Effects on a scene load, but I'll have to do some troubleshooting on how to delete effects on tokens for inactive scenes. This way the Animations would be synced for Linked Tokens across scenes. Sequencer should have that ability to end effects on other scenes, but I have to reach out to the Dev to see what I'm doing wrong

**Comment by otigon** [comment]
To properly manage Animations across different scenes (adding them can be handled on my end, but deletion of effects not possible right now), I've logged a feature request with Sequencer to add functionality to existing methods. Namely using ``Sequencer.EffectManager.getEffects()`` and ``Sequencer.EffectManager.endEffects()`` expansion to be able to run those on inactive scenes for animation control

**Comment by otigon** [comment]
Creating the effects on a scene render is easy, that's just checking the tokens for Active Effects that should have an animation, then play them.

What I'm referring to is, say a Linked token is stunned in Scene A, and you move to Scene B. The stunned Active Effect is on that token, so the animation starts. If you remove the Stunned effect in Scene B, the animation ends. However, while the Active Effect and animation are now gone in Scene B, going back to Scene A the token will still have the animation but no Active Effect

**Comment by DarKDinDoN** [comment]
Maybe you can get all the animations attached to a token, then find the corresponding active effect. If you don't find an active effect on the token, the animation should be deleted.

**Comment by otigon** [comment]
been a while since I touched the Branch I was testing this on, but Sequencer just added the ability to apply animations to the Prototype token, so this will help out tremendously. He also added the ability to remove the animations on other scenes. I'll see if I can fit this into the 3.0.0 release

**Comment by otigon** [comment]
completed with A-A version 4.0.0. All persistent effects will be applied to the prototype data for Linked Tokens
