### ISSUE TITLE
Laser Pistol animations not working

### ISSUE THREAD

**Issue by amcvfx** [otigon/automated-jb2a-animations#39]
The ranged weapon Laser Pistol doesn't seem to work as an override or as a default animation on weapons.

**Comment by otigon** [comment]
I'll check it out today and see if anything crazy is going on. Do you have any errors in the console(F12) when using the item?

**Comment by amcvfx** [comment]
I do! I get these errors:
![image](https://user-images.githubusercontent.com/35099081/116788748-4e996900-aaa3-11eb-8010-431a42db624a.png)

**Comment by otigon** [comment]
issue should be resolved on latest update
