### ISSUE TITLE
Feature Request: A hook that allows for changes to animation data before the animation is executed

### ISSUE THREAD

**Issue by Syven88** [otigon/automated-jb2a-animations#392]
For use with spells like Magic Weapon, Flame Arrows, or similar. When the spell is active, the animation is changed to one that more closely resembles the enchantment, and when the spell is no longer active, it returns to its default state.

**Comment by otigon** [comment]
completed with A-A version 4.0.0

The ``aa.preAnimationStart`` Hook contains all the sanitized data prior to beginning the animation
