### ISSUE TITLE
Feature Request:  Repeat option to apply to animation only [or having a persist duration]

### ISSUE THREAD

**Issue by Appak36** [otigon/automated-jb2a-animations#394]
Currently the repeat option repeats both the animation & the linked sound effect.  I'd like to see a way to repeat the animation only (ie I want the animation to play twice, but the sound once).

Alternatively, with the persist option, add a 'persist duration' option - a middle ground to playing once and persisting until manually removed.

**Comment by otigon** [comment]
For sounds, this is already handled in a Global setting named "Decouple Sounds".

**Comment by Appak36** [comment]
Woops, sorry!  Totally missed that in the main settings.
