### ISSUE TITLE
Items don´t trigger Animations when they get used up

### ISSUE THREAD

**Issue by Kurokasa** [otigon/automated-jb2a-animations#396]
Foundry ver. 9 (build 269)
DnD5e ver. 1.5.7
automated-jb2a-animations ver. 3.1.4

Hi, first of all thx for the amazing tool and all the work you do for the community :)
Items that get destroyed on 0 charges don´t trigger their animation once the item gets deleted and, even if it is probably redundant :D, they also don´t delete the template. This happens regardless if its a global setting or saved on the item.
I enabled debugging, but can´t find anything usefull. I get an error but iam not sure it is from AA, but i attached it anyway.

Hope you finde a fix :)

![Screenshot 2022-04-26 205841](https://user-images.githubusercontent.com/102412559/165372826-6520962b-d0ea-4986-a450-4f7ed42b587c.jpg)

**Comment by otigon** [comment]
The problem with items that delete themselves on last use is that there is no longer an Item for A-A to grab. I've never been able to find a workaround for it. Without an Item, A-A exits early
