### ISSUE TITLE
Problem with ActiveEffects

### ISSUE THREAD

**Issue by Teshynil** [otigon/automated-jb2a-animations#397]
When i try to assign the next effect:
OnToken>Spell>Bless>01>Any Color
In the code because there is a intro and a loop animation for the spell, it fails to get the animation.
This may fail with all the animations that have the same structure.

I think if i select persistent should be intro+loop else only intro

Thanks

**Comment by otigon** [comment]
I'll check it out. For Bless specifically however, I would use the Preset Menu -> Bless option. That will play the intro, loop and outro sections

**Comment by Teshynil** [comment]
Yeah for bless is that but i was checking to give a similar effect as the bless animation persistent

**Comment by otigon** [comment]
Ah I gotcha, I do remember running into that before but forgot to fix it. I'll get it patched this weekend

**Comment by otigon** [comment]
should be resolved in v 3.1.7
