### ISSUE TITLE
Errors after updating to 0.1.2

### ISSUE THREAD

**Issue by Deuterazamus** [otigon/automated-jb2a-animations#4]
After updating to 0.1.2 i'm unable to see any animation. Upon using any Item there's this error in console:

autoAnimations.js:223 Uncaught (in promise) TypeError: Cannot read property 'includes' of undefined
    at itemIncludes (autoAnimations.js:223)
    at RevItUp (autoAnimations.js:233)
    at autoAnimations.js:60
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at Workflow._next (workflow.js:627)
itemIncludes @ autoAnimations.js:223
RevItUp @ autoAnimations.js:233
(anonymous) @ autoAnimations.js:60
_call @ foundry.js:2496
callAll @ foundry.js:2456
_next @ workflow.js:627
async function (async)
_next @ workflow.js:623
(anonymous) @ workflow.js:319
setTimeout (async)
next @ workflow.js:319
_next @ workflow.js:608
async function (async)
_next @ workflow.js:607
(anonymous) @ workflow.js:319
setTimeout (async)
next @ workflow.js:319
_next @ workflow.js:589
(anonymous) @ workflow.js:319
setTimeout (async)
next @ workflow.js:319
_next @ workflow.js:551
(anonymous) @ workflow.js:319
setTimeout (async)
next @ workflow.js:319
_next @ workflow.js:523
(anonymous) @ workflow.js:319
setTimeout (async)
next @ workflow.js:319
_next @ workflow.js:443
(anonymous) @ workflow.js:319
setTimeout (async)
next @ workflow.js:319
_next @ workflow.js:380
(anonymous) @ workflow.js:319
setTimeout (async)
next @ workflow.js:319
_next @ workflow.js:376
(anonymous) @ workflow.js:319
setTimeout (async)
next @ workflow.js:319
_next @ workflow.js:373
(anonymous) @ workflow.js:319
setTimeout (async)
next @ workflow.js:319
_next @ workflow.js:338
(anonymous) @ workflow.js:319
setTimeout (async)
next @ workflow.js:319
doItemRoll @ itemhandling.js:355
async function (async)
doItemRoll @ itemhandling.js:310
call_wrapper @ wrapper.js:421
🎁@handler0(CONFIG.Item.entityClass.prototype.roll) @ wrapper.js:133
_onItemRoll @ base.js:681
(anonymous) @ base.js:440
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

These my current module settings:

![image](https://user-images.githubusercontent.com/68236513/110256713-a7182280-7f9a-11eb-837e-0f37f3748ce7.png)

Let me know if you need something else to help you debug (needless to say but prerequisite modules are correctly installed and everything was working fine in previous version)

**Comment by otigon** [comment]
I inadvertently pushed an update that wasn't fully tested. Let me push 0.1.3 and revert back to the previous version scripts. Sorry for the inconvenience

**Comment by otigon** [comment]
Update to 0.1.3 for fix, thanks for reporting
