### ISSUE TITLE
Request: Allow for usage of directional thunderwave template for cone spells

### ISSUE THREAD

**Issue by vanderleitelesjr** [otigon/automated-jb2a-animations#40]
Thunderwave has a directional animation from JB2A that looks like a cone, which plays based on the spell positioning related to the caster, but when you try to use the Thunderwave template for a cone spell, like Orange Thunderwave for Burning Hands, it always sticks to the the circular template.
It would be nice if we could purposefully select the cone template for cone spells.

**Comment by otigon** [comment]
I'll be implementing a Template option that will cover Ray and Cone animations initially, I'll be sure to add the corner Thunderwave Animation in there

**Comment by otigon** [comment]
Thunderwave didn't make the cut in the templates option, but you can use it as a custom animation
