### ISSUE TITLE
Feature Request: Include the option to customize sounds via Override Automatic Settings

### ISSUE THREAD

**Issue by paulohdsc** [otigon/automated-jb2a-animations#401]
Would it be viable to include the option to customize sounds via the Override Automatic Settings menu? I've come across some situations where the only thing I wanted to customize in the animation was the sound.

**Comment by otigon** [comment]
This will be in the next major release

**Comment by otigon** [comment]
completed with A-A version 4.0.0. Please see the changelogs.
