### ISSUE TITLE
Bug? No animations are played

### ISSUE THREAD

**Issue by Cubius** [otigon/automated-jb2a-animations#406]
I've been having some rather peculiar troubles with the module, as animations rather randomly refuse to play.

After setting up a few custom animations just a day ago, now no animations will play anymore. I've activated debug on both Automated Animations and Sequencer and copied (what I think is) the relevant debugger logs although there are neither warnings nor errors.

[aadebug.txt](https://github.com/otigon/automated-jb2a-animations/files/8646036/aadebug.txt)

**Comment by otigon** [comment]
I would suggest first using the Find the Culprit module to see if something somewhere is interfering.

Secondly, are these animations defined in the Automatic Recognition menu, or on the item itself? Or is it just that nothing at all plays?

Also:

Please list your Game System and Version, and versions for A-A , Sequencer, Socketlib

**Comment by Cubius** [comment]
Issue turned out to be tokens need to be placed on the scene for all animations to play. Just casting a spell off of a sheet does not trigger the animation on a template for instance.
