### ISSUE TITLE
[System compatibility request] Tormenta RPG e Império de Jade

### ISSUE THREAD

**Issue by Drackar1** [otigon/automated-jb2a-animations#408]
hello, my friends and I play a lot with the system "Tormenta RPG e Império de Jade", the compatibility with this system would be possible?

https://github.com/mclemente/fvtt-trpg

**Comment by otigon** [comment]
Is this system different from Tormenta 20?

**Comment by Drackar1** [comment]
is the predecessor of tormenta 20.

**Comment by otigon** [comment]
I'll take a look when I have time. In the meantime please see this section of the Wiki to find out if the system passes the required data https://github.com/otigon/automated-jb2a-animations/wiki/Adding-System-Support

**Comment by otigon** [comment]
closing due to no response in over 2 months
