### ISSUE TITLE
[System Compatibility Request] Chronicles of Darkness 2E

### ISSUE THREAD

**Issue by RinVindor** [otigon/automated-jb2a-animations#409]
It would be incredible to have compatibility for CotD 2E.

https://gitlab.com/MarlQ/mta

**Comment by otigon** [comment]
It will be a bit before I can check this, but please see this section of the Wiki to determine if the system passes the required info for A-A https://github.com/otigon/automated-jb2a-animations/wiki/Adding-System-Support

**Comment by otigon** [comment]
closing due to no response in over 2 months
