### ISSUE TITLE
Active Effect animation size should be a scale property based on the grid size of the effect target, not a flat radius

### ISSUE THREAD

**Issue by Elemental-Re** [otigon/automated-jb2a-animations#412]
Animations configured on the Active Effects tab of the Automatic Recognitions settings page currently have a radius property that functions solely based on the grid size that sizes all active effect animations of the same type the same size regardless of their target, causing the same effect to potentially seem over or undersized depending on the target and setting. The animation should instead be based on the size of the target and be modified by a scale value the way On Token effects are.

![image](https://user-images.githubusercontent.com/86752832/168974414-6243a76e-d46f-4df0-bff3-79a6da5c4302.png)

**Comment by otigon** [comment]
There are 3 options when selecting an Active Effect animation. On-Token, Aura and Preset. If you want it scaled based on Token size you use the On Token menu. If you want it sized off grid units via radius use the Aura option.

**Comment by Elemental-Re** [comment]
Right, my mistake, just noticed this now. Closing.
