### ISSUE TITLE
[Bug] Effect scale is based on token image scale instead of grid dimensions

### ISSUE THREAD

**Issue by Elemental-Re** [otigon/automated-jb2a-animations#415]
This is almost certainly related to #373

I noticed that effects are now scaled off the same property that scale's the token's image size. This change seems to originate with commit 66a79686b705924e6dc1ab646835fe63d128b968, which in [src/aa-classes/animation-data.js](https://github.com/otigon/automated-jb2a-animations/commit/66a79686b705924e6dc1ab646835fe63d128b968) included the following change from

`const sourceScale = handler.sourceToken.w;`
to
`const sourceTokenGS = handler.sourceToken.width / canvas.grid.size;`

While this may resolve the issue of the effect scaling improperly on scenes of different grid sizes, from my testing, `token.w` refers simply to a token's size in pixels that it takes up on the grid, while `token.width` multiplies that value by the token scale to show how much size the token's image takes up. changing the calculation from using the `.w` to the `.width` property on the token now causes the effect to have varying sizes between tokens that technically take up the same space on the grid but have tweaked their appearance with the scale property in the token configuration dialog. 

The following image shows three tokens with scales .9, 1.4, and 1.9 from left to right respectively, each with the same effect playing based on an active effect configured using an on token animation with a scale of 1.

![image](https://user-images.githubusercontent.com/86752832/170144964-6673dc6b-0262-4a8a-8173-a58cd8444d98.png)

This looks weird to me, because the effect on the right-most token is so large even though it's a medium character that just uses such a high scale because their token image has their arms held out with a weapon so far from their body, and the token scale property was the only way to get it to look correct. The character's melee attacks are equally oversized, and it does not look correct to me at all.

![image](https://user-images.githubusercontent.com/86752832/170145347-92fea8e5-f344-4e4f-bfa9-317656e319d2.png)

**Comment by otigon** [comment]
I have plans to switch this to using ``token.w`` on the next major release since it could have minor breaking implications. Looking to push that out in a few weeks

**Comment by otigon** [comment]
fix is in place on version 3.2.2

**Comment by otigon** [comment]
reopening due to release issues

**Comment by otigon** [comment]
released on 3.2.8
