### ISSUE TITLE
[BUG] Active Effect animations proc on non-AE triggers (like chat cards)

### ISSUE THREAD

**Issue by MrVauxs** [otigon/automated-jb2a-animations#418]
Pathfinder 2e v.3.10.4
Foundry 9.269
AA 3.2.0

[Imgur Video of Bug](https://i.imgur.com/UmCZAE9.mp4)

**Comment by otigon** [comment]
How should this be handled in PF2e? Sending the item to chat makes A-A think it is being used

**Comment by MrVauxs** [comment]
> How should this be handled in PF2e? Sending the item to chat makes A-A think it is being used

By having Active Effect animations only proc on Active Effects being added to the sheet. You are already doing that without needing a chat card.

Also, this seems to be a related issue: https://github.com/otigon/automated-jb2a-animations/issues/417

**Comment by otigon** [comment]
So there can only be one way to go on this with feats. I either treat them solely as Active Effects, in which case it would only apply the animation when the Effect is applied, or I treat Feats as items and only activate on sending the item to chat.

I can't find anywhere in the PF2e Item data structure where it specifies which Feats have Effects and which don't 

You say they should be Active Effects, and #417 says normal items. I don't see a feasible way to treat it as both.

I'll chew on it a bit

**Comment by otigon** [comment]
I think I found in the data where it shows whether a Feat has an "effect" associated it under ``item.data.data.actions``. Where it is ``null`` if it has no effect, and some value if it does. I should be able to use this to exit out of the workflow when posting a Feat to Chat if it has an effect attached to it, otherwise play any associated animation

**Comment by MrVauxs** [comment]
I'm almost certain you're talking about inherited actions, which should not
work like this and work like regular actions.

pt., 10 cze 2022, 01:30 użytkownik otigon ***@***.***>
napisał:

**Comment by otigon** [comment]
I did a random sampling and the data seems to support my conclusion but I'll give it another check

**Comment by MrVauxs** [comment]
Your assumption is flawed that it would automatically apply the effect.
There is NO way currently in PF2e to automatically apply Effects. Also,
even if there was, your animations would be duplicating themselves anyway.

pt., 10 cze 2022, 14:29 użytkownik otigon ***@***.***>
napisał:

**Comment by MrVauxs** [comment]
To illustrate my point:
[Imgur Link](https://i.imgur.com/j227Yrw.mp4)

**Comment by otigon** [comment]
Well you should 

> 

Nowhere did I say it would be automatically applying the effect bud.
" the assumption would be that if sent to chat you would be applying that effect."

**Comment by otigon** [comment]
> This should be a good middle ground, since if an Effect has an AE tied to it, the assumption would be that if sent to chat you would be applying that effect.
> Your assumption is flawed that it would automatically apply the effect. There is NO way currently in PF2e to automatically apply Effects. Also, even if there was, your animations would be duplicating themselves anyway.

Nowhere did I say that it would be automatically applying the effect bud.
" the assumption would be that if sent to chat you would be applying that effect"

**Comment by MrVauxs** [comment]
> Nowhere did I say that it would be automatically applying the effect bud.
" the assumption would be that if sent to chat you would be applying that effect"

I get that, the issue is that this causes duplication of the effect

**Comment by otigon** [comment]
.... Yes but you are not understanding what I'm saying. Everything I'm talking about is the "Proposed" fixed. I've already done testing with the changes I've made and it is working. You are still describing the problem, whilst I am describing the solution

**Comment by otigon** [comment]
Proposed change is:
1. If the ``Feat`` has an Active type effect associated, it will only play the animation when that Effect is applied to the Token
2. If the ``Feat`` has no Active type effect associated, it will play when a chat card is posted to chat

**Comment by MrVauxs** [comment]
Right, although I am worried that Feats categorized differently than said here might still have effects and cause duplication, we'll see if such bug reports arise in the future (and in which case it'll also be a matter of did AA do it wrong or PF2e categorized it wrong)

**Comment by otigon** [comment]
There is always the possibility of bugs if the data structure isn't consistent within a given system. With so many Feat items in PF2e, the best I can do is a random sampling. But, if something pops up its just a matter of whack-a-mole to get them sorted

**Comment by Ghilteras** [comment]
@MrVauxs can we close this now?

**Comment by MrVauxs** [comment]
The bug doesn't occur anymore, so yes.
