### ISSUE TITLE
[LANG] "damage" word not translated in src/autoAnimations.js

### ISSUE THREAD

**Issue by Tsukyur** [otigon/automated-jb2a-animations#420]
Hi,

There is an issue with the "damage" word not being translated in the 5 occurences of `msg.data.flavor?.toLowerCase().includes("damage")` in the file : `src/autoAnimations.js`

It means that, for some spells, there is no animations triggering, because the french text for "damage" is "dégâts".
Is there a way we could convert it into a variable so we can translate it ?

I replaced it manually inside the file by "dégâts" for the french version, and it works fine with Pathfinder 2e.

Thanks for your work.

**Comment by otigon** [comment]
Thanks for the info, I'll change this to a configurable variable based on the translation files

**Comment by otigon** [comment]
Localization should no longer be needed for this on the latest A-A releases in version 4+
