### ISSUE TITLE
Using a Macro to execute Automated Animations

### ISSUE THREAD

**Issue by mudgw2** [otigon/automated-jb2a-animations#421]
Greetings, I'm attempting to use a macro to use automated animations with twodiesix framework in Foundry VTT.

We have an item (Auto Pistol) defined and setup with A-A automations and triggering the below macro.  Its attempting to do a laser shot and a sound effect.

The macro that gets triggered is:
```
if (game.modules.get("autoanimations")?.active) {
sourceToken = getControlledTraveller().token;
  targets=Array.from(game.user.targets);
  item = game.items.getName("Auto Pistol");
  AutoAnimations.playAnimation(sourceToken, targets, item);
console.log(sourceToken); 
game.twodsix.rollItemMacro("xv6O9MYYTpt4G7ue");
}

function getControlledTraveller() {
  if (game.user?.isGM !== true) {
    const playerId = game.userId;
    if (playerId !== null) {
      const character = game.actors?.filter(a => (a.data.permission[playerId] === CONST.DOCUMENT_PERMISSION_LEVELS.OWNER ) && (a.data.type === "traveller") && !!a.getActiveTokens()[0])[0].data;
      if (character != null) {
        return game.actors?.get(character._id);
      }
    }
  } else {
    // For GM, select actor as the selected traveller token
    if (canvas.tokens?.controlled !== undefined) {
      const selectedToken = canvas.tokens?.controlled.find(ct => ct.actor?.data.type === "traveller");
      if (selectedToken) {
        return (selectedToken.actor);
      }
    }
  }
}
```

However, we keep getting an error in the console:

`TypeError: Cannot read properties of null (reading 'width')
`in animation-data.js: 335

Any suggestions?

**Comment by otigon** [comment]
that is attempting to get the originating Token.width data, does that not exist maybe in the twodiesix system? To check, you can select a token, open the console (F12), and in the console type ``_token`` and see if it has a width parameter

**Comment by mudgw2** [comment]
There were multiple issues since twodiesix dosnt have the proper hooks in place to support this natively like PF1e does.  The solution was to run the below script using the exact name of the weapon in question.

```
const itemName = "Auto Pistol";
const sourceToken = canvas.tokens?.controlled.find(ct => ct.actor?.data.type === "traveller");
const item = sourceToken.actor.items.getName(itemName);
game.twodsix.rollItemMacro(item.id);
if (game.modules.get("autoanimations")?.active) {
  targets=Array.from(game.user.targets);
  await AutoAnimations.playAnimation(sourceToken, targets, item);
}
```

**Comment by otigon** [comment]
Assuming this is resolved
