### ISSUE TITLE
Allow still images/alternative image for templates

### ISSUE THREAD

**Issue by SalieriC** [otigon/automated-jb2a-animations#425]
I'd like to create a puddle of water after placing a template attacked to it. Currently A-A doesn't allow adding still images to templates however. I'd propose to either allow attaching still images using them as the "animation" or adding a new selection to change the image/animation attached to a template after the primary animation concludes.

**Comment by otigon** [comment]
The File Pickers in A-A allow for image/video selections. If you have the animation set to Persistent you should be able to have a still image placed on the canvas. Is this not the case?

**Comment by SalieriC** [comment]
It accepts my webp file but doesn't attack it to the template.

**Comment by otigon** [comment]
I found the issue and will have the fix in the next release. Should be tonight or tomorrow.

If you need it asap you can change line 30 of ``src/animation-functions/templateAnimatino.js`` . Simply change ``true`` to ``false`` in the ``buildFile()`` args

**Comment by SalieriC** [comment]
Just noticed: The same issue also occurs on the target animation under extra effects it seems. It also won't accept webp files. Maybe that's an equally easy fix? =)

**Comment by otigon** [comment]
I'll give it a once over before release.

**Comment by otigon** [comment]
> Just noticed: The same issue also occurs on the target animation under extra effects it seems. It also won't accept webp files. Maybe that's an equally easy fix? =)

Yep it was apparently in use for quite a few places, a remnant from when I used to manually check the Video dimension sizes. Will be corrected for all areas in the release today

**Comment by otigon** [comment]
should be fixed
