### ISSUE TITLE
[Feature Request] Active Effect anims on source only option

### ISSUE THREAD

**Issue by LukasPrism** [otigon/automated-jb2a-animations#427]
Please consider an option for Active Effect animations that prevent them from propagating to other tokens via an aura. So the animation would only proc on the source, the actor that has the originating item that generates the AE.
At the moment if there is an A-A on an aura active effect, the anim will proc on all tokens that receive the active effect from the aura. In some cases this is great, but in other cases you want the A-A to just represent the aura itself.
You *can* put the A-A on the item rather than the AE, but then it doesn’t inherit the properties of the aura (like being suppressed when an actor is unconscious).
Thanks for a brilliant module!

**Comment by LukasPrism** [comment]
Another, probably simpler, option would be to have an checkbox on Aura autorecs to allow the anim to be suppressed when a token is dead or unconscious (which would mirror the ability of active auras).
I was hoping having the A-A on the AE rather than autorec would mean that it would fire automatically when the actor was dragged onto the scene, rather than having to start it manually. But this doesn't appear to be the case anyway?

**Comment by otigon** [comment]
completed with A-A version 4.0.0
