### ISSUE TITLE
Reset Entries

### ISSUE THREAD

**Issue by JuniorSylar** [otigon/automated-jb2a-animations#430]
Is there any way to reset the inputs that already come in the module? I had problems with a translation module and it messed up everything. I tried to uninstall and install the modules but without success.

**Comment by otigon** [comment]
You want to reset the Automatic Recognition menu back to the default settings?

**Comment by JuniorSylar** [comment]
> You want to reset the Automatic Recognition menu back to the default settings?

Exactly

**Comment by otigon** [comment]
Go ahead and run this line in the console (F12):
1. Make sure the Auto-rec menu is closed
2. Refresh after running this command

game.settings.set("autoanimations", "aaAutorec")

**Comment by otigon** [comment]
closing issue
