### ISSUE TITLE
On Token Animation issues in Starfinder

### ISSUE THREAD

**Issue by Iankid** [otigon/automated-jb2a-animations#435]
Currently, there are some unexpected behaviors when using On Token animations with SF Feat items. 
1. With persistent animations, the animation stays active after feat has been disabled. 
2. For some reason, the animation only plays when a new target is selected **After** activating the feat. This is an issue for feats that have multiple targets. Or for feats that do not have a target, such as self affecting.

**Comment by otigon** [comment]
This issue totally fell be the wayside sorry. Is this still present in V10? I've released several major overhauls to the module. If this is still present please log a fresh issue and I'll get it checked out and fixed
