### ISSUE TITLE
[PF2E] Strikes from Rule Elements play animation on both attack and damage

### ISSUE THREAD

**Issue by tyrielv** [otigon/automated-jb2a-animations#436]
This appears to be related to #417. I think this is because the chat item is typically a feat or effect instead of a melee or ranged weapon.

**Comment by tyrielv** [comment]
Also it looks like some rule element strikes aren't playing at all that used to - looking in particular at monk stances.

**Comment by Ghilteras** [comment]
Just tried an Ape Fist (Rule Element that creates a strike on Animal Instinct Barbarian) and the animation still does not play

**Comment by tyrielv** [comment]
This is working now. A note to anyone that has trouble getting autorecognition to work for these: You have to name the auto-recognition setting for the effect that grants the strike, not the label of the strike. For example, use "Ape Animal Instinct" instead of "Ape Fist."

**Comment by otigon** [comment]
Reopening as a recent change broke this. Will require a specific implementation for PF2e, otherwise all active effects pull from the entire Auto-rec menu (this has bad consequences for other systems)

**Comment by Ghilteras** [comment]
Any chance we can fix this for 3.2.100 release?

**Comment by otigon** [comment]
It will be in the next release

**Comment by otigon** [comment]
This is "fixed" now on version 3.2.991
I reverted the previous change that broke it, but made that part PF2e specific so it doesn't wreak havoc with other systems
