### ISSUE TITLE
[Feature request]Play sound regardles of targeting 

### ISSUE THREAD

**Issue by moinen** [otigon/automated-jb2a-animations#440]
If I understand correctly the module can currently either:
a) if there is a selected target play a sequence with a sound
b) if there is no target do nothing
c) if the option of 'disable animation' and 'add sound' are both selected can play sound regardless of a target being present or not

I propose that the sound should play even without a target being present. No animation, just sound. That way it would be more flexible

**Comment by otigon** [comment]
Sorry, no plans to implement anything like this. A-A has reached it's near end of development
