### ISSUE TITLE
[System Compatibility Request] Lancer

### ISSUE THREAD

**Issue by Z3nner** [otigon/automated-jb2a-animations#445]
Hi, I would be interested in using AA to make the VFX/SFX module I created (Lancer Weapon FX (really more of a compendium than a module.)) work seemlessly with attack rolls in the Lancer system.

**Comment by otigon** [comment]
Without knowing the system at all, does the system provide any reference to the Item that is being used? I took a brief look and it doesn't look like there are any system hooks provided, so A-A would have to monitor the ``createChatMessage`` hook. However, looking in there I can't find any reference to the item or item-id.

A-A requires at a minimum the Item being used to run correctly

**Comment by otigon** [comment]
Closing due to no response

**Comment by Z3nner** [comment]
Hi,
Sorry for my lack of response, I got some help from someone who knows what they are doing (I do not. I'm generally clueless in this field) and ended up working my already existing module to do what I want. But I think Automated Animations would still be useful for the Lancer system.
Here is a link to my repo which, I think, would contain everything you need to add support.

https://github.com/Z3nner/lancer-weapon-fx
