### ISSUE TITLE
Feature Request: Randomized Animation Hit Radius on target token.

### ISSUE THREAD

**Issue by Icarus-Mods** [otigon/automated-jb2a-animations#447]
Hey, as requested I'm making a GitHub ticket for this suggestion. Original Suggestion was as follows:

Would it be possible to include the ability to have an animation not always hit the same area on a target token? But perhaps have like a randomized radius. 

This would be especially neat when using rapid fire weapons for example.

**Comment by otigon** [comment]
Added a Random Offset option for Range menus under the Primary Animation section to help with this. Active on A-A version 4.0.11
