### ISSUE TITLE
[ Feature Request ] Decouple audio on per item basis

### ISSUE THREAD

**Issue by Nachtrose** [otigon/automated-jb2a-animations#448]
Would it be possible add a "Decouple audio" checkbox to each item/setting? Sometimes you just need mix and match repeats depending on the files at hand.

Thanks.

**Comment by SalieriC** [comment]
I'd love that but last time it was denied unfortunately: #302

**Comment by otigon** [comment]
Sorry no plans to implement this on a per item basis
