### ISSUE TITLE
Request: Only display animations that you have the animations for

### ISSUE THREAD

**Issue by JLtheking2** [otigon/automated-jb2a-animations#45]
First of all, great work on the awesome module! Me and my players love it!

My request is that I wonder if its possible to have the module index the animations you have in the JB2A_patreon module, and only display the options for animations that you have. For example, if you have not updated the JB2A_patreon pack, but this module adds support for additional animations, those new animations will show up as options but the animations will of course not play, not unless you update the pack to add the new extra animations.

Having to try out animations only to have them not work gets pretty tiring. And I can only see this issue compounding the more time goes on. This would be a great feature to have to avoid players getting frustrated with options they cannot pick. 

Thank you :)

**Comment by otigon** [comment]
I'll take a look, but realistically I wouldn't see it happening. At a dollar and change per month to update the JB2A package that's pretty cheap

**Comment by JLtheking2** [comment]
I would think so too, but JB2A just included a "limit" to their $1.50 tier. I cannot update without subscribing at the $4 tier which, for a couple of extra animations per month that I might not even use, is beyond my budget.

**Comment by otigon** [comment]
hmm, I hadn't seen that

**Comment by otigon** [comment]
I did some looking, and I don't think there is any reasonable method for me to accomplish something like this. (Open to ideas). I think the best thing to do would be to only update Automated Animations when you update JB2A.
