### ISSUE TITLE
automated animations not working with 3D canvas

### ISSUE THREAD

**Issue by Kalenore69** [otigon/automated-jb2a-animations#452]
I was tweaking around with automated animations and 3D canvas and I'm not sure exactly how to get it to work, changed it to 3D mode and everything

**Comment by otigon** [comment]
It has to be on 3D mode, and you'll still have to target tokens as normal

**Comment by Kalenore69** [comment]
![image](https://user-images.githubusercontent.com/65742168/180349205-e433a0f3-8e10-4cef-ae83-36e9d48d2bfb.png)

These settings don't yield anything still, targeting a user and everything, it works fine with item macros set up, but automated animations tools make it a lot quicker to do.

**Comment by otigon** [comment]
Do you have any red errors showing in the console (F12) when you expect the animation to play? I dont' have any issues on my end

**Comment by otigon** [comment]
closing due to no response
