### ISSUE TITLE
[BUG] Can't open menu for Active Effects

### ISSUE THREAD

**Issue by kevindwitama** [otigon/automated-jb2a-animations#453]
Trying to open the A-A menu to customize individual effects gives the following error in the browser console:

```
Foundry VTT | Rendering AAActiveEffectMenu
foundry.js:319 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Function._getAllTheNamesAefx (autorecFunctions.js:126)
    at Function._checkAutoRecAefx (autorecFunctions.js:262)
    at AAActiveEffectMenu.getData (activeEffectApp.js:50)
    at AAActiveEffectMenu._render (foundry.js:3062)
    at AAActiveEffectMenu._render (foundry.js:3764)
    at AAActiveEffectMenu.render (foundry.js:3021)
    at HTMLAnchorElement.<anonymous> (autoAnimations.js:116)
```

Tested on a fresh world.

Version numbers:
FoundryVTT V9.269
DnD5e 1.6.3
Automated Animations 3.2.93
JB2A Patreon 0.4.5
Sequences 2.1.8
socketlib 1.0.10

**Comment by otigon** [comment]
Hmm, Is this the Automatic Recognition Menu, Active Effect or Item?

**Comment by otigon** [comment]
More specifically, some steps for replicating the error as I don't have any issues on my fresh test world

**Comment by kevindwitama** [comment]
Steps to reproduce:
1. Create a new world with the above modules enabled.
2. Login as a game master
3. Create a new user with the player role
4. Create a new actor and set ownership to the new player
5. Log out as GM, log in as player
6. Open the actor's character sheet, go to the Effects tab and add a new Temporary Effect
7. Edit the newly added effect and try to open the A-A menu (which fails)
8. Log out as player and log back in as GM, repeating 6-7, also failes.

I also forgot to mention that this was tested on Chrome 103, Firefox 102, and latest FVTT app on Windows 10 21H2.

**Comment by otigon** [comment]
Thanks, I'll give it a check soon

**Comment by otigon** [comment]
Ok I think this is occurring because you don't have any Active Effect fields set in your Automatic Recognition menu. I'll fix this on my end this week, but in the meantime you should be able to just add a field in the Autorec Menu - Active Effects tab and it should clear things up.

![image](https://user-images.githubusercontent.com/73318661/180653595-99a79735-64e8-4e1a-b136-e8623edc583b.png)

**Comment by kevindwitama** [comment]
just tested the workaround and now it works! thanks

**Comment by otigon** [comment]
Bug should be fixed as of version 3.2.94

**Comment by kevindwitama** [comment]
hmm, looks like a new issue popped up. changing the settings in the menu that pops up seems to delete all effects. I've attached a video showing the issue.

[2022-07-27 14-02-29-1.webm](https://user-images.githubusercontent.com/10781720/181184293-10db0cfe-c87b-4b94-992d-e5a0b8e415d4.webm)

**Comment by otigon** [comment]
This is a known issue that was brought to my attention. Still trying to find a fix for it, as I don't know why it's doing that. 
The upcoming menu reworks don't have this issue, so I'm stuck with either pasting a warning about the issue, or disabling the active effect menu on items, trying to decide which

**Comment by kevindwitama** [comment]
I personally would have a warning about the issue, I have players who go wild with their customisations lmao

**Comment by otigon** [comment]
That's probably a fair middle ground.
