### ISSUE TITLE
Automated Animations not working with spells stored in Magic Items items

### ISSUE THREAD

**Issue by Reivin800** [otigon/automated-jb2a-animations#455]
Good Day.

I was searching for a fixe for this as i read that it was "Fixed as of version 1.1.4 so long as you are using Midi-QOL. I'm still looking for a Core solution" 

But it has resurfaced on the last update, at least for me.
Its there a fix to this?

Best regards

**Comment by Reivin800** [comment]
Last Update Fixed it.
Im closing this.

**Comment by otigon** [comment]
ah thanks for letting me know. It must have been some of the fixes I put in in the last update or two from some code changes I made
