### ISSUE TITLE
Ground Tiles dont work with custom Links

### ISSUE THREAD

**Issue by Kurokasa** [otigon/automated-jb2a-animations#457]
Foundry v9.269
DnD5e v1.6.3
A-A 3.2.95

Hi thx for the awesome work.
Ground tiles dont seem to work when you have to select them via the custom Option. The tile is created but the File is empty. I tried this in the Automatic Recognition and in the Item Animation.
![Screenshot 2022-07-29 121246](https://user-images.githubusercontent.com/102412559/181737795-174efb56-7c7e-44e1-93f7-a128559f9738.jpg)
![Screenshot 2022-07-29 121216](https://user-images.githubusercontent.com/102412559/181737800-e65d47c8-f111-4d87-9292-b71af5d152cd.jpg)

**Comment by otigon** [comment]
Issue fixed as of version 3.2.96
