### ISSUE TITLE
Feature Request: Support for template animations on temporary items and midi-qol

### ISSUE THREAD

**Issue by pgervais70** [otigon/automated-jb2a-animations#458]
It would be nice to be able to configure auto recognition for template animations on temporary items .
This could be achieved easily with a little modification to dnd5e from getdata-by-system.js
Change this:
```
    static async dnd5e(input, isChat) {
        if (game.modules.get('midi-qol')?.active && !isChat) {
``` 
By this:
```
    static async dnd5e(input, isChat) {
        let midiWorkflowAvailable = false;
        if (game.modules.get('midi-qol')?.active && isChat) {
            const workflowId = getProperty(input, "data.flags.midi-qol.workflowId");
            let workflow = workflowId ? MidiQOL.Workflow.getWorkflow(workflowId) : undefined;
            if (workflow) {
                input = workflow;
                midiWorkflowAvailable = true;
            }
        }
        if (game.modules.get('midi-qol')?.active && !isChat) {
          midiWorkflowAvailable = true;
        }
        if (midiWorkflowAvailable) {
```

**Comment by otigon** [comment]
Thanks for the info. Do you have an example of a temporary item this helps with so I can test on my end?

**Comment by pgervais70** [comment]
I am working on an item macro for Hail of Thorns, and on a hit of ranged weapon attack, I create a temporary item for the Burst effect. Here is my item macro and the my config for the AA template effect.
[hail-of-thorns.zip](https://github.com/otigon/automated-jb2a-animations/files/9221985/hail-of-thorns.zip)

**Comment by otigon** [comment]
can you send me the Item you are using for Hail of Thorns as well? I didn't realize that's not part of the SRD

**Comment by otigon** [comment]
Nevermind on that item request. I was able to verify that it doesn't affect anything else. I wasn't aware of the ``MidiQOL.Workflow.getWorkflow()`` method, that could help me solve some other problems I was having as well. I'll get this pushed out later today with the release I have ready

**Comment by otigon** [comment]
Added in as of version 3.2.96
