### ISSUE TITLE
Custom Presets

### ISSUE THREAD

**Issue by MrVauxs** [otigon/automated-jb2a-animations#461]
Modules could create new Presets, and perhaps even effects, to the Autorec Menu.
It could be a simple JSON that you push into an AA provided function. For each declared variable, it creates an appropriate checkbox, listing, or other pre-defined menu component. Creating custom menus would probably be out of scope of this already ridiculous suggestion.

The components one which can push would probably be listed out on the wiki. Here is a hypothetical example.
```
{
  name: "Rage",
  row: [
    {
      dropdown: [
        {
          id: "tokenBorder",
          title: "Token Border", 
          list: [ ...strings of anything they want ]
        },
        {
          id: "rageEffect",
          title: "Rage Effect", 
          list: [ 
            "could also call on a AA pre-defined list, like Weapons, Spells, Generic, etc.", 
            "it would still be on the module to interpret what to do with it, it would just save time copying all possible effects",
            "would also make it compatible with new releases of JB2A's modules, as AA updates, so do these custom Presets"
          ]
        }
      ],
      "checkmark": [
        {
          id: "persistent",
          title: "Persistent"
        },
        {
          id: "stomp",
          title: "Make a big stomp",
          hint: "Leave a big crack in the ground as you rage?"
        }
      ]
    }
  ],
  function: "pf2eJB2AMacros.RageAnimation(data)"
}
```

Ex. returns `pf2eJB2AMacros.RageAnimation({ name: "Rage", "dropdown": { rageEffect: "smash", tokenBorder: "bloody red" }, checkmark: { persistent: true, stomp: false } })`

**Comment by MrVauxs** [comment]
This particular solution is mainly inspired by Warpgates **[Basic Menu](https://github.com/trioderegion/warpgate/wiki/Basic-Menu)**

**Comment by otigon** [comment]
Given  that the menus are built in Svelte now, there's no way to dynamically push UI updates without having to recompile the entire module, which can't be done. If you have any ideas for additional presets we can look at adding those in.
