### ISSUE TITLE
Present menu doesn't allow custom animation selection.

### ISSUE THREAD

**Issue by Iankid** [otigon/automated-jb2a-animations#464]
Unlike most of the other menus in the autorec menu, Presents doesn't allow custom selected animations.
This would help with situations like #465

**Comment by otigon** [comment]
Presets are very specific to what types of animations they should play with. I've slowly built a few of them out like Fireball and Misty Step to allow more custom ones, but they are done on a case by case basis, and they won't always work with any animation. Think of Presets as custom macros provided by A-A
