### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ducky00** [otigon/automated-jb2a-animations#471]
Playing animations and sound on missed attacked automatically with no need to roll the damage for it

**Comment by MrVauxs** [comment]
That's already how it works, unless you have "Only play animations on damage rolls" enabled.

**Comment by otigon** [comment]
Going to close this one. As MrVauxs pointed out the "Miss" animations are already a thing. I don't plan on providing support for separate "miss" sounds, as this would be highly confusing to implement and use
