### ISSUE TITLE
[Bug]Cannot open Configure Settings with AA enabled

### ISSUE THREAD

**Issue by lucasmiranda2711** [otigon/automated-jb2a-animations#478]
I think the title pretty much explains it.
It seems the new settings for v10 cannot be registered without default values. For example
While trying to register the option "autoanimations.CriticalMissAnimation". It throws an error because the value of the option is null.

**Comment by otigon** [comment]
Thanks for the report, I'll check into it soon

**Comment by otigon** [comment]
Are you doing this with Mid-QOL active?

**Comment by otigon** [comment]
Fixed this in version 3.3.1

**Comment by lucasmiranda2711** [comment]
Hi there, sorry I took so long to answer, fixing confirmed
