### ISSUE TITLE
Automated Animation + Midi-QOL don't works

### ISSUE THREAD

**Issue by arkangel85** [otigon/automated-jb2a-animations#479]
if both "automaed animation" and "Midi-qol" are active the foundry settings page (generic) no longer opens, I can’t help on which of the two modules causes the problem, both if activated by themselves do not cause the problem

![immagine](https://user-images.githubusercontent.com/93746418/188319913-6d2451f0-49f3-47bd-a5c5-a6124d6f6e44.png)

**Comment by otigon** [comment]
You need to update A-A
