### ISSUE TITLE
Request: add support for "Animated Spell Effects: Cartoon"

### ISSUE THREAD

**Issue by Merudo** [otigon/automated-jb2a-animations#48]
There is a collection of over 200 spell effects [available here](https://github.com/jackkerouac/animated-spell-effects-cartoon).

It would be great if these animations could also be automated through your fantastic module.

Although, I understand it might be too difficult or out of the scope of your project.

**Comment by otigon** [comment]
To support that I'd basically have to write and entirely new module. It's simply not possible for me anytime in the near future
