### ISSUE TITLE
Dice Tray

### ISSUE THREAD

**Issue by Deth2442** [otigon/automated-jb2a-animations#481]
Console logs this error when rolling from Dice Tray
![image](https://user-images.githubusercontent.com/112991742/188764243-f31b4228-b65d-4ac6-bfc3-cb3b18abb835.png)

**Comment by otigon** [comment]
Need more info than that. Foundry Version, A-A version?

**Comment by Deth2442** [comment]
Sorry
Foundry V10 (latest stable)
AA V 3.3.14

**Comment by otigon** [comment]
thanks, I'll give it a check for the next release

**Comment by otigon** [comment]
This might be fixed since the V4 release today. I was never able to replicate the error. Going to close this for now. If the error persists please log a new issue
