### ISSUE TITLE
AutoAnimations.playAnimation() + Templates

### ISSUE THREAD

**Issue by MrVauxs** [otigon/automated-jb2a-animations#484]
Add the ability for `AutoAnimations.playAnimation()` to play template animations.

"I'll add it in for V4"

**Comment by otigon** [comment]
for version 4, I restructured the external calls for animations and what options can be passed.

``AutoAnimations.playAnimation()`` will be deprecated in favor of the new ``AutomatedAnimations`` field which has:
``PlayAnimation``
``AutorecManager``

For PlayAnimation, and existing AutoAnimations.playAnimation(), you can set ``reachCheck`` as a number for reach, ``playOnMiss`` as a boolean, ``hitTargets`` as an array or tokens that are hit, and ``templateData`` as either a ``template Document`` or ``template instance``

Those are really the only ones I think are useful other than what A-A compiles. 

Also, the new class ``AutomatedAnimations.AutorecManager``` will have the following exposed fields: 
``exportMenu()`` to export your Autorec menu directly,

``mergeMenus(menu, menus ={})`` which accepts an incoming, exported menu, and an object to tell it specifically which menus to merge such as ``{melee: true, range: true}`` to only merge the Melee and Range menu.

``overwriteMenus(menu})`` which accepts an incoming menu to overwrite on the existing one.

``getAutorec()`` will return an object containing all autorec menus and the version

`` addMetaData(data, options)`` which expects at least an object in place of data, which is the ``metaData`` you wish to set on all Autorec entries as ``entry.metaData``. Options is... optional. By default the ``metaData`` will be set on all entries in all menus. You can pass an Object to options to limit it to select menus such as ``{melee: true, range: true}`` to only place metadata on entries in those menus. Anything requiring more pin-point modifications can be done on the user end with a mix of all these.

**Comment by otigon** [comment]
completed with A-A version 4.0.0. You can pass the template thru External Animation calls using the ``templateData`` field
