### ISSUE TITLE
Wrong Entangle

### ISSUE THREAD

**Issue by Kharmans** [otigon/automated-jb2a-animations#487]
I don't know why but when I use the spell Entangle with the animation Entangle, it came out this way.

![image](https://user-images.githubusercontent.com/112586547/192120623-41c5718b-9562-4f98-b5b6-6f7c1a6b5f39.png)

**Comment by otigon** [comment]
Need more information 
1. Foundry version
2. A-A version
3. Sequencer version

Have you tested with only A-A, Sequencer and Socketlib active. This looks like another module is interfering

**Comment by Kharmans** [comment]
1. Foundry: v10.286
2. A-A: v3.3.16
3. Sequencer: v2.3.7
4. Game System: DnD5e v2.0.3

I tried with only A-A, Sequencer and Socketlib and the result is the same.

![image](https://user-images.githubusercontent.com/112586547/192150431-dc18d3ce-861b-4087-8f1e-13b7e7c1159d.png)

**Comment by otigon** [comment]
You have some some module that is altering your templates. That Template overlay is not Core Foundry nor 5e. 
![image](https://user-images.githubusercontent.com/73318661/192152102-909aadc1-b6b1-4996-aaaf-fff69efdd978.png)

**Comment by otigon** [comment]
All A-A does is pass Sequencer the template object to play the animation on. Whichever module is modifying the core template structure is causing this. This is neither a Sequencer issue nor Automated Animations as far as I can tell

**Comment by Kharmans** [comment]
Makes no sense, the test is with only A-A, Sequencer and Socketlib.

**Comment by otigon** [comment]
> Makes no sense, the test is with only A-A, Sequencer and Socketlib.

Can you screenshot how you have the animation set up?

**Comment by Kharmans** [comment]
> 

![image](https://user-images.githubusercontent.com/112586547/192152343-3663a080-c4fe-495b-9f93-4c1b19da6720.png)

**Comment by Kharmans** [comment]
> Can you screenshot how you have the animation set up?

![image](https://user-images.githubusercontent.com/112586547/192152382-ee7e966b-ec0c-4f13-b21c-c7d483c8c7fb.png)

**Comment by otigon** [comment]
Ok, I can replicate it now.  For some reason the "Below Token" option is causing the rotation. This will be a Sequencer issue, so I'll let that Dev know about it

**Comment by Kharmans** [comment]
Ohhh, ok! In th meantime I'll just choose another option than Attach to Template.

Thanks!

**Comment by otigon** [comment]
completed with A-A version 4.0.0. While this is still an issue with Sequencer, A-A version 4 allows you to adjust the rotation of Template animations. Setting this to 45 will fix this problem
