### ISSUE TITLE
[Enhancement] Animations play depending if the roll succeed or fail in the WFRP4 System.

### ISSUE THREAD

**Issue by danil0man** [otigon/automated-jb2a-animations#488]
In warhammer fantasy some rolls need to succeed or fail. The idea would be that if the (spell) for example fails then it will not display any animation. 
OBS. Things like a spell or a ranged attack are prime to this. But things like weapon attacks are Opposed so it would need to depend. I know I am complicating things but I hope this could be added as a feature

**Comment by Txus5012** [comment]
This already exists for spells, prayers and skills.

**Comment by otigon** [comment]
Going to close this as it does already exist for those as Txus5012 pointed out
