### ISSUE TITLE
System Request: Pathfinder 2E.

### ISSUE THREAD

**Issue by sandersontavares** [otigon/automated-jb2a-animations#49]
Hey! Great work automating 1E, Can i request that some love be shown to 2E, given that it has one of the better foundry integrations out of any system out there?

**Comment by otigon** [comment]
Unfortunately the nature of how they built PF2 makes it nearly impossible to support Automated Animations. I have some ideas for work-arounds, but don't have much time these days to try it out. And tbh the amount of work and technical know-how it needs to get it done is above my head
