### ISSUE TITLE
FVTT v10 SWADE: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'actorId')

### ISSUE THREAD

**Issue by aedgaruk** [otigon/automated-jb2a-animations#490]
Hi,

Since I undertook the FVTT upgrade AA has stopped working and throws this error (see image):

![image](https://user-images.githubusercontent.com/111492074/194147374-36e70db2-df51-4989-9adb-e18864bb5dd2.png)

... Line: 290 ...

![image](https://user-images.githubusercontent.com/111492074/194147694-f2fe6271-aaa1-40a9-8429-c40030c62154.png)

Cheers
Andy

**Comment by otigon** [comment]
completed with A-A version 4.0.0
