### ISSUE TITLE
[Bug] Magic Missile and custom effects do not play animation

### ISSUE THREAD

**Issue by Z8MB1E** [otigon/automated-jb2a-animations#491]
When casting Magic Missile, no animations play, no matter what the settings for it are. This is the Magic Missile preset that ships with this module. The same thing goes for custom animations, although there are still some preset animations, like the Bow, Rapier, etc., that still work. I am afraid to modify them at this point as I feel like they might break.

I get an error in the console anytime I attempt to submit the form:
![image](https://user-images.githubusercontent.com/5430887/194181058-37341cee-2161-489f-bf7d-7f2a3e9f7770.png)

My Foundry version is v10.286 using the DnD5e system v.2.0.3.

Let me know if there's anything else I can provide!

**Comment by otigon** [comment]
Have you tried with only Sequencer, Socketlib and Automated Animations active? And, are you targeting a token and rolling relevant damage?

**Comment by Z8MB1E** [comment]
Yep, I tried it before and just tried it again. It seems that, if those are the only three modules I have enabled, the effects don't work at all. It's like they all just broke.

**Comment by otigon** [comment]
Those are the only 3 modules required for it to work, so something else is going on outside of that. Do any Red errors show in the  console?
Are you on a scene with a grid, etc?
Try pulling the Wizard and another Token out from the SRD Starter Heroes compendium and using the Wizard to cast Magic Missile

**Comment by otigon** [comment]
And what versions are you running for
Sequencer
A-A
SocketLib

**Comment by Z8MB1E** [comment]
I just realized that I actually need those three modules _and_ JB2A's content module. Now, with those four loaded, it seems like it's all working. Unfortunately, adding the rest of the modules in that we use every session seems to cause it to return to a broken state.

**Comment by otigon** [comment]
Well it's one of those modules that's causing the issue. Usually these types of issues are due to a module that affects the rolls/chat output. Are you using Ready Set Roll?

**Comment by Z8MB1E** [comment]
> Are you using Ready Set Roll?

I am... is that what it is? Maybe I glossed over it, but I didn't see a specific mention of RSR in the module description/incompatibilities.

**Comment by otigon** [comment]
RSR isn't compatible with A-A right now. I have a release that will be out in 1-2 weeks that it works with

**Comment by Z8MB1E** [comment]
> RSR isn't compatible with A-A right now. I have a release that will be out in 1-2 weeks that it works with

Awesome, I appreciate that. Thanks for your quick assistance on this. I look forward to that release!!
