### ISSUE TITLE
Active Effects not working in WFRP 4e

### ISSUE THREAD

**Issue by Txus5012** [otigon/automated-jb2a-animations#496]
Since A-A 4.0.0 the active effects animations don't work in the WFRP4e system.

I wrote this simple macro for the Deafened condition:
![Active Effects](https://user-images.githubusercontent.com/87753744/194825979-a59581c8-7ad8-4346-954f-b638aa5f6e3b.jpg)
As you can see, there is an error when activating the condition. It seems to work well when removing the condition.

Tried the same macro in a D&D5e world and worked well.
This worked well in earlier versions of A-A.

**Comment by otigon** [comment]
Thanks for the heads up, I'll get it sorted today

**Comment by otigon** [comment]
Got it sorted out, I'll have an update out later this morning

**Comment by otigon** [comment]
Should be fixed as of version 4.0.03

**Comment by Txus5012** [comment]
That was fast! It's working now. Thanks.
