### ISSUE TITLE
Retest #490: SWADE - AA does not manifest FX or SFX (v4.0.03)

### ISSUE THREAD

**Issue by aedgaruk** [otigon/automated-jb2a-animations#498]
Hi,

I was in the process of raising this ticket in response to the 4.0.02 when I saw your release for vx.03 so I've updated and tested it again without any joy for both versions, I appreciate the x.03 fix was in response to #496 and a different world but thought you'd like to know I'd tried both.

FVTT: 10.287
SWADE: 2.0.5
AA: 4.0.03

In summary: No errors or warnings thrown but also no FX or SFX 

I've tried the following permutations: 
Ranged and Melee
Preconfig (Dagger) (see images)
Custom: Laser Pistol with customised JB2A animations + SFX (.mp3) files ... essentially the same setup as worked in v9x but deleted and re-created.

Suggestions re: something I've missed ... or any other test config's you'd like me to try out?

![image](https://user-images.githubusercontent.com/111492074/194909552-e4ca70dd-a89e-4e89-b750-93e0deb3f98c.png)

![image](https://user-images.githubusercontent.com/111492074/194909666-f4e4977c-8ec0-4d7d-897b-129df48913f2.png)

Cheers
Andy

**Comment by aedgaruk** [comment]
Appreciate the effort ... I'll be gutted if it can't be fixed having played PF2e and had spells and arrows flying about!

BTW Just tried it with/without SWADE Tools to the same effect.

**Comment by otigon** [comment]
Yeah it'll probably take someone issuing a Pull Request to get that fixed. The primary problem is that I have no idea how the system works, and with no "SRD" content I can't get anything to work for rolls, etc. Sorry for the bad news

**Comment by otigon** [comment]
Oooo I got it working with Better Rolls 2 for Swade... maybe I can get it to work with Core SWADE lol

**Comment by otigon** [comment]
So it looks like I got it working when using the Better Rolls 2 for Swade module. No dice on using it without. I'll push this update later today

**Comment by aedgaruk** [comment]
Do you know FloRad ... he's the SWADE system guru, I'm sure he'd know 

I'm asking because SWADE Tools and BR2 are mutually exclusive modules and I like Tools but BR2 is going to be a tough sell to my newbie players ... and me TBH :)

**Comment by otigon** [comment]
I can attempt to fix what's already present, but unless a PR is done I won't be delving further into SWADE sorry

**Comment by aedgaruk** [comment]
I've taken the liberty of forwarding this ticket to FloRad as a prelude to an introduction for you both and he's happy to chat if you're game ... he says to DM him on Discord if you wish.

**Comment by aedgaruk** [comment]
Hi,

Retested it v's BR2 and I concur, it does work ... I've got back my pew-pew noises and animations!!
Additional bonus is it's got me to knuckle down and engage with BR2 and I must say I'm warming to it markedly.

Not sure what you want to do re: this ticket but I'm happy for it to be closed, tho' I suggest a note on the Project URL saying to use BR2 and not SWADE Tools may head off aggro in the future.

Many thanks, you've made this scruffy looking nerf herder happy ;)

Andy

**Comment by aedgaruk** [comment]
OK ... I don't know what is going on! 

As a final retest for my own satisfaction I tested:

BR2 with AA - Works as expected
SWADE System - Works as expected
SWADE Tools with AA -  Works as expected

... I have upgraded FVTT to v10.288 since raising this issue and reinstalled Foundry and recreated my world with fresh installs of every module, including AA + dependencies so wherever the glitch was it's possible been exorcized along the way.

![image](https://user-images.githubusercontent.com/111492074/195343563-76ffe968-09cd-43e2-812a-4c57254a273d.png)

**Comment by otigon** [comment]
Huh... that's interesting to say the least haha. I'll go ahead and close this out. Let me know if anything else pops up. Active Effects should also now be working in SWADE on the latest A-A v 4.0.07
