### ISSUE TITLE
issue perhaps with automated animations?  I don't know enough to be sure, I just can't get AA to work since an upgrade

### ISSUE THREAD

**Issue by nightgauntt** [otigon/automated-jb2a-animations#499]
commons.js:1696 Error: You are accessing the ChatMessage#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1685:19)
    at ChatMessage._logV10CompatibilityWarning (commons.js:6612:14)
    at get data [as data] (commons.js:6512:24)
    at AASystemData.getItem (getdata-by-system.js:669:31)
    at AASystemData.getRequiredData (getdata-by-system.js:593:31)
    at async AASystemData.forbiddenlands (getdata-by-system.js:259:38)
    at async systemData$1.make (system-data.js:12:69)
    at async runStandard (aa-standard.js:23:19)

**Comment by otigon** [comment]
What versions are you running for everything, A-A, Foundry, Forbidden lands?

**Comment by otigon** [comment]
Need more context on the not working part. Did it stop working after updating Automated Animations, after upgrading to Foundry V10, etc

**Comment by nightgauntt** [comment]
sorry had to pick up kids.  And I was hoping the error was enough to help :)  so for context.  The system worked fine about 2 weeks ago on a new AWS server. Stopped working last monday.  Troubleshooted a couple hours then, just got back to it today.   I had free jb2a.  I upgraded to jb2a patreon.  noticed the new version of aa today and upgraded Everything is upgraded:
Foundry10 -286
forbidden lands 10.0.0-4
aa 4.0.0.4
jb2apatreon 0.4.9
sequencer 2.3.8
fxmaster 3.5.0

The new aa seems to recognize correctly, ie a longsword shows melee: longsword and if i create something it shows correctly.  I added sound files to some.  Previews work for all of them in AA.

When i select a target and attack with a weapon, premade, added, with or without sound. nothing happens and the error above shows. 

I have tried find the culprit, but even with just the minimum aa jb2a sequencer, it is not work.  

Like i said, i'm not positive it is even an AA issue, I just thought i'd check if the error code was something that someone had run into

**Comment by otigon** [comment]
I'll give it a check tonight and see if I can find anything

**Comment by otigon** [comment]
I get this pop-up with Forbidden Lands 
<img width="463" alt="image" src="https://user-images.githubusercontent.com/73318661/194971458-600df455-3983-49d3-bd89-554ceb7b9927.png">

Are you sure this is a stable version to use on V10?

**Comment by otigon** [comment]
Either way, can you export an actor and send it to me on Discord? I can't get anything to work in this system

**Comment by nightgauntt** [comment]
I'd be happy to send you an actor, but I can't find your discord.  Please don't spend a lot of time on it, I don't even know if it is a AA issue or a FBL issue.

**Comment by otigon** [comment]
It's no problem for me to check. Discord ID is Otigon#2010

**Comment by otigon** [comment]
Issue should be resolved on latest A-A

**Comment by nightgauntt** [comment]
I checked last night and it was working thanks so much!!


Reuben Lopez
________________________________
