### ISSUE TITLE
Animation on damage not working

### ISSUE THREAD

**Issue by HarryWraith** [otigon/automated-jb2a-animations#5]
Hi. I was checking out your module with a view to becoming a patron to this and jb2a. I want the animation to occur only on damage, but when I check the box the animation is occurring on swing...regardless of hit or damage. This could be user error but I don't see what I'm I'm doing wrong.

![image](https://user-images.githubusercontent.com/59278137/110360421-99b07600-8036-11eb-83ce-137eefe6e8ad.png)

**Comment by otigon** [comment]
1. Are you using Midi-QOL?
2. Did you refresh the server after enabling the option?
3. Are you using any other rolling mods like Better Rolls, Mars, etc

**Comment by HarryWraith** [comment]
Hi. OK so I found two problems. Firstly, I was attacking using the attack macro which I'd dragged and dropped to a macro slot. Secondly, I was using better rolls 5e. Once I disabled this it worked. 

On 8 March 2021 at 18:55, otigon <notifications@github.com> wrote:






Are you using Midi-QOL?
Did you refresh the server after enabling the option?
Are you using any other rolling mods like Better Rolls, Mars, etc

**Comment by otigon** [comment]
Thanks for the information. I'll be adding pure Better Rolls support soon, but hadn't noticed that interaction before so it definitely will help me out. I did a bit of testing with Midi-QOL & Better Rolls and will test this out more later today to see if I can pin down where the fault lies.
