### ISSUE TITLE
SWADE - Active Effects Support

### ISSUE THREAD

**Issue by SalieriC** [otigon/automated-jb2a-animations#504]
The Active Effects animations currently do not seem to work on SWADE.
You can assign me @otigon, I don't know when I'll find time to take a look at it (will probably take a while since I have to deal with my own stuff first), but if no one does it first, I'll try to take a shot at it.

**Comment by otigon** [comment]
I'll take a look and see if I can figure that one out

**Comment by SalieriC** [comment]
Okay cool. If not assign me. I don't know how A-A handles that yet but if it's just a matter of getting the correct hook it's probably an easy one.
Should be `updateActiveEffect` when enabling/disabling an AE and `createActiveEffect` as well as `deleteActiveEffect`. No idea if that helps because I don't know how exactly you handle that but maybe it does. =)

**Comment by otigon** [comment]
I don't think I have them set up for SWADE yet, but if they're using the core Active Effect system it will be easy to implement. Should be able to get it done today without issue

**Comment by SalieriC** [comment]
There is a bit of other stuff attached to AEs in SWADE but the property paths should be as in core I think.

**Comment by otigon** [comment]
Active effects should now be working in SWADE as of version 4.0.07
