### ISSUE TITLE
Deviation Toggle

### ISSUE THREAD

**Issue by Fumblemunky** [otigon/automated-jb2a-animations#506]
A deviation bar where you can type how far, in grid units, the animation/s will randomly deviate. Useful for making rapid fire weapons less laser accurate, creating spread weapons like shotguns and firing multiple arrows simultaneously, and making explosives and AOE spells more organic feeling. Especially useful if having a delay timer of 0 causes animations to fire simultaneously.

**Comment by otigon** [comment]
I've added a "Random Offset" option in the Range menus under the Primary Animation section to randomize the impact location. Active as of version 4.0.11
