### ISSUE TITLE
Animations not showing on spells cast from magic item

### ISSUE THREAD

**Issue by kuchrk24** [otigon/automated-jb2a-animations#508]
Foundry v10.287
Automated Animations v4.0.10
Magic Items v3.0.0
DnD 5e v2.0.3
Browser: Firefox

I apologize in advance because I know there were a couple issues created for this already several months ago, but I am experiencing this issue still. I've tried combing the settings to see if I am missing something but so far nothing has helped. I have a custom spell that I have set up global animation (template) recognition for. If I cast the spell directly from a tokens spell book, the animation shows up in the template just fine. However, if I cast it from a magic item that it is attached to, no animation shows in the template. Any help would be greatly appreciated!

**Comment by otigon** [comment]
Magic Item spells are stored on the item they are applied to rather that then Token/Actor. I'm in the middle of a rework of the main A-A workflow and these work, sort of. Non-AOE spells work just fine so long as you have your token selected prior to using the spell, and AOE spells have to pull from the primary DnD5e SRD Spell compendium to get the item. It will be a few days before this is released

**Comment by kuchrk24** [comment]
Actually it looks like it's not just magic items. Plain old fireball isn't working either. Anyway, thanks for the response. I'll watch for updates and try again.

**Comment by jputman** [comment]
I also noticed that I wasn't able to get a macro to run from the Fireball effect (though the animation was running) but the macro was not triggering. I am adding it as a comment here as it seems that it might fall under the Non-AOE spells work just fine type comment.

**Comment by otigon** [comment]
@kuchrk24 It looks like everything is working fine from my testing after the latest A-A releases when using magic items.
@jputman The macro thing was a separate issue, but should be fixed on now A-A version 4.0.17
