### ISSUE TITLE
Request: Create Tile

### ISSUE THREAD

**Issue by Havoclivekiller** [otigon/automated-jb2a-animations#51]
Create a new tile upon an item (spell, weapon, etc.) usage. Either under the caster, where the template was set or at the target(s), centered. For example, this could be used as an after-effect of a grenade (crater) or another spell that changes the environment. Coupled with an explosion animation, it would be glorious to see a crater after it or blacked terrain (some transparent burnt terrain?).

**Comment by otigon** [comment]
I'm currently looking to switch to Tile placements for all animations rather than relying on FX Master. If this works out I should be able to implement something like this. (Will take time)

**Comment by otigon** [comment]
You can now place Tiles on the canvas via the Templates option for Circular and Square templates as of 0.5.0
