### ISSUE TITLE
Dagger animation sound doesn't play

### ISSUE THREAD

**Issue by tristanvann** [otigon/automated-jb2a-animations#510]
Other animation + sounds seem to work, but specifically any animation set to use Dagger will play the animation but without any sound.

**Comment by otigon** [comment]
weird... what version of A-A are you running

**Comment by tristanvann** [comment]
Version 4.0.07. Foundry v10, build 288

**Comment by otigon** [comment]
Try updating your A-A, current version is 4.0.11. if the issue still occurs please screenshot how the faulty animation is set up and post it here

**Comment by tristanvann** [comment]
Ok I updated and the issue still persisted, so I poked around the animation options so more and noticed that the range switch wasn't set up with sound, so I did that and it worked. Even though the tokens were adjacent to each other on the map. So I experimented a little more and it seems like if the target token is Large-sized or bigger (2x2+ squares), it calculates ranged switch based on the top left square of the target token. So even though the two tokens were adjacent, it was acting as though it was at range, and thus not playing the melee sound.

Bug: Tokens 2x2 squares or larger calculate Range Switch from the top left square of their space, which creates strange behaviors for melee combatants adjacent on other sides.

Expected behavior: A token should play the melee animation if it is within melee range of any side of a target.

**Comment by otigon** [comment]
Ah that makes some more sense, thanks for the break down. I'll take a look at the range checking and see what I can do

**Comment by otigon** [comment]
I'll have a reworked range check in place and released sometime in the next week

**Comment by otigon** [comment]
The reworked range check is live as of A-A version 4.0.15. Should eliminate these issues
