### ISSUE TITLE
Animations broke after update

### ISSUE THREAD

**Issue by Maelorn09** [otigon/automated-jb2a-animations#515]
Hi, after recent update most of my weapon animations both autorecognized and custom don't play with the below error showing error. Here's the scrin from the hand crossbow. The menu is updated.
![image](https://user-images.githubusercontent.com/114569560/197178829-72b255a1-0cd2-49cf-b2e7-632fbb3086b2.png)

**Comment by otigon** [comment]
Is this PF2e?

**Comment by Maelorn09** [comment]
> Is this PF2e?

Right

**Comment by otigon** [comment]
I'll push a hot fix shortly

**Comment by otigon** [comment]
If you update to 4.0.13 this should be fixed

**Comment by Maelorn09** [comment]
> If you update to 4.0.13 this should be fixed

fixed indeed. Thanks
