### ISSUE TITLE
Sequencer Tip showing despite AA tips turned off

### ISSUE THREAD

**Issue by apoapostolov** [otigon/automated-jb2a-animations#518]
AA 4.0.15. I get this all the time:

![image](https://user-images.githubusercontent.com/4083812/197423765-5f04fb3f-ae8f-4838-86a8-08f2073565a6.png)

I already should have turned them off:

![image](https://user-images.githubusercontent.com/4083812/197423779-a31119c8-d0af-4336-8d86-d4d316788243.png)

**Comment by otigon** [comment]
Not sure what you're requesting here. Is the Disable Persistent Effect TIps not working? It works on my end

**Comment by apoapostolov** [comment]
Sorry I wasn't thinking straight when I opened this issue. It all works fine.
