### ISSUE TITLE
[Feature] Ability for mods to provide autorec link to AA

### ISSUE THREAD

**Issue by apoapostolov** [otigon/automated-jb2a-animations#519]
This is mainly for JB2A x PF2 mod that has its own autorec.json file that needs to be fed manually into AA with every update. There could be an approach to make AA remember its last merged file and new contained metadata about versioning and online repo URL, and prompt to update/overwrite itself every X days. Another approach could be local mods could carry their autorec.json files and AA could provide prompt to recognize and suggest an update/overwrite if the versioning has been updated, or a new mod is available to merge.

**Comment by otigon** [comment]
The PF2e Animation Macro module has already implemented a method for you to update on their end to see if anything new needs to be updated/added

**Comment by otigon** [comment]
![image](https://user-images.githubusercontent.com/73318661/197424216-adba7d78-b84e-4555-a91d-80821d5a64f9.png)

**Comment by otigon** [comment]
I worked with the PF2e Animation Macros dev when I released A-A version 4.0.0 to expose the internal Autorec updates in A-A. This way other modules that may pop up like that one will be able to run their own updates if needed. Going to go ahead and close this one out

**Comment by apoapostolov** [comment]
Thanks for pointing this out!
