### ISSUE TITLE
Token disappears after teleporting with Misty Step (DnD5E)

### ISSUE THREAD

**Issue by KJTailor** [otigon/automated-jb2a-animations#521]
As described in the title. When using the Misty Step spell, first the teleportation limits appear as a wide circle, as expected. When clicking in that circle, the animation plays and shows an afterimage of where the caster left, but where he teleported to, is just a blank spot. That is not to say, the whole token is gone, no. The token is technically still there, but it is now an empty space. It is neither "made invisible, nor anything. Me, the GM, also can't see a token there, but both the player and the GM can still select "the token".

Used find find the culprit to figure out which other module it could be that is interfering here, and could only find that maybe an interaction with sequencer did not properly clone the casting token to where it should be?

**Comment by otigon** [comment]
Hmm, the token never gets deleted or cloned with that Sequencer. Rather, it's just turned transparent before the move. Can you screenshot how your Misty Step animation is set up?

**Comment by KJTailor** [comment]
What details exactly are you after aka what should the screenshot include?

**Comment by otigon** [comment]
The A-A menu where you have Misty Step set up.

**Comment by otigon** [comment]
For instance: 
![image](https://user-images.githubusercontent.com/73318661/197653951-158c454f-bf6a-40a3-b5d8-1383f777eb6a.png)

**Comment by KJTailor** [comment]
ah ok. I will get to that later today after work (Australian time)

**Comment by otigon** [comment]
No worries, I'll probably check back in the morning (US time) lol

**Comment by KJTailor** [comment]
So even after the update today, it still doesn't come back after teleportation.
here is a screenshot of the settings: 494584
![image](https://user-images.githubusercontent.com/87787745/197688880-5e1b14eb-e9a7-444e-9d6b-af243e149e72.png)
 
and here I'm trying to do a little showcase (as well as that works in images)
![image](https://user-images.githubusercontent.com/87787745/197689320-8d885441-eab1-4719-b4b8-b7f7982f1a48.png)
![image](https://user-images.githubusercontent.com/87787745/197689398-1318b8de-1eba-4ff6-8405-b448a5497691.png)
![image](https://user-images.githubusercontent.com/87787745/197689465-226d0ac7-e24e-45dd-a659-9e56dd7839d4.png)

What is weird is, it works on some maps, and others it doesn't. The map in the screenshots doesn't have anything but walls, lights and sound effects. Another where it actually works only has walls.
The map where I first noticed it not working, uses weather FX and the inbuilt FX mask, maybe that's a connection? But doesn't explain why the map in the screenshots doesn't work...

**Comment by otigon** [comment]
So the way the Teleportation works is I have Sequencer make the Token transparent, teleport/move to the chosen location, and then reappear (back to full opacity). This could be some sort of lag issue at play.

Are you self hosting, or is this on a hosting service like the Forge?

One thing you can try is to increase the "Delay Fade In" to a longer time. The default is 250 ms. I suspect increasing that to 1000 or 1250 will fix your issue.

**Comment by otigon** [comment]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/73318661/197906261-c18b268f-72dd-42f1-a9f8-9a12a3370967.png">

**Comment by KJTailor** [comment]
I am using Foundry.
And your idea of increasing the Delay for the Fade In actually worked! Thank you

**Comment by otigon** [comment]
Ah good to know! I've seen this before where using very small delay times can sometimes cause issues like this, almost like it ends up skipping a step if the CPU is distracted. I'll go ahead and close this one out for now.
