### ISSUE TITLE
[System request] Splittermond

### ISSUE THREAD

**Issue by gsterling** [otigon/automated-jb2a-animations#523]
Greetings,
do you still accept system requests? Some where closed with the info you don't but the README.md still says I should log a request.

The system itself is only german, but the code and variable names are all in english. You can find it here: https://bitbucket.org/rpgframework-cloud/splittermond-fvtt/

I am sorry that I can't provide any of the info if the chat message provides the necessary data.

**Comment by otigon** [comment]
I took a brief look and the system does appear to pass the Item ID of weapons that are used. I think it is possible to add support in A-A for it, but I'll have to decline to do that myself. Took me a while just to get a weapon rolled due to the language barrier (I speak very little German). If you can get in touch with someone who can put in a Pull Request to add support I can review it after submittal and merge it in
<img width="271" alt="image" src="https://user-images.githubusercontent.com/73318661/197770479-58957966-62dc-4d1c-a931-ba672f6ad690.png">

**Comment by gsterling** [comment]
Thank you. Do you have any info on what exactly needs to be done? Maybe an existing PR that I could use to fifure out what I need to change for Splitternond

**Comment by otigon** [comment]
I've recently released a pretty big system workflow refactor that makes it easier to add system support. If you look at this file, it would be a good template for adding it in: https://github.com/otigon/automated-jb2a-animations/blob/main/src/system-support/aa-dcc.js

It does look like the Attack/Damage for items is rolled separately, so it will need to have checks in place so you don't get animations running every time you roll something. And then finding out how to tell if the Item has damage/attack/etc. It would basically be something like:
```js
export function systemHooks() {
    Hooks.on("createChatMessage", async (msg) => {
        if (msg.user.id !== game.user.id || !AnimationState.enabled) { return };

        let compiledData = await getRequiredData({
            itemId: msg.flags?.splittermond?.check?.weapon?.id,
            actorId: msg.speaker?.actor,
            tokenId: msg.speaker?.token,
            workflow: msg,
        })
        if (!compiledData.item) { return; }
        runSplittermond(compiledData)
    });
}

**Comment by otigon** [comment]
That would get the Item ID, but the tricky part comes on how you check to see if it should actually show an animation. The basic layout would be something like
```js
async function runSplittermond(data) {
 let msg = data.workflow;
 if (/*something here to check if it is an attack roll*/) {
    const handler = await AAHandler.make(data);
    trafficCop(handler)
 } else if (/*something here to check if is a damage roll*/) {
      const handler = await AAHandler.make(data);
      trafficCop(handler)
 }
}
```
It would also need a game setting added to choose whether to play animations on attack/damage, etc
