### ISSUE TITLE
canvas drawing failed: the belowtokenneffects layer subclass of canvaslayer must define the _draw method

### ISSUE THREAD

**Issue by thejoecraft** [otigon/automated-jb2a-animations#526]
canvas drawing failed: the belowtokenneffects layer subclass of canvaslayer must define the _draw method

THis error populates when activating Automated Animations module now, A no longer works and crashes my foundry.

**Comment by otigon** [comment]
Can you screenshot the entire error, and when does this happen. What versions of everything are you running

**Comment by thejoecraft** [comment]
Yes, ill ss and add here. just the base DnD5e system at it's latest update

**Comment by otigon** [comment]
Also version you are on for:
Foundry
A-A
Sequencer
DnD5e

**Comment by otigon** [comment]
Closing due to no response
