### ISSUE TITLE
AA "Remove Template" interrupts Midi QoL workflow

### ISSUE THREAD

**Issue by FreshnessDND** [otigon/automated-jb2a-animations#529]
Enabling "Remove Template" stops Midi QoL workflow in assigning damage to targeted tokens and hinders automatic rolling for saves unless LMRTFY is assigned.

Disabling "Remove Template" resolves the issue and workflow proceeds as normal.

**Comment by otigon** [comment]
I would recommend in this instance to NOT use the Template removal in Automated Animations. Midi-QOL can handle template removal

**Comment by FreshnessDND** [comment]
It can't handle template removal after the template has been immediately placed. It only has workflow to remove template after effect has been removed.

**Comment by otigon** [comment]
Won't be able to have it both ways. If A-A is messing with Midi like that, you either need to forgo those parts of Midi or have Midi handle the templates
