### ISSUE TITLE
Talents and Spells not triggering AA animations in Shadow of the Demon Lord system

### ISSUE THREAD

**Issue by doctorthoss** [otigon/automated-jb2a-animations#531]
Weapon attacks trigger animations just fine with no issues, but talents and spells don't.  Saw someone mention this on the discord and Otigon said it looked like a simple fix but wanted to post here just in case.

Foundry v10 build 288
SotDL system v. 2.2.3
AA v4.0.21
JB2A v0.5.1

**Comment by doctorthoss** [comment]
This is the error that comes up when triggering a talent while AA is enabled

`Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
[Detected 2 packages: autoanimations, system:demonlord]
    at Function.from (<anonymous>)
    at Object.fn (aa-demonlord.js:13:82)
    at #call (foundry.js:724:20)
    at Hooks.call (foundry.js:706:38)
    at Object.fn (demonlord.js:11372:9)
    at #call (foundry.js:724:20)
    at Hooks.call (foundry.js:706:38)
    at DemonlordActor.useTalent (demonlord.js:2612:11)`

**Comment by doctorthoss** [comment]
(reopening, closed by accident)

**Comment by doctorthoss** [comment]
Also even with weapons (which do trigger animations on the current patch, whereas talents/spells don't) only play animations on roll attack works, when one of the other triggers is selected no animations play
![image](https://user-images.githubusercontent.com/81924327/202804999-9623b148-1191-4f08-9cd2-203f097d1ec8.png)

**Comment by otigon** [comment]
Fixed on version 4.0.22

**Comment by doctorthoss** [comment]
Issue has returned somewhat: at the moment there doesn't seem to be a way to get a talent without any damage roll to play an animation. If it has a damage roll you can set it to "play animations on roll damage" and it'll play the animation when you do, but if it's an ability that doesn't have any associated damage rolls, like a buff or something, it seems impossible to trigger the linked animations
