### ISSUE TITLE
Using remove template option on a template animation does not process damage/savs in midi qol 

### ISSUE THREAD

**Issue by dale-e-o** [otigon/automated-jb2a-animations#536]
Steps
.
Open a template spell like fireball - 
Setup effect and add advance option to remove template (I just want to see the effect not keep the template on the screen
Cast Fireball

Actual Results
The effect executes beautifully, however Midi QOL does not apply the damage or call for saving throws from the affected creatures.

Expected Results
The effect goes off and mathematical automations complete.

**Comment by otigon** [comment]
Been a recent issue. A-A removes the template when set so the animation plays without interference. Automation is done thru other modules so you'd need to reach out to them if there is an issue
