### ISSUE TITLE
Template Animations not triggering in Starfinder

### ISSUE THREAD

**Issue by oronald** [otigon/automated-jb2a-animations#537]
The melee and Range animations work fine, but the Templates, where i need to select an area, do not.

I have tried using spells like Fog Cloud in Starfinder, but when i cast it, nothing show up, there's no option to select the area of effect, i just click it, the message appears in the chat but nothing happens.

I don't know if i missed something, but i tried a few tutorials and it didn't fix it.

**Comment by otigon** [comment]
Fixed on version 4.0.22
