### ISSUE TITLE
Unbind Alpha and Unbind Visibility defaults are reversed

### ISSUE THREAD

**Issue by MrVauxs** [otigon/automated-jb2a-animations#538]
By default, `Persistent` Active Effect animations have **Unbind Alpha** and **Unbind Visibility** disabled.
As a result, all effects by default show up when the token is hidden. Enabling **Unbind Visibility** makes the effect disappear when the token is hidden.
In the meantime, **Unbind Alpha** does not work at all. Changing the tokens opacity with the setting on or off doesn't change anything.

**Automated Animations**: 4.0.21
**Foundry**: 10.290
**System**: Pathfinder 2e v.4.4.0

**Comment by otigon** [comment]
Fixed on version 4.0.22
