### ISSUE TITLE
Automatic Backup for "Restore Default Menu" not working?

### ISSUE THREAD

**Issue by jalspaugh3** [otigon/automated-jb2a-animations#540]
I accidentally clicked the "Restore Default Menu" thinking it was related to a UI Skin and not my library of animations, and I lost everything.  On the Confirmation window it said "A Backup will be Exported for Insurance" but I can't seem to find a backup that was made anywhere.  There are no new .json files that have been made anywhere in my worlds or modules folders.  I am guessing that a backup was never made?

**Comment by otigon** [comment]
That message was supposed to have been removed because the multitude of earning dialogs added during menu change processes like thatm unfortunately it's lost to the abyss sorry
