### ISSUE TITLE
In SotDL system, spells and talents with damage rolls do not play animations unless "play animations on roll damage" setting is on

### ISSUE THREAD

**Issue by doctorthoss** [otigon/automated-jb2a-animations#541]
After the latest patch, animations for spells and talents are working again in SotDL, as long as either:
A. The spell or talent does not have an associated damage roll
B. The spell or talent *does* have an associated damage roll, and the "play animations on roll damage" module setting is on.

With the default setting, "play animations on roll attack," animations play perfectly as long as the spell/talent has no associated damage roll. Whether there's an associated attack roll only and no damage, or no associated roll at all, the animation will play with no issues. But if a damage roll is added to the spell or talent, animations stop playing alltogether.

The workaround is to enable "play animations on roll damage." When this is on, then spells and talents with damage rolls will play their animations when damage is rolled. However currently it seems there's no way to have a spell or talent with a damage roll trigger an animation whenever it is cast, instead of waiting for a damage roll (that will never come if the spell missed).

**Comment by doctorthoss** [comment]
This problem does *not* apply to weapon attacks, which play their animation normally when the initial _attack_ is rolled, despite having associated damage rolls

**Comment by doctorthoss** [comment]
Let me know if I can do any testing to assist with this one! I knows it's a weird one and SotDL isn't the most popular system, but I really appreciate all the work you've done, and given that SotDL has an officially licensed module coming out with foundry this year it'd be great to have the support!

**Comment by otigon** [comment]
Thanks for reminding me on this, it got lost for a while. I'll take a look this weekend

**Comment by doctorthoss** [comment]
> Thanks for reminding me on this, it got lost for a while. I'll take a look this weekend

No worries at all, thanks so much!! Like I said, let me know if I can provide any useful data

**Comment by otigon** [comment]
Unfortunately this is going to require someone with knowledge of the system to submit a PR to fix this. @patrickporto  originally submitted the PR to add support for the system, maybe he would be able to check it

**Comment by doctorthoss** [comment]
@clipplerblood any chance you could assist with this?

**Comment by doctorthoss** [comment]
@otigon not sure if this is something you could address on your end with a compatibility patch, but thanks to the intrepid efforts of another modder the possible cause for this issue has been found; apparently "msg.isRoll" returns false when certain rolls are triggered by built-in macros in the SotDL system. I opened an issue for it here: https://github.com/Xacus/demonlord/issues/118

And there are more details in the issue where others discovered the problem here: https://github.com/Xacus/demonlord/issues/115

**Comment by doctorthoss** [comment]
good news, a fix is already coming! will update this after the SotDL update and we'll see if it fixes the problem

**Comment by doctorthoss** [comment]
Unfortunately the SotDL update didn't fix the issue. Origin if you have any idea what might be causing this on the A-A end maybe @juanferrer could assist from the SotDL side of things? Otherwise I'll just keep an eye out and keep trying to troubleshoot

**Comment by doctorthoss** [comment]
Update! Juanferrer, the guy in charge of the SotDL module, has just submitted a PR to fix these issues
