### ISSUE TITLE
Feature Request: Export Only Non-Default Effects

### ISSUE THREAD

**Issue by Armandeus66** [otigon/automated-jb2a-animations#544]
The PF2e Animation Macros for use with Automated Animations has a Debug feature that can show all non-default (to PF2e Animation Macros) effects. It cannot export only those effects.

Please add a means to export only those effects from the bottom of that debug list as a separate json file, instead of the current way that can only export the entire list of all effects.

I asked at PF2e Animation Macros, but was told that this would be a more appropriate place to make the suggestion by the module author.

This would allow the user to share or archive only those effects that are not default, such as user-created effects, or effects from other sources. The exported file would be shorter, making it easier to see what the new effects are, and edit or delete some of them with a text editor. Also, since the file only includes non-default effects, someone importing would not have to worry about overwriting the defaults.

An additional feature for this would be to have those sounds, and any animations not in the JB2A set, exported (to a zip archive?) along with the json file of only the non-default effects. The merge function could then copy the sounds and animations into a specific import directory when merging, to keep these non-JB2A animations and new sounds separate and easy to find.

**Comment by otigon** [comment]
Gotta draw the line somewhere, and I'm pretty much done constantly changing stuff to accommodate. Sorry but no
