### ISSUE TITLE
[Feature Request] Babele compatibility

### ISSUE THREAD

**Issue by MiahNelah** [otigon/automated-jb2a-animations#548]
__Context :__
When using Babele to translate stuff, names are dynamically altered on-the-fly. As name changed, A-A's global animation lookup fail. Basic workaround is to duplicate every A-A animations setup and translate every name, but it is a lot of work and very tied to specific localization.

__Request :__
Use original name instead of altered ones by Babele.

__Details :__
While Babele alter name, it store original name inside flags at `flags.babele.originalName`. A nice way to ensure compatibility would be to take babele's original name if available to look for animation instead of base name.

**Comment by MrVauxs** [comment]
As far as we have tested, it already works with Babele. What does not work for you?

**Comment by MiahNelah** [comment]
I understood I do ha a misconception about Babele. I  checked out and you're true : everything works fine with compendiums.  In that way, this feature request is obsolete, and I realize I poorly described it. 

My thoughts was about embedded items which has been translated by Babele when imported from compendium. Once a an item has been imported and/or embedded, it's definitely translated in a way original name is lost. In that way, it's not anymore about Babele compatibility. It's more about how to handle a custom naming process which may store original name in some flags for later use with A-A.

You can close this issue, I'll try to dive into code and see if I can weaver a custom solution for my needs.

**Comment by MrVauxs** [comment]
Babele doesn't translate directly as far as I know, but instead changes how things are shown.
The original data is still there and read by AA. It's when you do manual modifications is when you have to adjust for the new, custom names.
