### ISSUE TITLE
[Bug] 3D Canvas particle animations: cant change sprite, can't use 3D sprite.

### ISSUE THREAD

**Issue by JSwift777** [otigon/automated-jb2a-animations#549]
When using Automated Animations in conjunction with 3D Canvas, most of the options (e.g. speed, repeat, delay, etc) appear to work correctly, however the sprite is stuck as the default 'emberssmall.png' (a small white circle) regardless of what file is pointed to.

In addition, 3D Canvas allows for the use of 3D objects as particles by pointing the ".sprite()" function at a 3D model, however the file picker for the 'sprite' field in the automated animations configuration window only allows images to be selected - ideally it should also allow .glb/fbx/etc files.

On a related note, the Sprite field and the Type field seem to be missing from the secondary animation area, so the sprite used for the secondary animation or the type of particle system used cannot be changed.

**Comment by otigon** [comment]
Just pushed several updates that should fix most of these
