### ISSUE TITLE
[System Request] Savage Worlds

### ISSUE THREAD

**Issue by brunocalado** [otigon/automated-jb2a-animations#55]
Hi.

I can't make it work well with Savage Worlds.

Can you make it activate the animations? It don't need to identify the items. Just make the custom form work.

Thank you.

Bug then you click Override Animation?
![image](https://user-images.githubusercontent.com/4999783/118189541-4d0f5f80-b418-11eb-81e4-d7b03acf74f5.png)

**Comment by otigon** [comment]
@brunocalado are you using Better Rolls for SW, or just rolling from core?

**Comment by brunocalado** [comment]
I tried both. 

Better Roll 2 and the core.

**Comment by randyrosales** [comment]
it gives an error in this line in the code:

let targetSize = target.actor.data.data.traits.size;

I don´t think that route is valid in SWADE, looking at your code i think you are trying to check the target size like in D&D, but in SWADE the size is a number, and is in **target.actor.data.data.stats.size** and in SWADE the size is a number not a string, so for example compare it with "tiny", "med" or "huge" like you are doing in your code should not work (unless there is some part of the code that I´m not looking that make the conversion)

**Comment by otigon** [comment]
I'll have to do the conversion inside the Swade handler document. I should be able to do this in the next few days.

**Comment by otigon** [comment]
I've put in a quick patch so the Creature Attacks and Healing Spells function. I'll fix it more comprehensively on the 0.8 update
