### ISSUE TITLE
Warhammer 4th : Creature trait do not play animation

### ISSUE THREAD

**Issue by Skrollyx** [otigon/automated-jb2a-animations#551]
The creature from the official compendium have their attack from their traits in the note window in creature sheet, which do not cause the animation to play.

**Comment by otigon** [comment]
I would need you to send me a creature from this compendium through Discord, Otigon#2010, so I can test with it

Everything is behind a paywall in Warhammer and I own none of the content

**Comment by Skrollyx** [comment]
I already sent you a bear almost a month ago didn't you receive it ?
I'm Kioll77 on discord

**Comment by otigon** [comment]
I'll have to check my discord messages, was stupid busy at work the last 2 months

**Comment by otigon** [comment]
Have a fix in for next release, I'll let you know when it's out

**Comment by Skrollyx** [comment]
Cool, thanks a lot !

**Comment by otigon** [comment]
Fixed in version 4.2.10
