### ISSUE TITLE
Feature: Autorecognition word exclusion

### ISSUE THREAD

**Issue by SalieriC** [otigon/automated-jb2a-animations#552]
A feature to include a word or series of words in each autorec that prevents that autorec from being applied if the excluded word(s) is found. Basically a reverse autorec.

Example:
Autorec: "Word"
Exclude: "Another"
Affects: "Word", "Interesting Word", "Long Word", "Short Word", etc.
Won't affect: "Another Word", "Another Interesting Word", "Another Long Word", etc.

This would help a lot with things that share some words. It would be especially advantageous to me as it would allow me to provide users of my module an import for AEs as my module has a feature to apply AEs for spell effects but it also adds an AE to the source of the spell indicating that it is maintained. With such a feature I could exclude the AEs which indicate the maintenance and apply it only to the real thing.

**Comment by otigon** [comment]
I actually have a "force exact match" feature I'm adding in that should take care of this

**Comment by SalieriC** [comment]
That's similar but not exactly what I meant and wouldn't be the ideal solution. For me (and possibly many SWADE players) at least.

**Comment by otigon** [comment]
I'll consider it, but I'm really not a fan of adding more clutter to the UI and complexity to the search function

**Comment by otigon** [comment]
Feature has been added in version 4.2.00. Has Exact Match, Excluded Words, and Excluded Item property. Find the advanced features section inside the Overflow button on each animation section.
<img width="295" alt="image" src="https://user-images.githubusercontent.com/73318661/210270690-576c7a5f-d954-474d-bb2a-d7474b2d174f.png">
