### ISSUE TITLE
[System Request] Integration with Twodsix System

### ISSUE THREAD

**Issue by marvin9257** [otigon/automated-jb2a-animations#553]
This request reopens a similar request (#546) to provide integration with the Twodsix system.  The system chat messages have been updated with the current release to include flags for the following:

actorUUID: the actor making the roll
tokenUUID: the token on the scene (may not match actor's token)
itemUUID: item being used by actor
rollClass: type of roll (i.e. Weapon, Skill, Ship, Damage, etc.)

Thank you for your consideration.

**Comment by otigon** [comment]
Added basic support in version 4.2.11. Just let me know if anything acts weird
