### ISSUE TITLE
Cyberpunk Red Core: Ranged attacks not working anymore

### ISSUE THREAD

**Issue by diwako** [otigon/automated-jb2a-animations#554]
(this is a repost from the discord, just wanted to post here as well so it is being kept track of)

Hello since recently I have issues with the automated attack animations on ranged based attacks not working anymore in the cyberpunk red core system
recently all ammunition in the system was renamed to be consistent, that is a change I have done already on the configuration part inside AA to reflect the new naming.

I have checked if a global match is found for the ammunition, which it has for all types so far, yet no animation is played.
The only animations that are affected are ranged attacks and template based animations. melee and active status effects are working as intended.
![image](https://user-images.githubusercontent.com/8259498/209844210-57936fdf-b752-4104-92fe-e258c32a4ab8.png)
![image](https://user-images.githubusercontent.com/8259498/209843931-6c1a93e4-cda8-4b90-bcaa-f3c92397f37d.png)
![image](https://user-images.githubusercontent.com/8259498/209843946-7ba35b28-4ccd-4d7e-bb99-278cd8408f1b.png)

Here the exported config
[fvtt-autoanimations-autorecognition.zip](https://github.com/otigon/automated-jb2a-animations/files/10315308/fvtt-autoanimations-autorecognition.zip)

**Comment by otigon** [comment]
should be fixed in version 4.2.00

**Comment by diwako** [comment]
Thank you, just tested it, it works again!
