### ISSUE TITLE
AA not playing animations in the Rifts modules for SWADE

### ISSUE THREAD

**Issue by CaponNC** [otigon/automated-jb2a-animations#555]
Sequencer shows shows the animation trying to be played, but the effect doesn't appear on the canvas.

**Comment by CaponNC** [comment]
Found out it's due to Better Rolls 2 for SWADE that's causing issued. Using an alternative module (SWADE Tools)

**Comment by otigon** [comment]
BR2 for SWADE is undergoing some data structure changes. I won't be able to tweak stuff on my end until they're finished
