### ISSUE TITLE
Cannot dropdown After Image/Video on presets after setting file and saving.

### ISSUE THREAD

**Issue by Janner3D** [otigon/automated-jb2a-animations#556]
![image](https://user-images.githubusercontent.com/35965176/209995144-1e260c44-5d8d-49d8-8022-a0f003f89fa7.png)
After setting a file to use as an after-image, the dropdown functionality of that sub-menu no longer seems to work, which also causes some other bugs across the menu, such as no longer being able to create new animations sequences, 'causing the menu to be stuck to the top left of the screen and no longer being able to reopen the automatic recognition menu after closing it.

**Comment by otigon** [comment]
Please check the console (F12) for errors

**Comment by Janner3D** [comment]
> Please check the console (F12) for errors. Also pleases provide the following:
> 
> 1. Game system and version
> 2. A-A version

![image](https://user-images.githubusercontent.com/35965176/210003266-6dbaf1cb-fd56-4127-80e0-6e8ed72fe340.png)
![image](https://user-images.githubusercontent.com/35965176/210003317-b43c1d32-d460-4d2f-9f62-99b486091703.png)
![image](https://user-images.githubusercontent.com/35965176/210003341-ca3ff716-e8ee-434a-b199-18ded6c046ac.png)

**Comment by otigon** [comment]
Can you export your Global Autorec menu and post it here? Hard to tell what that error is pointing to

**Comment by Janner3D** [comment]
> Can you export your Global Autorec menu and post it here? Hard to tell what that error is pointing to

How do I export the list?

**Comment by otigon** [comment]
Menu Manager button in that window , export
![image](https://user-images.githubusercontent.com/73318661/210006498-5a0a715b-3d4d-4223-8a9c-955e0b3e01e5.png)

**Comment by Janner3D** [comment]
[fvtt-autoanimations-autorecognition.zip](https://github.com/otigon/automated-jb2a-animations/files/10321974/fvtt-autoanimations-autorecognition.zip)


> Menu Manager button in that window , export ![image](https://user-images.githubusercontent.com/73318661/210006498-5a0a715b-3d4d-4223-8a9c-955e0b3e01e5.png)

**Comment by otigon** [comment]
weird, it should have downloaded as .json extension. Can you message me this on discord? ID Otigon#2010

**Comment by otigon** [comment]
Going to close this, but will still be looking into the issue. Use the Autorec menu I sent you in Discord to overwrite your current menu.
