### ISSUE TITLE
Broken in DnD 5e 2.1.1

### ISSUE THREAD

**Issue by plumppig** [otigon/automated-jb2a-animations#569]
Post the 2.1.1 migration the following error occurs when trying to polymorph.

![Screenshot 2023-01-11 at 8 14 53 PM](https://user-images.githubusercontent.com/5460707/211967734-07cf59c1-60bd-4034-a195-92e3d61277c8.png)

**Comment by otigon** [comment]
I don't see any errors there related to Automated Animations

**Comment by plumppig** [comment]
Ah crap, I meant to put this in automated polymorph; haha. My bad!
