### ISSUE TITLE
SWADE Potions/Gear

### ISSUE THREAD

**Issue by brunocalado** [otigon/automated-jb2a-animations#573]
Amazing module!!!!!

Is it possible to trigger an animation by sendind it to chat without roll?

I want to trigger an animation when using potions and other items which don't need a roll.

![image](https://user-images.githubusercontent.com/4999783/213798877-c1910969-a729-42cd-8a1b-e96b0b0df72d.png)

**Comment by otigon** [comment]
If you are using Better Rolls 2 this should already work. Otherwise it may not work with the base system. I don't know SWADE much at all, so it would require someone with knowledge of the system to update the workflow in A-A to work with the base system
