### ISSUE TITLE
Cyberpunk Red Core: Ranged and template based attacks stopped working

### ISSUE THREAD

**Issue by diwako** [otigon/automated-jb2a-animations#574]
Hey
The Cyberpunk Red Core system had another larger update.
Testing on my local dev instance I noticed the ranged attacks are not showing up. It looks very similar to #554 with it only affecting ranged and template based animation detection

![image](https://user-images.githubusercontent.com/8259498/213911946-32597585-222d-45aa-a215-b129588223ec.png)

![image](https://user-images.githubusercontent.com/8259498/213911974-d0b3e9b2-887f-4f26-8b83-28536964d380.png)

What however looks new is this message with debugging enabled
`DEBUG | Automated Animations | Could not extract Item ID from Chat Message HTML`

**Comment by otigon** [comment]
yeah it looks like they changed the data structure on us. I'll get a fix in for the next release

**Comment by Zyzyx** [comment]
Hi, I work on that system. Can you outline what structures your module expects or depends on? I can write that down in our docs so if we change it again we can give you a heads' up, or maybe avoid a breakage altogether.

**Comment by otigon** [comment]
Hey there @Zyzyx , this one was specifically dealing with how I was checking the item for Ammunition. I think previously the structure was ``item.system.magazine.ammoId`` and changed to ``item.system.magazine.ammoData.uuid``.

It's really not a problem when data structures change, I just have to tweak it on my end to accommodate. For the rest of it I'm grabbing the ``Item ID``, ``Actor ID``, and ``Token ID`` from the chat message when it is posted to chat

**Comment by otigon** [comment]
Fixed on A-A version 4.2.09

**Comment by Zyzyx** [comment]
(I know I'm late) Thanks for the quick fix!
