### ISSUE TITLE
Error on autorec file

### ISSUE THREAD

**Issue by brunocalado** [otigon/automated-jb2a-animations#575]
Hi.

When I try to load this autorec it loads, but then it generates an error when I try to edit the staff. There is also an error when I try to activate the animation.

![image](https://user-images.githubusercontent.com/4999783/213938118-3d56d0ee-21b5-4514-a734-94c75112f007.png)

![image](https://user-images.githubusercontent.com/4999783/213938126-fc14a939-67ae-47a1-8e35-9a90bc312d1b.png)

[autorec.txt](https://github.com/otigon/automated-jb2a-animations/files/10475410/autorec.txt)

**Comment by brunocalado** [comment]
After this update I can't even open the menu.
![image](https://user-images.githubusercontent.com/4999783/213938551-bb3aa688-3384-4937-8e90-71055fde2496.png)

**Comment by otigon** [comment]
run this command in the console to export your menu, then please post it here

AutomatedAnimations.AutorecManager.exportMenu()

**Comment by brunocalado** [comment]
> run this command in the console to export your menu, then please post it here
> 
> AutomatedAnimations.AutorecManager.exportMenu()
[fvtt-autoanimations-autorecognition (2).txt](https://github.com/otigon/automated-jb2a-animations/files/10475427/fvtt-autoanimations-autorecognition.2.txt)

**Comment by otigon** [comment]
that should have been a .json file on the export, did you change it to .txt?

**Comment by brunocalado** [comment]
> that should have been a .json file on the export, did you change it to .txt?

Github don't accept .json. I need to change it to .txt.

**Comment by otigon** [comment]
Did you import this menu from somewhere? Some of the animation fields are missing required data

**Comment by brunocalado** [comment]
> Did you import this menu from somewhere? Some of the animation fields are missing required data

Yes. My friend used chatGPT to create this file... 

He just explained to me.

I was trying to understand too.

Thank you.

**Comment by otigon** [comment]
I'll message you on Discord with a fixed file

**Comment by brunocalado** [comment]
> I'll message you on Discord with a fixed file

Tks!
