### ISSUE TITLE
[Suggestion] Fallback animation

### ISSUE THREAD

**Issue by Gorvaine** [otigon/automated-jb2a-animations#577]
Would be possible to have a fallback animation for all the items that does not have any specified animation configured?

Thanks!

**Comment by otigon** [comment]
There is nothing for this in A-A, and tbh I don't see myself creating something for it like that. You can already use the Global menu to do something similar, such as adding an entry in the Range menu for "Bow", which will play that animation for any Item with "bow" in the name that doesn't already have an entry. You can use the same logic for other items
