### ISSUE TITLE
Secondary and Target animations not working for PF1e

### ISSUE THREAD

**Issue by Yonman17** [otigon/automated-jb2a-animations#578]
Secondary and Target animations not working for Pf1e since the update to Version 10

**Comment by Yonman17** [comment]
> Secondary and Target animations not working for Pf1e since the update to Version 10

The main issue is that you Cannot select an animation when you use a custom file.  Selecting a file leaves the option blank even after selecting.

**Comment by Yonman17** [comment]
Looks like it's working again now

**Comment by otigon** [comment]
Resubmit and follow the provided format

**Comment by Yonman17** [comment]
And now it's working again.  Seems like I have to reboot foundry

**Comment by otigon** [comment]
This does sound like a big, and if you resubmit this tickets with all the required information I can take a look. Without that information nothing will get done
