### ISSUE TITLE
Integration with Token Magic

### ISSUE THREAD

**Issue by brunocalado** [otigon/automated-jb2a-animations#581]
Hi!

Is it possible to integrate Token Magic module into AA? 

Example:
Instead of you have to create a macro, add it to the world and enable Advanced Macros module. You could just paste a Token Magic macro into a text box in the AA menu. 

This would allow to have even more animations available for AA. This would also let you have a autorec file with everything you need, without have to fill the world with macros.

tks

**Comment by otigon** [comment]
Integrated TMFX at this point would require a huge overhaul to the module, so not really in the cards right now.

For the issue of loading your world with macros, you can store them all in a compendium and call it from there within A-A. In the macro section you can navigate to the compendium and then pick the macro you want

**Comment by brunocalado** [comment]
> Integrated TMFX at this point would require a huge overhaul to the module, so not really in the cards right now.
> 
> For the issue of loading your world with macros, you can store them all in a compendium and call it from there within A-A. In the macro section you can navigate to the compendium and then pick the macro you want

Nice. This solves. But, the longer name makes harder to find the macro. Can you fix this? 

tks

![image](https://user-images.githubusercontent.com/4999783/215325223-67de9140-ffbf-43d9-97e5-7686c741c0b4.png)
