### ISSUE TITLE
[REQUEST] - Color Effects for any Animation Type

### ISSUE THREAD

**Issue by WanderSiqueira** [otigon/automated-jb2a-animations#582]
**Is your feature request related to a problem? Please describe.**
No, it's not. The module works perfectly for me.

**Describe the solution you'd like**
I'd like to suggest that the "Effects" tab there's in the Aura Animation Type sheet be implemented in other Animation Types.

**Describe alternatives you've considered**
Our DM already has the JB2A patreon version of the module and they don't have a red Fog Cloud, then I had to set it as an aura, and I creat a token everytime we want to put it in the game, just to set it red (It's from one of the characters lore, because is made of his blood).

**Additional context**
We all love your module!

**Comment by otigon** [comment]
Added the ability to tint, saturate and contrast all animation sections in version 4.2.11
