### ISSUE TITLE
[REQUEST] - Remove Annoying Warning

### ISSUE THREAD

**Issue by brunocalado** [otigon/automated-jb2a-animations#584]
Using Automated Animations and Token Magic I trigger an animation without the need to args, but sequencer keep warning about the need to advanced macros.

Can you turn off this warning? Maybe ignoring args if the field is blank or add a checkbox to turn off args

https://user-images.githubusercontent.com/4999783/215296779-3d1d0b2f-742a-4dff-be22-91d9543f960b.mp4

tks

**Comment by otigon** [comment]
Not an A-A issue, I don't output that warbing

**Comment by otigon** [comment]
added checks in A-A to not pass args if Advanced Macros is not active, thus eliminating the errors showing
