### ISSUE TITLE
[REQUEST] - Match autorecs by damage type

### ISSUE THREAD

**Issue by morepurplemorebetter** [otigon/automated-jb2a-animations#586]
I would like to be able to set a generic animation that works as a failover for when a feature has no matching name. I feel the best way to do this would be to match the damage type, as that will best determine what kind of animation is most appropriate.

This way I could, for example, select a default animation (and sound) for all things that do piercing damage in melee.

I play D&D 5e, so that would be the system I would like to see this be implemented for, but I guess this would be equally applicable to many other systems.

The implementation could be as "simple" as (1) adding a checkbox in the Advanced Recognition Features that it will be checked against the (first) damage type and not a feature's name, and (2) only checking the autorecords with this checkbox set last. As well as the actual implementation of how the matching is done, of course.

**Comment by otigon** [comment]
I should be able to get this functionality in for D&D 5e. There is something similar in place for PF2e where it falls back to base weapon type, and since 5e has a good item data structure shouldn't be too hard. I'll get it worked on

**Comment by otigon** [comment]
I looked at doing something like this, but the amount of work to build out a "default" style menu is beyond what I'm willing to put in, and I can't see any way to make it system agnostic. Going to close this one
