### ISSUE TITLE
[FEATURE REQUEST] - Allow all template elements to be hidden when using A-A template animations

### ISSUE THREAD

**Issue by paulohdsc** [otigon/automated-jb2a-animations#590]
I already reported this on discord. I'm opening this issue for you to take a look if you have the time.

I noticed that the _**Automatically hide template elements**_ option of Token Magic FX works only partially with A-A template animations (see image). The "point" elements of the template are hidden, but not the border. Would it be feasible to allow said TMFX option to also hide that circumference border element? If not, could you incorporate a similar option in A-A?

![image](https://user-images.githubusercontent.com/75817094/216205762-82da4fc6-81ac-475a-a3c7-58d4ad28a31d.png)

**Environment details**:
Foundry 10.291 | DnD5e 2.0.3 | A-A 4.2.13 | TMFX 0.6.1.2
Token Magic FX _**Default template grid on hover**_ option was disabled, as needed for A-A _**Template Grids on Hover**_ to activate

**Comment by otigon** [comment]
I have a similar setting in A-A to hide the Template Grid Highlighting in a way similar to TMFX, but I could not figure out how to hide the other elements. I'll take a look, but it's lower priority

**Comment by otigon** [comment]
Decided not to implement this
