### ISSUE TITLE
[BUG] - Side Impact not working

### ISSUE THREAD

**Issue by WanderSiqueira** [otigon/automated-jb2a-animations#591]
**Describe the bug**
Side Impact option is causing the animation to not play at all. Not only the Side Impact part, but all the animations within that animation template.

**To Reproduce**
Just set a side impact animation within any of the camps available (both Secondary Animation and Target Animation causes the bug).

**Expected behavior**
I expect the animation to be executed.

**Screenshots**
Don't think I have anything of help.

**Setup:**
 - Foundry Version: Newest (don't know, sorry)
 - System Version: Tormenta 20 newest (don't know, sorry)
 - Sequencer Version: Newest (don't know, sorry)
 - Automated Animations version: Newest (don't know, sorry)
 - Hosting Location: Local
 - Browser & version: I am the GM.

**Active modules:**
 - Sequencer
 - socketlib
 - I have a lot of modules, none of them is about animations.

**Additional context**

**Comment by otigon** [comment]
Thanks for the info, I'll get it sorted

**Comment by otigon** [comment]
Fixed in version 4.2.15
