### ISSUE TITLE
[BUG] - Teleportation Area

### ISSUE THREAD

**Issue by Kharmans** [otigon/automated-jb2a-animations#592]
**Describe the bug**
The area of the teleportation preset are wrong. When I choose Square, the area showing are very wrong and with circle too. The teleportation works and the area of the effect are ok. The problem is only what it shows. Curious, this problem don't occur with maps without grid.

**To Reproduce**
1. Just configure any Teleportation Preset.

**Expected behavior**
The teleportation template be what I configure it to be.

**Screenshots**
![trem](https://user-images.githubusercontent.com/112586547/216854192-4abc86d0-ed87-4859-8f5f-32bda5c76951.png)
![trem 2](https://user-images.githubusercontent.com/112586547/216854202-f28252b9-b683-4f86-8f75-fb68e0fdcd28.png)
![trem 3](https://user-images.githubusercontent.com/112586547/216854241-8b2ef12c-4b3f-4ff3-9d65-d40a13670b68.png)
![image](https://user-images.githubusercontent.com/112586547/216854244-34871836-8bcb-4dc4-b8d3-685fd4e3a13a.png)

**Setup:**
 - Foundry Version: 10.291
 - System Version: DND5e 2.1.4
 - Sequencer Version: 2.410
 - Automated Animations version: 4.2.15
 - Hosting Location: Molten Hosting
 - Browser & version: OperaGX LVL4 (core: 94.0.4606.79)

**Active modules:**
 - Sequencer
 - socketlib

**Comment by otigon** [comment]
I can't seem to replicate this issue. Can you test this with only the following modules active? You can use the Find the Culprit module to test this quickly.

Automated Animations
Sequencer
Socketlib

A screenshot of the scene configuration you are using would be helpful to. 
![image](https://user-images.githubusercontent.com/73318661/216863896-99b1ca55-844b-4406-8e91-543080b5eec4.png)

**Comment by otigon** [comment]
Oh and be sure to update your Sequencer module, latest version is 2.411

**Comment by Kharmans** [comment]
So, after seeing your images, I find the problem. It's the map. I don't know why, but it are configure with Grid Size 200. When I configure to 100, the teleport work properly.

**Comment by otigon** [comment]
It should be accounting for different grid sizes. I'll take a look

**Comment by otigon** [comment]
It looks like it's a problem with Sequencer not accounting for the different grid sizes. I'll bring it up with that Dev

**Comment by otigon** [comment]
this should be fixed now, just update your Sequencer module
