### ISSUE TITLE
[FEATURE REQUEST] - Option to Remove Template for all non-Persistent animations

### ISSUE THREAD

**Issue by manolodantonio** [otigon/automated-jb2a-animations#593]
System: DnD 5e

Using AA with Midi-QOL automations, i find that "Remove Template" is the best setting for non-persistent template effects.

Use Case: i cast a lightning bolt, i see the measured template and possible targets before placing the template. When i place the template, affected tokens are automatically targeted, and M-QOL automations fire. The template is now useless, only hindering animation visibility and requiring manual removal.

To solve this, right now it is required to modify every animation activating the Remove Template option.
An option to globally activate Remove Template if the animation is not persistent would be very appreciated.

This could be in the Settings submenu and, if enabled: 
- should grey out the Remove Template option in the Primary Animation panel. 
- The Remove Template option now will activate or deactivate based on the current status of the Persistent option.

**Comment by otigon** [comment]
I would recommend using Midi-QOL to remove the templates. Automated Animations has a global setting to remove the grid highlighting unless hovered
