### ISSUE TITLE
Animations and overrides stop working correctly after walls and lights added to game world.

### ISSUE THREAD

**Issue by FilthyHippy** [otigon/automated-jb2a-animations#6]
Sorry to bother you, I am not sure what I am doing wrong, but I would love to get this mod working consistently and have been beating my head against it for a few days now. (I just got the update, but no improvement).

As best as I can figure out, the mod starts behaving erratically when I start adding walls and lights to a game world.

I first installed this on a game world that I had been working on for some time. Many animations came from the wrong actor (or no actor), or did not play at all. Overrides in the source box had no effect or odd effects (changing bite to sword just changed the color of the bite) I started a new world to check for module conflicts.

In the new world, I used a blank map and enabled only this mod's dependencies and suggested mods (JB2A-patreon, Furnace, Token MagicFX and FX master). Every animation I tested worked brilliantly. Overrides also worked. I then added the other mods I wanted to use one at a time (D&D beyond importer, Virtual Tabletop Assets - Iconizer, Dice Tray, Dice So Nice!, Lootsheet NPC 5e, Fantasy UI). Everything still worked.

I tried reinstalling mods to the original game world in the same order, no luck. Since I had previously tested and deleted a lot of mods, I thought that I had broken something in the original game world.

I then exported all my content to another new world by creating modules for my homebrew compendiums (actors, journalentries, Items, scenes). All the animations worked great until I started using my old scenes, then things stopped working again. I guessed that something was wrong with the scenes. I was sure I had found the problem.

Finally, I began remaking my maps in the new game world. I added my old background images from the source .png files, not from the compendium. Everything still worked. I then drew walls on several of the maps and added a few light sources. I tested the animations again, and I was back to the same problem. The problems now occur on every scene I test, not just the ones with walls and lights.

Some examples:
spear and javelin do not work at all, cannot override
scimitar's override stopped working (could previously set to sword, 1hs, 1hp, anything, really)
bow animations come from actors who have bows, but were not selected. 
putting xxx or another keyword in the source box seems to have stopped working entirely

As I said, my best guess is the walls and lights, but I don't know if something else could be a factor. Sorry for the long post, but I wanted to describe my troubleshooting process (I also fiddled with module settings quite a bit, but nothing changed.)

Any suggestions on getting the animations to behave or the source of the problem would be greatly appreciated.

Thanks

**Comment by otigon** [comment]
I haven't run into any issues like this, but let's start from the beginning.
1. Are you using Midi-QOL or MRE, or any other module that changes the roll functionality like Better Rolls?
2. Are you rolling the item from the character sheet, or activating them from the Macro hotbar?
3. Are there any errors in the console (F12) when things start going wonky? 
4. Are the characters imported using a module like D&D Beyond Importer, and are any of these custom items or from the SRD compendium?
5. Is this in the 5E System?

**Comment by FilthyHippy** [comment]
Thank you so much for your response!

1. I am only using the modules listed in the initial post; no Midi-Qol, MRE or Better Rolls.
2. I am embarrassed to admit that I did not think to try rolling from the macro bar. I just tested this on some of the item/animation combinations that were not working, and they work great from the macro bar!!! The same problems repeat when rolled from the character sheet. I am sorry if I missed this in the instructions/description somewhere.  Switching the selected actor and using the same macro also plays the animation correctly. I've only tested about ten actor/item/effect combinations so far, but this seems to solve everything. Is it supposed to work from the character sheet or only from the macro bar?
3. No console errors when using macro bar or character sheet.
4. I tested SRD, imported, and completely homebrew actors, and SRD, altered name/stats SRD, and completely homebrew items. Mostly shortbow, crossbows, shortsword, scimitar and spear (it is strange, but all the spells I rolled from the character sheet worked no matter what I did, I only had problems with some of the items listed under the Attacks section of the sheet. Mace, for example, always worked no matter what)
5. Yes, this is D&D5e, Latest Foundry version. All modules were updated yesterday.

Thank you for your help, and sorry again If I just didn't read carefully enough. 

Also, thank you for developing this amazing module. I wouldn't even try to use animations if you hadn't created a way to make them easy for my players. I haven't told them about this yet, and am excited to see their reaction when we begin the new campaign in a couple weeks. I didn't find a Patreon link for you, but would be happy to support for a limited time just to show my appreciation.

I think this closes the issue for me, especially if the mod was not intended to work from the sheets. Is there anything else I can tell you that would be helpful for you?

**Comment by otigon** [comment]
I'll need to take a look at what's going on, I think I should be able to replicate based on your response (I'll try it out later today).

The animations should work whether the item is rolled from the Macro Bar or the Character Sheet, but I think I did all my testing rolling the items from the inventory panel versus the Attack section. I don't "think" that should make a difference, and it's weird that it's changing behavior with walls/lights etc.

I want to keep this issue open until I can get some testing done. I'll reach out if I have trouble replicating the issue.

One thing to note is that I haven't fully implemented animation switching yet. So using a Mace will generally use the Mace animation, and adding Sword in the Source field shouldn't generally change that.

**Comment by otigon** [comment]
That makes sense with multiple tokens on the field if the tokens are linked, though they "should" have unique Identities if I'm remember correctly. I'll definitely be able to test this and hopefully get back to you with a solution.

Thank you very much for the detailed outline, it really does help narrow things down

**Comment by otigon** [comment]
Did some quick testing during lunch and was able to replicate the problem you found. I'll dig into the data structures and how they change/don't change with multiple tokens on the field. At first glance it seems like something that should be fixable, but I'll know more later

**Comment by otigon** [comment]
Pretty sure I've found a fix for this. It had to do with the way I went about getting the Token ID for playing the animations. I'll run some tests later and push a fix tonight
