### ISSUE TITLE
[FEATURE REQUEST] - TYPE SHORT DESCRIPTION HERE

### ISSUE THREAD

**Issue by ServantofShiloh** [otigon/automated-jb2a-animations#601]
Hey, hey! Thanks for taking the time to read this.

I was wondering if you have any plans to make this compatible with **The One Ring** systems 1e and 2e? I tried to make this work (I play 1e) and the animations were not working as they should. I'm not a coder, but I'm guessing it has something to do with the pop up box it calls whenever something is done. Not sure how difficult this would be, but I'm throwing some love out there for TOR. 🙂

Thanks.

**Comment by otigon** [comment]
I don't have plans to add any more systems. I'll be pushing all system specific support for systems into a separate module soon, and others will have to submit PR's to add system support
