### ISSUE TITLE
[SYSTEM REQUEST] - Dark Heresy 2E

### ISSUE THREAD

**Issue by FilippoPolo** [otigon/automated-jb2a-animations#605]
Hi! I'd love to have support for Dark Heresy ( https://foundryvtt.com/packages/dark-heresy ). I'm starting to look into FoundryVTT development, but it'll be a while before I can try to do this on my own. :-)

**Comment by otigon** [comment]
new system support must be added via Pull Request, as I will not be adding more myself. That system support must also be maintained by whomever submits it
