### ISSUE TITLE
[BUG] - Error when editing HP while Damage Log module active

### ISSUE THREAD

**Issue by esheyw** [otigon/automated-jb2a-animations#606]
damage log, AA, dependencies, pf2e, foundry all  current at time of writing

If I have both [Damage Log](https://github.com/cs96and/FoundryVTT-damage-log) and AA active, and edit the HP of an actor without a token on the active scene, I get one of these:

![](https://i.imgur.com/Dt7bdKO.png)

Doesn't happen if the actor is on the scene.

Now this could be an issue on their end, but the error is popping this module's name first, so I'm starting here.

**Comment by otigon** [comment]
fixed on 4.2.40
