### ISSUE TITLE
[BUG] - Failure to remove underlying animations when dying condition is applied despite settings for AA

### ISSUE THREAD

**Issue by ThunderousLeft** [otigon/automated-jb2a-animations#607]
**Describe the bug**
Dying condition is applied and Dying, Prone, and Unconscious animations play, despite AA settings for removing nesting animations being enabled

**To Reproduce**
1. Apply dying condition to a creature

**Expected behavior**
Unconscious and prone animations are not also played

**Screenshots**
https://youtu.be/n69GvYNPgFo

**Setup:**
 - Foundry Version: 10.291
 - System Version: PF2e 4.9.3
 - Sequencer Version: 2.414
 - Automated Animations version: 4.2.32
 - Hosting Location: Local Windows 11 electrum app instance

**Active modules:**
- Advanced Macros
- Automated Animations
- FXMaster
- JB2A Patreon Complete Collection
- lib - color settings
- lib Themer 
- libWrapper
- PF2e Animations
- PF2e TokenMagic Integration
- Sequencer
- socketlib
- Token Magic FX
- Warp Gate

**Comment by otigon** [comment]
This is not anything A-A can fix. The PF2e system is not listing those as children of the dying condition, so there isn't anything I can do
