### ISSUE TITLE
[SYSTEM REQUEST] - ECLIPSE PHASE 2E (Bubz System)

### ISSUE THREAD

**Issue by PlasticMohawk** [otigon/automated-jb2a-animations#610]
Hello!

If you get a chance, it would be great if you could add support for the Eclipse Phase 2E Bubz System. https://github.com/Bubz43/ep2e/releases

I recognize you have other priorities; that said, if you could offer support for this, that would be great.

Thanks!

**Comment by otigon** [comment]
I don't personally add support for systems anymore (too many to support). It requires someone to issue a PR for the module to add it, and they would also be the ones to do maintenance on it when necessary
