### ISSUE TITLE
[BUG] - Fault in Animation Type making select box drop-downs not populate

### ISSUE THREAD

**Issue by MattBridger777** [otigon/automated-jb2a-animations#611]
**Describe the bug**
There appears to be a bug introduced since the last update. When I go into Automated Animations' window, select "Customi(s)e Item" and then try to select any Animation Type other than the default of "Melee", the select boxes for "Animation" don't always change to be what they should according to what was selected. For example, changing Animation Type to "On Token" and then changing Type to "Magic Sign" doesn't result in the list of options under Animation changing, it just stays on the default list of spells as if Type was still set to "Spells." 
This also appears to make the file chooser and other options for "Options", "Colo(u)r Tint", "Sound" and "Range Switch" stop working.

It appears that when the Animation Type is changed to be anything other than "Melee" the Console generates the error :
Uncaught (in promise) TypeError: $animation.meleeSwitch is undefined
[Detected 1 package: autoanimations]
    update MeleeSwitch.svelte:29
    update index.mjs:1270
    flush index.mjs:1234
    promise callback*schedule_update index.mjs:1185
    make_dirty index.mjs:2067
    ctx index.mjs:2105
    1 index.js:91889
    _updateSubscribers index.js:98
    set AnimationStore.js:50
    select_change_handler index.js:91686

Screenshots below
![Screenshot1](https://user-images.githubusercontent.com/92942471/226884023-5e7516df-4299-45b5-8d79-0901645c745b.png)
![screenshot2](https://user-images.githubusercontent.com/92942471/226884091-13c3e156-cb2a-4ad8-ada6-11242a33c750.png)
![sceenshot3](https://user-images.githubusercontent.com/92942471/226884110-19ec7be8-da9b-4a8f-9056-5cdee7faa61d.png)

**Setup:**
 - Foundry Version: 10.291
 - System Version: Pathfinder 1 0.82.5
 - Sequencer Version: 2.414
 - Automated Animations version 4.2.40
 - Hosting Location : Forge
 - Browser & version : Firefox 111.0

**Active modules:**
 - Sequencer
 - socketlib
 - Abron's Compendium Tools
 - Abron's Context Menu Library
 - Compendium Folders
 - libWrapper
 - Moulinette Core
 - Moulinette Tiles
 - My Shared Content
 - Pathfinder 1 Shared Compendium
 - Pathfinder 1e Archetypes and Abilities
 - Pathfinder 1e Content
 - Pathfinder 1e Statblock LIbrary
 - Quick Insert (Search widget)
 - sbc | PF1 Statblock Converter
 - The Forge

My thanks for your attention,
~Matt Bridger

**Comment by otigon** [comment]
The item menus have been troublesome lately. I'd recommend using only the Global menu for the time being

**Comment by otigon** [comment]
Oddly enough this looks like a Firefox issue specifically, as I don't have this issue on Chrome ( I was able to replicate the error on Firefox). I'll have to take a look again when I get time to see what I can do

**Comment by nyxalteria** [comment]
I'm having this issue on the foundry client itself

![image](https://user-images.githubusercontent.com/92659516/229372254-01e852d1-42dc-430d-920a-f1f5254c69d9.png)
![image](https://user-images.githubusercontent.com/92659516/229372271-9ef9020b-a836-46da-8559-9a7ee86888ae.png)
I'll change it to magic sign for example and the animations dropbox won't show the sign types, it'll show the spell animation types.

**Comment by otigon** [comment]
Firefox and the Foundry client are buggy with the module right. I'd recommend using Chrome for now till I can fix it

**Comment by otigon** [comment]
Or just use the global menu and not the on-item menu

**Comment by otigon** [comment]
I had some time to look at this today, and I think I have a fix in place. Will notify you when it is released later

**Comment by nyxalteria** [comment]
> I had some time to look at this today, and I think I have a fix in place. Will notify you when it is released later

Excellent, thanks.

**Comment by otigon** [comment]
4.2.42 is active, and *should* fix this issue. Please let me know if you experience any further errors
