### ISSUE TITLE
[FEATURE REQUEST] Allow GM to edit their client's Template Grids on Hover setting

### ISSUE THREAD

**Issue by finalfrog** [otigon/automated-jb2a-animations#614]
Pretty much self-explanatory. I find the player experience this setting provides much more enjoyable than the one I get when I'm a GM. It'd be nice to be able to use this setting when I'm GMing. Also it would allow using Force Client Settings to apply it to all players without them having to manually enable it.

**Comment by otigon** [comment]
I'm not sure I understand this request. This setting is already a client side setting, so users can choose to enable or disable it

**Comment by finalfrog** [comment]
When I'm logged in as GM this is what I see in settings menu for Automated Animations:

https://i.imgur.com/SUrAzPh.png

When I'm logged in as play this is what I see in settings menu for Automated Animations:

https://i.imgur.com/whbOFf4.jpeg

**Comment by finalfrog** [comment]
Sorry if the word "client" in the title made some confusion. To be clear I want to be able to enable the setting while playing as a GM.

**Comment by otigon** [comment]
You can already enable this as the GM too. Open your global menu, click Settings in the title bar: 
![image](https://user-images.githubusercontent.com/73318661/227669636-bc7a1389-3e72-4cfb-a615-edc495b70e7c.png)

**Comment by finalfrog** [comment]
Ah didn't see the inner setting menu. Thanks!
