### ISSUE TITLE
[FEATURE REQUEST] - Animation sound settings

### ISSUE THREAD

**Issue by ScyllPoesis** [otigon/automated-jb2a-animations#616]
**Is your feature request related to a problem? Please describe.**
Sort of? While playing with the new soundfx support is incredible, I've found that they're often too loud for my table's taste; generally they're fine, but so far a few have been overpowering any BGM or chatting in the moment. A couple (like produce flame) spike like crazy. This can be solved by manually going through each animation as they come up and they're not too numerous right now so it's not a major issue, but as the amount of animations with sound auto-rec'd grows, this could become something I consider disabling (which is a shame!). Additionally, one of my players may rather not listen to them at all to just focus on the table, but they love the visual flair of the animations.

**Describe the solution you'd like**
Just a couple module settings added, really. First would be a client-setting toggle to enable/disable the sound component of the animation at the module level. Second would be a global volume setting, that just multiplies against the animation volumes (so an animation set to 80% volume, with a global setting of 50%, would be played at 40% volume. 

**Describe alternatives you've considered**
Currently I have to listen to an ear-shattering explosion, pause the game to open the animations menu, find the offender, and adjust the volume during the session. Not ideal, and a reactive solution instead of a proactive solution.

Cheers!

**Comment by otigon** [comment]
Each sound section has it's own individual Volume control, but this is only a multiplier to the Foundry Global volume setting (Ambient or Interface, can't remember).

If a specific person wants Sounds to be turned off, they can do so inside their Sequencer settings. 
![image](https://user-images.githubusercontent.com/73318661/228236873-6e63c4d9-9b09-41a5-a569-045bf35b539d.png)

Outside of what is already provided there is nothing A-A can do for this, so closing this ticket
