### ISSUE TITLE
[BUG] - Play on Hit setting option doesn't appear to do anything

### ISSUE THREAD

**Issue by JulesVerne22** [otigon/automated-jb2a-animations#619]
**Describe the bug**
I have midi qol installed as well as automated animations and when selecting the only play on hit option, the animations occurs whether a hit occurs or not.

**To Reproduce**
1. Install the latest dnd5e system
2. Install the following modules: (midi qol, automated animations, jb2a, and any of their dependencies)
3. Create a world and launch it
4. Create a player character and a monster character
5. Give the player character fire bolt
6. Set the hits option in midi qol to "check - all see result"
7. Check the play only on hit option in automated animations
8. Start an encounter and roll fire bolt multiple times, you'll see the animation play on hits and misses

**Expected behavior**
I would expect the animation to play only when the chat message says hit.

**Setup:**
 - Foundry Version: v2.10.191
 - System Version: dnd5e v2.1.5
 - Sequencer Version: v2.414
 - Automated Animations version: v4.2.42
 - Hosting Location (Local, Forge, etc): Local
 - Browser & version: google chrome latest

**Active modules:**
 - Sequencer
 - socketlib
 - Active Token Effects
 - Active-Auras
 - Advanced Macros
 - Auto-Rotate
 - Automated Animations
 - Automated Evocations - Companion Manager
 - Better Roofs
 - Character Actions List dnd5e
 - Combat Booster: Turn Marker, Recent Actions and more
 - Cursor Hider
 - DDB-Importer: A D&D Beyond Integrator
 - DFreds Convenient Effects
 - Dice So Nice!
 - Dice Tray
 - DNDBeyond Character Sheet for 5E
 - Dynamic effects using Active Effects
 - FXMaster
 - Hero Creation Tool for DnD5E
 - JB2A - Patreon Complete Collection
 - Levels
 - lib - Color Settings
 - libWrapper
 - Magic Items
 - Item Macro
 - Midi QOL
 - Midi SRD
 - Minimal UI
 - Monk's TokenBar
 - Perfect Vision
 - PopOut!
 - Settings Extender
 - Simple Calendar
 - Times Up
 - Token Magic FX
 - Universal Battlemap Importer
 - Wall Height
 - Warp Gate

All modules on latest versions although I did revert DAE back to v23 in an attempt to fix the issue.

**Comment by otigon** [comment]
I'm pretty certain this setting was supposed to have been removed a while back. I have to change some of the Midi specific options up at some point, so I'll see if I can squeeze it back in, but going to close this out for now.
