### ISSUE TITLE
[BUG] - TYPE BRIEF DESCRIPTION HERE

### ISSUE THREAD

**Issue by AdjustableWrench** [otigon/automated-jb2a-animations#621]
**Describe the bug**
On item sheets for Level Up: Advanced 5th Edition, there is no "A-A" button to modify the animation per item

**To Reproduce**
1. Open any item 
2. See error

**Expected behavior**
That upon opening an item page, there should be a button in the title to open the item's A-A menu

**Screenshots**
![image](https://user-images.githubusercontent.com/129865182/229803123-b958c38c-1dc1-4b81-917f-1851376a35c8.png)

**Setup:**
 - Foundry Version: v10.291
 - System Version: Level Up: Advanced 5th Edition v0.10.5
 - Sequencer Version: 2.414
 - Automated Animations version: 4.2.42
 - Hosting Location: Local
 - Browser & version: Foundry Client

**Active modules:**
 - Sequencer
 - socketlib
 - Automated Animations

**Comment by otigon** [comment]
I forgot, this should be resolved as of version 4.2.43
