### ISSUE TITLE
[BUG] - Lag Spike when Unselecting Status Effects from Tokens PF2E

### ISSUE THREAD

**Issue by Gogfot** [otigon/automated-jb2a-animations#627]
**Describe the bug**
Using the pathfinder 2e system when you remove a status effect the lobby lags to the point of freezing for a few seconds, sometimes more than a few. This can be annoying if you have to remove multiple statuses and each one takes 3-7 seconds at a time freezing the lobby in the meantime.

**To Reproduce**
1. Load a lobby of pathfinder 2nd edition.
2. Select a character token.
3. Give character token a status from the token itself by selecting the "Assign Status Effect" icon at the right side of the token. Lets say Grabbed. This gives the character the following conditions : Grabbed, Flat Footed, Immobilized. 
4. Right click grabbed at the same area, in order to remove grabbed condition.
5. Lobby should slow down / freeze from anywhere 3-7 seconds.

**Expected behavior**
Ideally i'd expect no slowdown / freeze or a 1 second slowdown.

**Screenshots**

**Setup:**
 **- Foundry Version: [e.g. 9.238]**
 Version 10 Build 291
 **- System Version: [e.g. DND5e 1.5.7]**
Pathfinder 2nd Edition 4.10.4 
 **- Sequencer Version: [e.g. 1.0.0]**
2.414
 **- Automated Animations version** 
4.2.44
 **- Hosting Location (Local, Forge, etc)** 
Local hosting
 **- Browser & version [e.g. Google Chrome 98.0.4758.82]** 
Players are using firefox / chrome

**Active modules:**
![image](https://user-images.githubusercontent.com/28920832/231722176-1a07b854-38fe-483e-af43-3839eeca819d.png)
![image](https://user-images.githubusercontent.com/28920832/231722225-cc7f27e5-3817-43f6-a2e2-34dd9f466437.png)

**Additional context**
I did try re-doing the steps with having automated animations module turned off and the lobby did not freeze when adding / removing statuses. After turning the module back on the freezing times were between 2-4 seconds instead of 3-7. Unsure if that helps at all.

**Comment by otigon** [comment]
This isn't really anything I can help with. To stop this freezing, you can either disable all Active Effect type animations, or try using the Disable Nested effects option in the A-A settings to reduce the number of animations on screen.
