### ISSUE TITLE
Magic Missiles & The Future 

### ISSUE THREAD

**Issue by LionheadGaming** [otigon/automated-jb2a-animations#63]
There is a desire to see Magic Missile return to its triple cast baseline and it seems some desire to be able to specify the total dart count perhaps in the animation or if possible when it's cast. This problem if solved could potentially be expanded to other similar spells like Scorching Ray or Eldritch Blast. Additionally, there is a "Number of Loops for Explosion" general setting that could be set up as an improvisational tool for other animations that DMs might repurpose for monsters, traps, etc. A 'Loop Effect?' Check Box would be great for general usage.

**Comment by otigon** [comment]
I added the loop counter option for Magic Missile. I'm going to leave this issue active so I can remember to look at implementing something like that across the board

**Comment by otigon** [comment]
Should all be in the 0.5.0 release
