### ISSUE TITLE
[SYSTEM REQUEST] - Stars Without Numbers

### ISSUE THREAD

**Issue by Kilgrim1982** [otigon/automated-jb2a-animations#630]
Hi, hope you are doing fine!

First of all, love what you are doing! We use your system in a friends PF2 and my DND Games. 
I´m working on a server to get a SWN Sandbox Game running and tried to get this system working on it but sadly I can´t manage to do it.

Is it possible to get it working with wintersleepAi´s SWN Module ? [https://github.com/wintersleepAI/foundry-swnr]

Thanks a lot and have a great day!
Michael

**Comment by otigon** [comment]
System support needs to be added via Pull Request on GItHub. I don't have time available to take care of these inquiries sorry.
