### ISSUE TITLE
[SYSTEM REQUEST] - POKÉMON TABLETOP UNITED

### ISSUE THREAD

**Issue by Ellamental2** [otigon/automated-jb2a-animations#638]
https://github.com/dylanpiera/Foundry-Pokemon-Tabletop-United-System

Im happy to do this myself if you can offer some guidance on your preferred best practise etc we currently have some default animations within the system and if a custom animation isn't selected we would want that default animation to still play.

**Comment by otigon** [comment]
System support needs to be added via Pull Request on GItHub. I don't have time available to help with these
