### ISSUE TITLE
[FEATURE REQUEST] - Add option to set "Template Grids on Hover" for all players

### ISSUE THREAD

**Issue by nschoenwald** [otigon/automated-jb2a-animations#639]
My players are not very tech savvy and I DM a lot of one shots with various players. I don't want them to have to navigate through the menus themselves to set this option. It would be great if there was an option where I as a DM could set this for all players.
With other modules, I use the module "Force Client Settings" to set options for my players, but this is not possible here because the option is in the bespoke autorec menu.

**Comment by otigon** [comment]
Sorry, I don't have plans to offer functionality like that. All my settings are handled through the Typhon Runtime Library and I wouldn't even know where to begin to do that

**Comment by nschoenwald** [comment]
Couldn't you set the scope for the setting to 'world' or at least give it the option be set to world? It is currently set to client, which as far as I can see means that it is dependent one the user's browser cookies or local storage.
