### ISSUE TITLE
[BUG] - (V11) passing arguments has changed

### ISSUE THREAD

**Issue by Tupsi** [otigon/automated-jb2a-animations#646]
**Describe the bug**
V11 made it possible to pass arguments directly to macros now without the need from the module Advanced Macros (although in a different format object instead of array). Consequently the author of Advanced Macro removed that feature from AM altogether.
Macros like JB2A Melee_Attack_Advanced_A-A_v5 rely on data passed over which no longer get passed along (because there is no more args array the moment you update the Advanced Macro module to v11 compat).

**To Reproduce**
1. update to foundry v11
2. update modules
3. use jb2a macro Melee_Attack_Advanced_A-A_v5 in an A-A
3a. just use a macro for a-a with a console.log(args) inside to see args is missing (there is scope now though)

**Expected behavior**
A-A should use the new method and passing along stuff in the scope object of core foundryvtt.

**Screenshots**

**Setup:**
 - Foundry Version: 11.299
 - System Version: DND5e 2.2.1
 - Sequencer Version: 3.0.9
 - Automated Animations version: 4.2.53
 - Hosting Location (Local, Forge, etc): own linux server
 - Browser & version [e.g. Google Chrome 98.0.4758.82]: chrome 113

**Active modules:**
 - Sequencer
 - socketlib
 - advanced macros (useless now though)
 - jb2a

**Comment by Txus5012** [comment]
Seems like this change is affecting Active Effect Macros too.
![Active Effect Macro](https://github.com/otigon/automated-jb2a-animations/assets/87753744/b8e9723c-fb99-4ffd-937c-2b151e3a53d8)

**Comment by otigon** [comment]
should be resolved in latest A-A and Sequencer now. Macros should work just the same way as before, we are passing args
