### ISSUE TITLE
[FEATURE REQUEST] - Allow using module without a canvas

### ISSUE THREAD

**Issue by mclemente** [otigon/automated-jb2a-animations#649]
**Is your feature request related to a problem? Please describe.**
There is no way to use the module just for sounds without a canvas.

**Describe the solution you'd like**
Change the if-condition on https://github.com/otigon/automated-jb2a-animations/blob/main/src/system-support/aa-chatmessage.js#L27 (and the other 7 places where that code is replicated) to ignore a missing token if `handler.animationData.soundOnly?.sound?.enable` is true.

Example:
```diff
- if (!handler?.item || !handler?.sourceToken) {
+ if (!handler?.item || (!handler?.sourceToken && !handler.animationData.soundOnly?.sound?.enable)) {
  debug("No Item or Source Token", handler);
  return;
}
```

**Describe alternatives you've considered**
Move the check for a token from all instances where the code is replicated to trafficCop, since that centralizes the check.

**Additional context**
This is meant for chat-only game where only the sounds are important. I've noticed it can be circumvented by the GM making a scene only them have access to, but I feel that is "hacky" and unnecessary since the token shouldn't be important for a sound-only animation.

**Comment by otigon** [comment]
Sorry ,this is an Animation module first and foremost. I see no reason to add checks to treat it as an audio module for use on non-canvas worlds. I'd look at macros
