### ISSUE TITLE
[BUG] - Disabled A-A disallows to use Animate Dead spell 

### ISSUE THREAD

**Issue by Kayne** [otigon/automated-jb2a-animations#652]
**Describe the bug**
When Player disabled Automated Animations (because of performance issues), the Animate Dead doesn't work properly. The spell is displayed in chat, but the summons popup choice doesn't show up and logs says `Automated Animations
Animations are Disabled from the Automated Animations Settings`.

**To Reproduce**
1. As player, disable Automated Animations 
2. Cast Animate Dead spell
3. See nothing happens, and there's warning in logs

**Expected behavior**
Summon popup should appear and allows to summon token without any animations.

**Setup:**
 - Foundry Version: 10.291
 - System Version: PF2e 4.12.9
 - Sequencer Version: 3.0.10
 - Automated Animations version 4.2.53
 - Hosting Location: nodejs on server
 - Browser & version doesn't matter, same behaviour on all

**Active modules:**
Advanced Macros v;
Autocomplete Whisper v;
Automated Animations v;
Award XP v;
Cautious Gamemaster's Pack v;
Chat Images v;
Combat Enhancements v;
Dice So Nice! v;
Dice Tray v;
Drag Ruler v;
Enhanced Terrain Layer v;
Escape Window v;
Foundry VTT Anniversary Dice Set by The Rollsmith v;
Health Estimate v;
Image Hover v;
Initiative Double Click v;
Jam and Jax's NPC Ancestry Abilities v;
Jam and Jax's NPC Index: Specialists v;
Jam and Jax's NPC Index: Spellcaster v;
Jam and Jax's NPC Index: Warriors v;
JB2A - Patreon Complete Collection v;
libWrapper v.1;
LiveKit AVClient v;
Pathfinder 2e: Abomination Vaults v;
Pathfinder Beginner Box v;
Pathfinder Token Pack: Bestiaries v;
Pathmuncher: Pathbuilder character importer for PF2e v;
Perfect Vision v;
PF2e Animations v;
PF2e Companion Compendia v;
PF2e Dorako UI v;
PF2e Drag Ruler Integration v;
PF2E Exploration Effects v;
PF2e Giveth v;
pF2E Keybind Menagerie v;
Pf2E Modifiers Matter v;
PF2e Staves v;
PF2e Target Damage v;
PF2e Workbench v;
Polyglot v;
routinglib v;
Safety Tools v;
Sequencer v;
socketlib v;
Spellarena | Battlemaps Pack v;
Tidy UI - Game Settings v;
Token Action HUD Classic v;
Token Info Icons v;
Tokenizer v;
Token Magic FX v;
Token Mold v;
Warp Gate v;

**Comment by otigon** [comment]
This sounds like intended behavior for Automated Animations. If you have A-A disabled client side, nothing will run, and it sounds like you are expecting the macro to run.

To fix this, the player needs to enable Automated Animations. If the visuals are bogging them down, have them disable Effects for themselves in the Sequencer module settings. That way A-A will still run your macros, but the visuals will not be played for that client

**Comment by Kayne** [comment]
Oh, ok. Now I understand. The name of this and related module mislead me, because I thought this is about animations and turns out, that PF2e Animations **also** provides macros for handling summons. I was under the impression, that the popup to select summon is a pf2e core functionality. I wasn't expecting this from the animations module. My bad, didn't read the module description closely enough.
