### ISSUE TITLE
[BUG] - Syntax Error when trying to run certain animations

### ISSUE THREAD

**Issue by OrionTheOtter** [otigon/automated-jb2a-animations#653]
**Describe the bug**
When i try to run certain animations gives me the error
VM11397:24 Uncaught (in promise) SyntaxError: undefined. Identifier 'token' has already been declared
[Detected 3 packages: advanced-macros, lib-wrapper, sequencer]
    at new AsyncFunction (<anonymous>)
    at #executeScript (foundry.js:22632:16)
    at Macro.execute (foundry.js:22584:35)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Macro.prototype.execute#advanced-macros (main.js:53:14)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Macro.prototype.execute#0 (libWrapper-wrapper.js:189:20)
    at Proxy.<anonymous> (sequencer.js:187:25)
    at async Proxy.run (func.js:23:5)
    at async Proxy._execute (func.js:31:5)
    at async Proxy.play (sequencer.js:67:23)

**To Reproduce**
For this specfic one I'm trying to put the stumbling stance animation on one of my tokens

**Expected behavior**
Should be giving them a rocking motion with bubbles but instead just defaults to a random cure animation

**Setup:**
 - Foundry Version: 11 build 302
 - System Version: PF2e 5.0.1
 - Automated Animations 4.2.60
 - Advanced Macros 2.0.1
 - Lib-wrapper 1.12.12.1
 - sequencer 3.0.11

**Additional context**
Was working fully before updating to V11 but now just some of them are working i suspect it's the ones that dont require it to call on JB2A animations

**Comment by otigon** [comment]
Is this running a macro for the animation section?

**Comment by otigon** [comment]
If the faulty animation sections are using macros, you need to fix this in the macro. If that is the case please close this issue

**Comment by OrionTheOtter** [comment]
i didn't make this macro though it came straight from your automated animations

**Comment by otigon** [comment]
> i didn't make this macro though it came straight from your automated animations

Automated Animations does not provide any macros, that would have come from another module. My guess is you use/used the PF2e Animations module, in which case it could be useful to log that as a bug on their GitHub repository
