### ISSUE TITLE
[FEATURE REQUEST] - Being able to automatically display spell effects on templates and spells added to the sheets spellbook via magic items module or magic items 2 fork

### ISSUE THREAD

**Issue by SirAron111** [otigon/automated-jb2a-animations#660]
**Is your feature request related to a problem? Please describe.**
Na It's just that the spells if added from a magic item don't have the animations, the spells added to the sheet's spell book have when cast.

**Describe the solution you'd like**
The Animation to display if possible.

When a magic item adds a spell to the sheet, it's displayed like this, but doesn't trigger the automated name recognition it seems.
![Unbenannt](https://github.com/otigon/automated-jb2a-animations/assets/39855956/16c2b864-03d1-460d-aa70-d46b32d9a124)
Even if the spell is on the sheet, it doesn't do it. (The ones on the spell list work fine, just the ones at the bottom below don't seem to get recognized by the name detection when used. Maybe they aren't detected)
![Unbenannt2](https://github.com/otigon/automated-jb2a-animations/assets/39855956/5ea8e8aa-9078-4e60-b58c-82e122381bce)

**Comment by otigon** [comment]
What game system, and what modules are handling that magic item spell thing?

**Comment by SirAron111** [comment]
Its dnd 5e and the module would be called "magic items" in my case "magic items 2" which is the exact same just a fork for v11.

**Comment by otigon** [comment]
A-A has never reliably worked with the Magic Items module. They do things in a very strange way, and I can't reliably get access to the item being used

**Comment by SirAron111** [comment]
a ok good to know.
