### ISSUE TITLE
[SYSTEM REQUEST] - Mutants and Masterminds 3E

### ISSUE THREAD

**Issue by Dadrak** [otigon/automated-jb2a-animations#663]
Hi there,

It would be really neat if you would consider adding support for Mutants and Masterminds 3E: https://foundryvtt.com/packages/mutants-and-masterminds-3e

The request to make the system compatible with your module has also been made on the Github of the system dev.

As always thank you for your work and have a nice day :)

**Comment by otigon** [comment]
I don't add system compatibility anymore, this needs to be done via PR by someone else
