### ISSUE TITLE
[BUG] - Animations only play when damage is rolled

### ISSUE THREAD

**Issue by Glenn-v-W** [otigon/automated-jb2a-animations#665]
**Describe the bug**
Whenever using automated animations for a spell or ability, the associated animation only plays when damage is rolled, not when the spell or ability is activated, causing non-damage related animations to not be played.

**To Reproduce**
1. Go to character sheet
2. Click on ability with automated animation enabled, but no damage rolls
3. No animation is played
4. Click on ability with automated animation enabled, and which includes a damage roll
6. Animation is played
7. Adjust settings to roll damage manually
8. Click on ability with automated animation enabled, and which includes a damage roll
9. No animation is played
10. Click on damage roll
11. Animation is played

**Expected behavior**
Animations play even when ability or spell does not contain damage roll.

**Setup:**
 - Foundry Version: 10.291
 - System Version: DND5e 2.2.2
 - Sequencer Version: 3.1.1
 - Automated Animations version: 4.2.60
 - Hosting Location: Forge
 - Browser & version: Opera 99.0.4788.88

**Active modules:**

-  About Time
- Advanced Macros
- Ambient Doors
- Automated Animations
- Better Roll Tables
- Better Roofs
- CodeMirror
- Combat Booster: Turn Marker, Recent Actions and more
- Combat Enhancements
- Combat Utility Belt
- Compendium Folders
- Condition Automation
- Cozy Player
- Crash's Tracking & Training (5e)
- D&D5e Animations
- Deselection
- DFreds Droppables
- Dice So Nice!
- Dice Tray
- Drag Ruler
- Drag Upload (Get Over Here!)
- Dynamic Active Effects SRD
- Dynamic effects using Active Effects
- Dynamic Illumination
- Easy Target
- Enhanced Terrain Layer
- Find the culprit
- Forien's Quest Log
- Foundry Community Macros
- Foundry Community Tables
- FXMaster
- GM Notes
- Grid Scaler
- Hey, Wait!
- Iconizer
- Initiative Double Click
- Inline Webviewer
- Jack Kerouac's Animated Spell Effects
- JB2A - Patreon Complete Collection
- Less Fog
- Let Me Roll That For You!
- lib - Color Settings
- libWrapper
- Lichtgeschwindigkeit (Lightspeed)
- LootsheetNPC5e
- Magic Items
- Math.js
- Michael Ghelfi Studios Audio Pack
- Midi QOL
- Mob Attack Tool
- Monk's Active Tile Triggers
- Monk's Bloodsplats
- Monk's Combat Marker
- Monk's Little Details
- Monk's Scene Navigation
- Monk's Sound Enhancements
- Monk's TokenBar
- Monk's Wall Enhancement
- Multilevel Tokens
- Next Up
- Perfect Vision
- Pin Cushion
- Pings
- Polyglot
- PopOut!
- Quick Insert - Search Widget
- Ready Set Roll for D&D5e
- Sequencer
- Settings Extender
- Simple Calendar
- Skill Customization for D&D5e
- socketlib
- SortableJS vfvtt1
- SoundBoard by Blitz
- SoundBoard Pack - Blitz Free Pack
- SoundBoard Pack - Community
- SoundFx Library
- Split Journal
- Tabletop RPG Music
- Tagger
- The Forge
- The Forge: More Awesomeness
- The Furnace
- Tidy5e Sheet
- Tidy UI - Game Settings
- Token Action HUD Classic
- Token Attacher
- Token Info Icons
- Tokenizer
- Token Magic FX
- Token Mold
- Token Stamp 2 for Foundry VTT - RollAdvantage.com
- Token Tooltip Alt
- Trigger Happy
- Universal Battlemap Importer
- Warp Gate
- World Anvil Integration
- zSync

**Additional context**
Might be an incompatibility between modules or some setting incorrectly set, but so far I'm not finding the cause.

**Comment by otigon** [comment]
Your first step in a situation like this should ALWAYS be to test with only A-A and it's dependencies active. You have too many modules for me to help you do the troubleshooting. Please create a new issue after you have done this
