### ISSUE TITLE
PF1e - Pathfinder Alt Sheet messes with the A-A tab

### ISSUE THREAD

**Issue by Gazkhan** [otigon/automated-jb2a-animations#68]
@Skrall was looking for the Animation tab and couldn't find it until deactivation of all other modules and it fixed the issue.
There seems to be a conflict with the module "Pathfinder Alt Sheet".

**Comment by otigon** [comment]
I've activated only Pathfinder Alt Sheet and Automated animations. I am able to open the Item "edit" setting and the A-A Tab is present. I am unable to replicate this issue.

**Comment by Gazkhan** [comment]
Ok, I'll get back in touch with skrall and I'm closing the issue. Thanks.
