### ISSUE TITLE
Magic Missile fix for 0.8.5

### ISSUE THREAD

**Issue by yahavatar** [otigon/automated-jb2a-animations#69]
Otigon,

Had to change magic-missile.js file to get to run.

Line 83 was:
    let globalDelay = game.settings.get("automated-jb2a-animations", "globaldelay");
Changed to:
   let globalDelay = game.settings.get("autoanimations", "globaldelay");

Line 155 was:
    if (game.settings.get("automated-jb2a-animations", "tmfx")) {
Changed to:
    if (game.settings.get("autoanimations", "tmfx")) {

This is a great module!!!! Thank you for the time you put in to create this!!!

Yah.

**Comment by otigon** [comment]
Thanks for catching that! I thought I caught all those. I'll push that on the next update

**Comment by otigon** [comment]
Fixed this on 0.3.53, thanks again
