### ISSUE TITLE
[BUG] Localized 5e doesn't have item AA tab

### ISSUE THREAD

**Issue by Gieff** [otigon/automated-jb2a-animations#72]
With the backward compatibilty update the AA tab doesnt appear within my 5e localized system.

I found that in item-sheet-config.js:14 with the 5e system `typeLoc = data.itemType` will be a localized string, and will never be found inside the `acceptedTypes` array. 
Example, a _spell_ item in my case will be _incantesimo_, and not _spell_.

`data.entity.type` or `data.item.type` both work fine in 5e 1.2.4.
`data.item.type` works only in 5e 1.3.2

Also, changing `data.itemType` to `data.item.type` a feature item will be _feat_ and not  _feature_

tested with foundry/5e 0.7.10/1.2.4 and 0.8.5/1.3.2

**Comment by CarnVanBeck** [comment]
can confirm, the A-A tab is missing if localized (german in my case) but there in english

**Comment by otigon** [comment]
I'll get this sorted today

**Comment by otigon** [comment]
Version 0.3.59 switches this to data.item.type (for 5e) to avoid localization clashes.
