### ISSUE TITLE
Using Mass Cure Wounds with TMFX causes server instability

### ISSUE THREAD

**Issue by megahead11** [otigon/automated-jb2a-animations#74]
It seems like when you have a large amount of creatures targeted from the template (like from MIDI), the TMFX will play on all of the selected targets and cause some of the TMFX animations to hang or lock up the client; 

Here's some examples:

After using it, the animations will stick
https://gyazo.com/2c3258db8a12c42c3d2eb425d62733d0.mp4

The server starts to hang, making you unable to move tokens; eventually the client/server may either just be stuck or crash after a few minutes. https://gyazo.com/72572f9c601df95b2d3fb895a6b6031b.mp4

Tested both on remote hosted @ chrome and electron.

**Comment by otigon** [comment]
Is is related to large numbers of tokens being the targets of animations. I'll look at ways to reconfigure the animations to reduce this load, or set a limit on targets

**Comment by otigon** [comment]
This should be more stable now on the 0.5.0 release
