### ISSUE TITLE
Compendiums Not Showing

### ISSUE THREAD

**Issue by Volksters** [otigon/automated-jb2a-animations#79]
The macros are not showing up in my compendium folders at all. JB2A's folders are, however.

**Comment by otigon** [comment]
I'm unclear on this issue. I have no macro compendiums in Automated Animations

**Comment by Volksters** [comment]
Huh, I saw someone who showed me a compendium with your macros on them.

**Comment by otigon** [comment]
That is probably this module, which is a manual installation: https://github.com/otigon/otigons-animation-macros

**Comment by Volksters** [comment]
That was it! Thank you. Is it not included in the main module?

**Comment by otigon** [comment]
No, that is separate. I created Automated Animations to do away with all the pesky macros lol.
