### ISSUE TITLE
The animations of Disintegrate, Shatter, and Thunderwave do not render as expected under certain conditions.

### ISSUE THREAD

**Issue by dstein766** [otigon/automated-jb2a-animations#8]
I've found that, with midiqol enabled and Automated Animations set to "Only play animation on Damage Rolls" that the Disintegrate, Shatter, and Thunderwave animations do NOT play as expected.

I believe this is a more detailed description of the same thing discussed in Issue #5.

Test environment uses ONLY these modules:
-FVTT 0.7.9
-DND5E 1.2.4
-automated-jb2a-animations--v0.1.9;
-fxmaster--v1.0.3;
-jb2a_patreon--v0.1.5;
-midi-qol--v0.3.88;
-tokenmagic--v0.4.4;

Steps to Repro - **All tests run as DM**:
1. Enable the above set of mods (**except for midiqol**, which starts DISABLED)
1. Set Automated Animations settings as shown in the screencap.  Leave "Only play animations on Damage Rolls" UNCHECKED.
![image](https://user-images.githubusercontent.com/24942951/111206994-58641d00-8586-11eb-9096-8e3d541954d5.png)
1. Using a token that has DISINTEGRATE (and, optionally, Shatter, and Thunderwave) PLUS Fire Bolt, target a 2nd token.
1. Cast FIRE BOLT and click Attack button to roll a normal attack.
   EXPECTED: Animation renders when the ATTACK is resolved (regardless of whether or not attack actually hits)
   ACTUAL:   As expected.
   Roll Damage...
   EXPECTED: No animation.
   ACTUAL:   As expected.
1. Repeat test, using DISINTEGRATE.
   EXPECTED: Animation renders when the item is rolled (since there's no Attack button that needs to be pressed).
   ACTUAL:   As expected.
   Roll Damage...
   EXPECTED: No animation.
   ACTUAL:   As expected.
1. TURN ON "Play Attack Animations On Damage Rolls Only" and Reload Application.  Leave midiqol DISABLED.
   COMMENT: I was surprised to see the wording on this option change.  When midiqol is loaded this reads "Only play animations on Damage Rolls".
1. Repeat FIRE BOLT attack.   
   EXPECTED: Animation won't play until Damage button is clicked.
   ACTUAL:   As expected.
1. Repeat DISINTEGRATE attack.
   EXPECTED: Animation won't play until Damage button is clicked.
   ACTUAL:   As expected.   
1. **ENABLE midiqol.  Confirm BOTH "Only play..." settings are UNCHECKED.**  Full midiqol settings below.
1. Repeat FIRE BOLT test.
   EXPECTED: Animation renders at time of attack, regardless of whether it hits or not.
   ACTUAL:   As expected.
   Roll Damage...
   EXPECTED: No animation.
   ACTUAL:   Animation shown again.  (Hmmm...probably not a bug, just wrong expectation by me)
1. Repeat DISINTEGRATE test.
   EXPECTED: Animation renders when the item is rolled (since there's no Attack button that needs to be pressed).  (NOTE: This is my expectation since I haven't specifically configured to force animation only on damage rolls...so it should react the same with midiqol enabled as it did with midiqol disabled).
   ACTUAL:   FAILURE.  Animation did NOT show.
   Roll Damage...
   EXPECTED: No animation.  
   ACTUAL:   **FAILURE**.  Animation shows. (NOTE: Although this entire test didn't meet my expectations, it DID ultimately result in an animation...just not when I expect/believe it should have.  The behavior I'm observing for this test is the EXPECTED behavior for this test described three steps below!)
1. Turn ON "Only play animations on Damage Rolls".  Reload Application.
1. Repeat FIRE BOLT test.
   EXPECTED: No animation.
   ACTUAL:   As expected.
   Roll Damage...
   EXPECTED: Animation plays.
   ACTUAL:   As expected.
1. Repeat DISINTEGRATE test.
   EXPECTED: No animation at time of item being rolled.
   ACTUAL:   As expected.
   Roll Damage...
   EXPECTED: Animation plays.
   ACTUAL:   **FAILURE**.  Animation did NOT play. 

![image](https://user-images.githubusercontent.com/24942951/111207734-374ffc00-8587-11eb-9141-d73a9ecf4924.png)
![image](https://user-images.githubusercontent.com/24942951/111207768-4040cd80-8587-11eb-83c5-c79640f6a4a2.png)
![image](https://user-images.githubusercontent.com/24942951/111207795-49319f00-8587-11eb-9bbe-b844069b6ae8.png)
![image](https://user-images.githubusercontent.com/24942951/111207810-4f278000-8587-11eb-8923-4264bf2bd107.png)
![image](https://user-images.githubusercontent.com/24942951/111207828-564e8e00-8587-11eb-8e9a-9597e4fceeef.png)
![image](https://user-images.githubusercontent.com/24942951/111207856-5cdd0580-8587-11eb-906b-eba9f23cd77f.png)
![image](https://user-images.githubusercontent.com/24942951/111208051-8433d280-8587-11eb-858b-7071c25321e3.png)
![image](https://user-images.githubusercontent.com/24942951/111208074-8a29b380-8587-11eb-91f9-2656cbce28b7.png)

**Comment by otigon** [comment]
I logged the issue with Tim on the Midi-QOL Gitlab. He responded that this will be fixed on Midi v 0.3.89 release
