### ISSUE TITLE
Request: Animation on Critical Hit

### ISSUE THREAD

**Issue by abominablerob** [otigon/automated-jb2a-animations#80]
I just think it would be cool to be able to set an animation for a critical hit, like an explosion or colored variant. Just a suggestion, great work!

**Comment by otigon** [comment]
I have a Critical Hit / Critical Miss animation implemented currently with Midi-QOL / DnD 5e only. I do plan to expand that functionality to do more stuff, but is a little lower on the priority table

**Comment by abominablerob** [comment]
I had no idea, nor my other gm friend.  Will take a look tonight. Thanks!

**Comment by otigon** [comment]
It is very basic as it is currently implemented. It will only play an animation on the Source Token when a Fumble or Crit is rolled
