### ISSUE TITLE
Feature Change: Token Magic FX update

### ISSUE THREAD

**Issue by otigon** [otigon/automated-jb2a-animations#81]
Remove all Token Magic FX from A-A
Add in A-A supplied presets for TMFX 
Add TMFX Preset dropdown option on A-A tab, with delay start and delay delete settings

**Comment by CaosFR** [comment]
First, thanks for your great and easy to use module.

I would like to know if they is a way to use the "Tokenmagic" module from Feu-Secret in A-A ? When I check "Custom" option, it's looking for a file path but "Tokenmagic" is macro isn't ?

Thanks

**Comment by otigon** [comment]
I was planning on adding the option in earlier this year, but that fell to the wayside. I'm uncertain when or if I'll have time to add that in, but currently it is unable to support TMFX preset filters

**Comment by CaosFR** [comment]
Thanks for your effort, hope you will realase this option one day :)
