### ISSUE TITLE
Item sounds with spells

### ISSUE THREAD

**Issue by Bryn1701** [otigon/automated-jb2a-animations#84]
Really enjoying this module, having lots of fun with it. As the title says. There is an issue when Item sounds are attached to a spell. It just doesn't play. I have tried to remove everything bar the 2 modules and still nothing effects it. But attaching it to a weapon or feat and it works fine. Foundry version 0.8.6 and DnD5e version 1.3.3

**Comment by otigon** [comment]
Is there an animation set to play with the spells that no sounds play with?

**Comment by Bryn1701** [comment]
Aha! That did the trick. I thought it was independent of the spell effects. Thanks for the quick reply. I also had to turn down the volume to 3, because it was shattering my ear drums and distorting itself.  And yes I would like to have item sounds regardless of the animation chosen. Somethings just need sounds. And with Maestro broken in 0.8.6 I believe people will have this just for the sounds alone! Good job!

**Comment by otigon** [comment]
I keep forgetting to set the default sound to 2 instead of 25. It really gets loud fast. I'll leave this open to remember to reconfigure sounds

**Comment by otigon** [comment]
should be fixed as of 0.3.65
