### ISSUE TITLE
[Feature] Crit/Miss for external integrations

### ISSUE THREAD

**Issue by Moerill** [otigon/automated-jb2a-animations#89]
Heya, 
i'm back with a small feature request/suggestion to enhance external integration:
Add the critical hit and miss option to the function call.  
How?  
E.g. the new function call could look something like this:
``AutoAnimations.playAnimation(sourceToken, targets, item, options)`` where ``options`` is an object, possibly looking like this:
``{crit: true/false, hit: true/false}`` (Thinking about it i'd probably prefer a "hit" flag, with your module interpreting it as it wants. E.g. only showing animations on a hit or show the miss label. Whatever  the settings are set to)  
This approach has the advantage of
a) being easily extendable without breaking the signature
b) Your module can decide what to do with the information given. (E.g. respect all settings set by your module.)
c) not breaking old module integrations. Thanks to the "beauty" of JS, you don't have to worry about not having the right amount of parameters...  So if you implement it using default paramaters, e.g. like this it won't break previous usages of your function: 
```
AutoAnimations#playAnimation(sourceToken, targets, item, {crit = false, hit = true}={}) {
  // your Code
}
```
Thanks for all your hard and awesome work! :)

**Comment by otigon** [comment]
I have a few items I'm finishing up work on right now, but should be able to get to this soon

**Comment by otigon** [comment]
Finally did my re-write, so I'll get to this soon

**Comment by otigon** [comment]
Hey sorry for the super delay on this, I completely lost track of it. Someone put in a Pull Request for adding something similar to this and it's live in version 1.2.8.

You can pass it an array of Hit Targets, and have the option to override the Play on Miss setting in A-A to activate it. Details at https://github.com/otigon/automated-jb2a-animations/pull/335#issue-1113015632 

Does this work for what you were envisioning, or can I add in more options to help?

**Comment by Moerill** [comment]
Hi, thanks for reminding me of this request xD

I've been kind of busy for the last many months and am still for at least 1 month, before i can take a look at module development again. So I'm kind of out of the game for the time being.

But: it does look correct, i think. I'll just close this issue and when i get back to working on my stuff and probably integrating this update and notice something missing i'll just open up something new.
