### ISSUE TITLE
global delay in animations to support Dice So Nice

### ISSUE THREAD

**Issue by apoapostolov** [otigon/automated-jb2a-animations#9]
Suggested by Brother Sharp#6921

I wanted to suggest a global delay in animations that the GM can set.
This is so that it can be easily fit to whatever dice so nice speed that game is using, so that the animations are played after they look at the 3D dice for example

**Comment by otigon** [comment]
Are you using any other rolling Mods like Better Rolls, Midi-QOL, Mars or MRE?

DSN, be default, causes the chat card to be delayed until the 3D Die roll is completed. This should already have the effect you are looking for.

**Comment by otigon** [comment]
Global Delay setting for A-A is now live
