### ISSUE TITLE
A-A Tab not showing in Item sheets

### ISSUE THREAD

**Issue by YaruKo** [otigon/automated-jb2a-animations#90]
Yesterday I updated my foundry version to 0.8.6 and also reinstalled AA and  everything but since the update there is no A-A Tab in all of my items, spells etc. I tried reinstalling all modules, deactivating all modules except AA and its dependencies but nothing helped. I'm using the latest version of 5e. Also all the animations I set up in 0.7.10 are still working like melee attacks etc but I can't add more.

Sry if this is the wrong place to put this.

**Comment by otigon** [comment]
Can you check your console (F12) and see if any error messages occur when you open the item sheet?

**Comment by YaruKo** [comment]
I just checked it says: "Uncaught TypeError: self.webSocket.json is undefined" when I open an Item sheet.

**Comment by otigon** [comment]
Have you tested without any other modules active?
Checking for information:
1. Foundry version 0.8.6
2. 5e version 1.3.3
3. Automated Animations version 0.3.64

Also, if you are on the Forge you need to install Automated Animations from the Bazaar on the webpage, There are issues with the old version still sticking around

**Comment by YaruKo** [comment]
Installing via the Bazaar fixed it! 
It always installed the 0.3.28 version before when you install it via foundry but now it works and the A-A tab is back! Thank you very much!!

**Comment by otigon** [comment]
Sweet, glad it worked out. I'll see about contacting the Forge personnel to remove the older version
