### ISSUE TITLE
Does not work with SWADE as is advertised in foundry App

### ISSUE THREAD

**Issue by TheMOELANDER** [otigon/automated-jb2a-animations#92]
I have tried to make this run in foundry 0.7.9, 0.7.10, and 0.8.6 with the SWADE system.
In the module list this module is listed as being compatible with SWADE. It never worked even with keeping in line with all instructions.

**Comment by otigon** [comment]
Have you tested with just Automated Animations active to see if another module is interfering? I don't seem to have any problems or errors on my end.

Check the console (F12) for errors while testing

**Comment by TheMOELANDER** [comment]
Okay... I am using Foundry 0.8.6 rn and I did as you asked. It runs on a naked SWADE. So I tried again with the console activated in my customized SWADE game: This is the output from one roll. I used BetterRolls 2 and Swade-Tools if that matters?
![consoleoutputaa](https://user-images.githubusercontent.com/85022573/121261763-6db1c480-c8b3-11eb-8788-9a01f9473d97.PNG)

**Comment by otigon** [comment]
The interference is most likely with Better Rolls, as that will change the data being passed in the Chat Message, which Automated Animations uses to get the item ID, attack vs damage roll, etc.

I'll take a look at that module, but if it's anything like the Better Rolls for DnD5e it's very difficult for me to add compatibility with it.

If all else fails, I have an exposed function that the Better Rolls for SWADE author could implement in their module to call the animations. This is detailed on the GitHub readme near the bottom

**Comment by TheMOELANDER** [comment]
Thanks a lot. I will tell them. If I would do my own animation, could I implement it?

**Comment by otigon** [comment]
your own animation? Like using a webm file? A-A currently is only able to use JB2A animations. Using custom user animations is something that's on the roadmap, but much further down the line

**Comment by otigon** [comment]
@brunocalado the issue with the Actor Sheet has to do with the system CSS I'm assuming. I'll see if there is anything I can do to prevent it on my end.

**Comment by brunocalado** [comment]
I can make some of the effects work with the default chat. But, it don't work with better roll 2 module.

**Comment by otigon** [comment]
I'll take another look soon to see if I can get it to work with Better Rolls 2, but if it's anything like the BR for 5e, it will be nigh impossible. I'll check tho

**Comment by otigon** [comment]
@TheMOELANDER custom animations are now useable as of 0.5.0 for most options.

@bruncalod I'm going to close this issue, but I'll not on my bug list to take a look at Better Rolls

**Comment by brunocalado** [comment]
> @bruncalod I'm going to close this issue, but I'll not on my bug list to take a look at Better Rolls

bette rolls 2 dev is very friendly. Maybe he can also help

**Comment by brunocalado** [comment]
https://github.com/javierriveracastro/betteroll-swade/issues/278


Error:
![image](https://user-images.githubusercontent.com/4999783/127505490-0bb0a6a6-20a8-4ed2-9d04-7273eafdf285.png)

```
name-conversions.js:5 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at nameConversion (name-conversions.js:5)
    at new GeneralAnimHandler (generalAnim-handler.js:105)
    at Function.playAnimation (autoAnimations.js:381)
    at eval (eval at run_macros (item_card.js:557), <anonymous>:3:30)
    at eval (eval at run_macros (item_card.js:557), <anonymous>:7:37)
    at run_macros (item_card.js:559)
    at roll_item (item_card.js:692)
    at async HTMLButtonElement.<anonymous> (item_card.js:290)
```

**Comment by brunocalado** [comment]
This could help: https://github.com/javierriveracastro/betteroll-swade/issues/278

**Comment by otigon** [comment]
I think I see where that error is occuring. I'll look at getting it fixed today
