### ISSUE TITLE
Request: SW5e System

### ISSUE THREAD

**Issue by gravagehulk** [otigon/automated-jb2a-animations#95]
The Star Wars 5e system is basically just D&D 5e with laser guns and Wookies. It would be great to see it supported. I'd love to see blaster fire bouncing around the map during combat.

Thanks!

**Comment by otigon** [comment]
I'll try to take a look and see if I can add compatibility

**Comment by gravagehulk** [comment]
> I'll try to take a look and see if I can add compatibility

Thanks! I know it's not a super popular system. I just thought it might be easy since it's basically 5e. Even if I have to manually set the effects for each weapon/force power, that would still be something.

**Comment by otigon** [comment]
Is this the Star Wars FFG system?

**Comment by gravagehulk** [comment]
> Is this the Star Wars FFG system?

Yes sir.

**Comment by gravagehulk** [comment]
> Is this the Star Wars FFG system?

Sorry, I misread. This is not the FFG system. It's Star Wars 5e:

https://github.com/unrealkakeman89/sw5e

**Comment by gravagehulk** [comment]
> Ok perfect. I'll take a look at the system this week. I could only find the SWFFG system in the Foundry List

Yes, it's unlisted. I found it by accident, but it's surprisingly complete as a system. Thanks for taking a look!

**Comment by gravagehulk** [comment]
> Yeah you weren't lying, that was basically a cut n paste from DnD 5e and easy to add support. It should be live now as of 0.3.66. I did a small amount of testing and everything seems to function as intended. I was testing with Core and it worked great.
> 
> I suppose I should have asked if Midi-QOL or any other rolling modules are used on SW5e? If so, I can add additional support for those since they're based on DnD 5e anyway

MIDI-QoL is supported and works brilliantly. I haven’t tried BetterRolls. Most of the modules I tested work fine. 

Thanks for jumping on this so fast! Having animations for the attacks will be great.

**Comment by otigon** [comment]
Yeah no problem, I'll release another update shortly to add support for Midi-QOL. There are alot of extra optional setting for when that is being used. Right now it is just set for "core" SW5e without any rolling modules

**Comment by gravagehulk** [comment]
You’re the man!

**Comment by otigon** [comment]
Ok, should be good to go with 0.3.67 . Let me know here or on the JB2A discord if you hit any snags (hard for me to fully test since I don't use the system much). However, given it's similarity to 5e it "should" be mostly good to go

**Comment by gravagehulk** [comment]
Thanks again! I’ve been testing that system extensively, so I should be able to provide feedback soon.  Cheers.

**Comment by gravagehulk** [comment]
Just wanted to give some feedback on this:

So far, everything is working great! Both animations and sound effects are functional and really add a lot to the experience. I have to manually set each animation for each weapon. The module doesn't know what a "Blaster Pistol" or "Blaster Rifle" is, but at least I can. Thank you so much for adding support for this system.

**Comment by otigon** [comment]
Hey thanks for the feedback! Most of the auto-recognition stuff is based on DnD5e, as I think it would get overwhelming to do that for all systems. However, for the blaster pistol animation I can certainly add some auto-recognition checks in for those since those would be most suited for a system like this.

**Comment by gravagehulk** [comment]
> Hey thanks for the feedback! Most of the auto-recognition stuff is based on DnD5e, as I think it would get overwhelming to do that for all systems. However, for the blaster pistol animation I can certainly add some auto-recognition checks in for those since those would be most suited for a system like this.

Oh, man. That would be awesome. Not expected at all, but much appreciated.
