### ISSUE TITLE
Feature Request - Aura Duration

### ISSUE THREAD

**Issue by yahavatar** [otigon/automated-jb2a-animations#96]
It would be truly handy if there was a duration setting for auras to auto-expire after a certain amount of game time. Either selecting seconds or turns.

Thanks for the awesome work, Otigon!

yah.

**Comment by otigon** [comment]
AFAIK this could only be done if using Times Up or About Time correct? I can look at adding an option for that, just need to figure out how to check the current time vs. elapsed

**Comment by yahavatar** [comment]
Absolutely! Times Up / About Time worked great for expiring the CUB conditions... well, before 0.8... so requiring that module is completely understood.

Thanks,
yah.

**Comment by otigon** [comment]
I'm going to close this issue. I looked into it a bit, but for Auras auto-expiring you might be best to use a macro with Custom Token Animations to have it start/end based on that
